### ISSUE TITLE
Hosts page broken with ZMQ interfaces

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1015]
Hosts page is always empty for ZMQ interfaces

**Comment by emanuele-f** [comment]
The cause is commit eafea969c46424f861de469fa2bb2526f0a209b2 . Now MAC 00:00:00:00:00:00, which is used in nprobe flows, is considered a special MAC address but in host_stats we only retrieve non special mac hosts (r->hostMacsOnly = true).

Reverting the change with `git diff eafea969c46424f861de469fa2bb2526f0a209b2..9139851cc9828d3c9b38de409b242b3be0d1473a src/Utils.cpp | git apply` fixes the problem.

@lucaderi please review

**Comment by simonemainardi** [comment]
why did you reopen it?

**Comment by emanuele-f** [comment]
@simonemainardi issue is not fixed, otherwise I would have closed it myself.

I only pointed out where the problem is, the MAC `00:00:00:00:00:00` is now considered a special MAC, while before it wasn't.

**Comment by simonemainardi** [comment]
Issue says "Hosts page broken with ZMQ interfaces". Hosts page now works and the issue has been fixed with: https://github.com/ntop/ntopng/commit/e5e6ff6cd851dc6a3abf16e7dda27306b64177c7

I am not sure why:
- you said "MAC 00:00:00:00:00:00, which is used in nprobe flows" while mac addresses are sent over ZMQ as all the other fields
- you proposed a patch `git diff eafea969c46424f861de469fa2bb2526f0a209b2..9139851cc9828d3c9b38de409b242b3be0d1473a src/Utils.cpp | git apply` that will break:
  - Read of MAC address read on FreeBSD
  - Read of interfaces speed for PF_RING interfaces with comma

**Comment by emanuele-f** [comment]
00:00:00:00:00:00 it's internally used by ntopng for hosts on ZMQ. That patch was never intended to be a fix, but just an evidence of the problem.

It turn out that the issue was not fixed with e5e6ff6cd851dc6a3abf16e7dda27306b64177c7 since I could reproduced it with the same synthom (hostMacsOnly=true but mac is special).

```
src/ntopng/include/ntop_defines.h:178:40: warning: comparison with string literal results in unspecified behavior [-Waddress]
 #define CONST_INTERFACE_TYPE_ZMQ       "zmq"

src/NetworkInterface.cpp:2928:20: note: in expansion of macro ‘CONST_INTERFACE_TYPE_ZMQ’
   if(get_type() == CONST_INTERFACE_TYPE_ZMQ) hostMacsOnly = false;

```

See 92c0dc18ccbb02eb0cd5957815b1b1406c63d0fe for fix
