### ISSUE TITLE
alerts detection

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#1272]
hi,
I try to find how to change alert settings cause I have lot of alerts caused by "26 flows sent in 3 sec" and/or "26 flows received in 3s"
For me "26" it's ok and they should not appear in alert, I would like to put a higher value by example

thanks

nico

**Comment by emanuele-f** [comment]
Hi, in order to change these settings, please go into a local host page and click on the "triangle" icon.

![screenshot at 2017-05-29 10-26-26](https://cloud.githubusercontent.com/assets/5488003/26542211/a8e15370-4448-11e7-9a38-8098c888d759.png)

At the bottom of the page you can set the edges which trigger the alerts:
![screenshot at 2017-05-29 10-26-40](https://cloud.githubusercontent.com/assets/5488003/26542238/bdd1b1b2-4448-11e7-862b-74160f5ac156.png)

You can either set the new edges on a per-host basis, using the left column, or globally for your local hosts, using the right column

**Comment by Niko78** [comment]
thanks

**Comment by Niko78** [comment]
I talked too quickly !
I changed value for "all hosts" but still alerts

![1](https://cloud.githubusercontent.com/assets/17108017/26543699/325082a0-445f-11e7-829b-3dbbd517d7fa.PNG)
![2](https://cloud.githubusercontent.com/assets/17108017/26543706/350722ce-445f-11e7-8ad9-cdd39f945541.PNG)

**Comment by emanuele-f** [comment]
Please increase the edges a lot so that the existing alert will get closed (e.g. 1000). After that, you can tweak the correct edges.
Are these hosts you are having such alerts routers or servers? Or are they normal PCs?

**Comment by Niko78** [comment]
ok I increased values... let's see
normal PC yes

**Comment by Niko78** [comment]
![1](https://cloud.githubusercontent.com/assets/17108017/26548212/4d4fc03e-4473-11e7-93ad-15bc067507dd.PNG)
![2](https://cloud.githubusercontent.com/assets/17108017/26548213/502f13ae-4473-11e7-9bc8-4ee5ba4670ef.PNG)

still doesn't work
but it seems to me "SYN flood" works but not "Flow flood"
+ something I don't understand => in the settings it's in "per second" and in alerts it's "in 3 seconds" ???

**Comment by emanuele-f** [comment]
I've tried to reproduce the issue in my system with no luck. Please try setting an higher value (e.g. 100000) to drop the existing alerts. The alert should be reset after a minute. If that does not help, please consider resetting your alert data through the ntopng preferenes menu.

About the "per second" question, the alert is generated if the number of flows per second of an host is above the specified edge for at least 3 seconds. So, if your edge is 10 flows/s, the host will need to cross that edge in 3 consecutive seconds in order to trigger the alert.

Note: if the alert is not resetting, then either the host is actually still above 1000 flow/s or we have a bug

**Comment by Niko78** [comment]
well I flushed alerts, not better
I even cleaned my db, still not better

**Comment by emanuele-f** [comment]
Flushing alerts data will remove existing alerts, but it will also remove the alerts configuration, so you need to immediately set a new rule for the host before the fresh alert is triggered. You can do this from the cli with the following commands:
```
redis-cli hset ntopng.prefs.alerts_global.min.local_hosts flow_attacker_threshold 100000
redis-cli hset ntopng.prefs.alerts_global.min.local_hosts flow_victim_threshold 100000
```

Please execute them immediately after the alerts flush from the preferences

**Comment by Niko78** [comment]
still not ok even with your command
in hosts preferences I can see right values but I still get alerts like that
Host xxxxxx is a Flooder (26 flows sent in 3 sec)
Host yyyyyy is under flood attack (26 flows received in 3 sec)

**Comment by emanuele-f** [comment]
First of all, after resetting the alerts from the reset button, can you actually see no alerts reported in ntopng for about one minute? I want to understand if the reset alerts actually works for you.

**Comment by Niko78** [comment]
yes I can confirm during 1 minute, nothing after reseting them
but now back again "is a Flooder (26 flows sent in 3 sec)"

**Comment by emanuele-f** [comment]
Please repeat the procedure above with redis-cli command but, this time, execute `systemclt restart ntopng` right after the last redis-cli command. It should make ntopng reload the new settings. Sorry, I know this is hacky, we will improve alerts behaviour to avoid this commands stuff.

**Comment by Niko78** [comment]
done but still the same : alerts are back with this "26 flows..."
I can share my screen (teamviewer) if you want to check by yourself

**Comment by emanuele-f** [comment]
if you go into one of your local hosts view, can you see the newly set 100000 limit? If yes, please stop ntopng, delete the alerts database manually `/var/tmp/ntopng/0/alerts/alerts_v5.db` (where 0 is your network interface id) and then restart ntopng.

**Comment by Niko78** [comment]
yep I can see 100000
done... and still same result :-(

**Comment by emanuele-f** [comment]
So, it turns out we actually had a bug. This is fixed with commit 7bfc757cbf56fbbbc5595dc6aac95f79f2e5c396 , now it will work as expected. Thank you for reporting and for your tests.

**Comment by Niko78** [comment]
hi,
this bug is back for me
I have alerts while I configure higher values

**Comment by JTCozart** [comment]
This is an issue for me as well. The alerts are very annoying and I get about 5 a day.

**Comment by emanuele-f** [comment]
Please open a new issue and report the output of `ntopng --version`. Please note that you can configure the thresholds from the "User Scripts" -> "Hosts" page
