### ISSUE TITLE
Peers tab its blank and Application Portocol  is not clickable 

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#136]
Hello ,

1. i have workstations that in "Peers" tab its blank - i have attached Screen shot 
![peers tab](https://cloud.githubusercontent.com/assets/13960741/9463842/338c8682-4b28-11e5-8338-f58ca63b1082.png)

2. in some workstations "Application Portocol " is not clickable - why ?

![application protocol](https://cloud.githubusercontent.com/assets/13960741/9463845/380b964e-4b28-11e5-93e2-7042eeb119f8.png)

**Comment by whoknowz** [comment]
I noticed that too. I figured the flows have expired, not sure.

**Comment by lucaderi** [comment]
They are not clickable because you have not enabled nDPI rrd's for such host

**Comment by AlekMarkus** [comment]
Hello luca,

1. what do you mean "for such host" ? what are the difference from this host to another ? these workstation are all the same

and where can i enable rrd ?

2. what about the tab "peers" that blank ?

**Comment by lucaderi** [comment]
You can create RRDs only for local hosts.
You can specify what RRD to create in the preferences menu. You need to enable the nDPI (L7) RRDs creation.

**Comment by AlekMarkus** [comment]
Hey luca ,

1. the problem occur in local host

2 . and the RRD creation is enabled from the first day that i have installed ntopng

![rrd](https://cloud.githubusercontent.com/assets/13960741/9492835/c6a61916-4c03-11e5-9a01-cb31933e1227.png)

**Comment by lucaderi** [comment]
Are you using the current development version of ntopng?

**Comment by AlekMarkus** [comment]
ntopng Community v.2.0.150531 i have installed rpm and not compiled from Source

is there any difference ?

**Comment by lucaderi** [comment]
update the rpm

**Comment by AlekMarkus** [comment]
---> Package ntopng.x86_64 0:2.0.150531-164 will be updated
---> Package ntopng.x86_64 0:2.0.150826-415 will be an update
--> Processing Dependency: libzmq.so.4()(64bit) for package: ntopng-2.0.150826-415.x86_64
--> Finished Dependency Resolution
Error: Package: ntopng-2.0.150826-415.x86_64 (/ntopng-2.0.150826-415.x86_64)
           Requires: libzmq.so.4()(64bit)

which package contains libzmq.so.4 ? (already installed zeromq)

**Comment by lucaderi** [comment]
Just fixed in SVN. As of the issue above see #137

**Comment by AlekMarkus** [comment]
Hey Luca,

i have installed the new version of ntopng , i can see that sometimes the peers tab is not blank and sometimes it is , as well the problem of rrd still occur , i cannot click on protocols on different hosts

please advise

**Comment by lucaderi** [comment]
The pcap files are per sub-protocol, so Apple, where we put together DNS.Apple. HTTP.Apple.... otherwise we will have too many protocols.

Reset everything and delete /var/tmp/ntopng if you want, but noting will change. Is marta a local host? I believe is not. Click on it and check.

**Comment by AlekMarkus** [comment]
Ok got it :)

1. about marta so yes , it is a local host , the workstation is near my office

2. i can see that in others hosts there  is Protocols that are clickable and some of them not (Local host)

![protocols](https://cloud.githubusercontent.com/assets/13960741/9531279/d21fa360-4d0d-11e5-8382-8e8b917f79c8.png)

**Comment by lucaderi** [comment]
Do you allow remote login? Lorenzo what do you think?

**Comment by lmangani** [comment]
@AlekMarkus please contact support@ntop.org we can arrange a remote check
