### ISSUE TITLE
Preferences: Interface Speed issue.

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#174]
If I use, as input interface, a ZC "virtual" interface or an aggregated "view" interface I can't choose an "Interface Speed" value bigger than 1000 Mbit.

In this example the view interface "view:zc:2@0,zc:2@1,zc:2@2,zc:2@3"  represents a tap interface of a 1Gbit/s full duplex link. So the Interface Speed should be 2000Mbit.
![ntopng_interface_speed](https://cloud.githubusercontent.com/assets/14093378/9956902/79c4864a-5dfc-11e5-9a2a-d0dd72ead09b.png)

I've the same problem with a ZC interface obtained as a "fan-out" (zbalance_ipc command with the option -m 2) of more than two 1Gbit/s interfaces. Also in this case I can't choose an "Interface Speed" value bigger than 1000 Mbit.

Thanks.

**Comment by gianogli** [comment]
I realized now that in the picture there is another issue related to the "view" interface. In the second graph the sum of the 2 flows (inbound and outbound) is not 554.87Mbps. I think that this graph does not represent the aggregated view but only the zc:2@0 interface.

**Comment by simonemainardi** [comment]
@gianogli  first issue has been fixed with pull request #183
second issue has already been fixed so please update ntopng to the latest dev version.

**Comment by gianogli** [comment]
It doesn't work.
If I change the "Interface Speed" (for instance from 1000 to 2000) the Interface Speed remains 1000 but the "Custom Interface Name" becomes 2000.
The two graphs are still not correlated (the first one shows 1025Mbps while the sum of the others is about 175Mbps).
![ntopng_interface_speed1](https://cloud.githubusercontent.com/assets/14093378/10134687/fbb745b4-65e7-11e5-99ac-88b32c36d2c2.png)

**Comment by lucaderi** [comment]
@simonemainardi Please check this problem.

**Comment by simonemainardi** [comment]
new pull request should fix the issue. To reset interface name to its default, please clear the corresponding field and hit save.

Regarding the issue with counters, please note that while the gauge on the left shows the total sum of all traffic, plots on the right display only local-to-remote and remote-to-local traffic. Could you please let me know if the missing traffic is actually local to local.

**Comment by gianogli** [comment]
@simonemainardi now the gauge on the left seems to work. Thanks!
About the plots on the right, instead, I think that something is wrong in fact the monitored IP traffic is almost all local-to-remote or remote-to-local (I think that only the 1/2% is local-to-local).
My local network definition is something like this: -m "X.X.X.X/18,X.X.X.X/19,X.X.X.X/21,X.X.X.X/20,X.X.X.X/21,X.X.X.X/25,X.X.X.X/24,X.X.X.X/24,X.X.X.X/24,X.X.X.X/23,X.X.X.X/23,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8". (14 different networks...) Are there too many networks? Do you made some tests with a "-m" parameter like this?

**Comment by lucaderi** [comment]
@gianogli Please open a different issue per problem. If you issue persists try to reproduce it with a simple setup.
