### ISSUE TITLE
Win8.1 x64 - ntopng service occasionally crashes

### ISSUE THREAD

**Issue by kthkaya** [ntop/ntopng#194]
Hello,

Recently installed ntopng and longest time I can browse the web GUI is 4-5 minutes. After that, the service stops and ntop becomes unreachable.

Following is the eventviewer detils

Faulting application name: ntopng.exe, version: 0.0.0.0, time stamp: 0x55fbb78a
Faulting module name: wpcap.dll, version: 4.1.0.2980, time stamp: 0x51300495
Exception code: 0xc0000005
Fault offset: 0x0000000000023d23
Faulting process id: 0x3170
Faulting application start time: 0x01d0fc90e4915ace
Faulting application path: D:\Program Files\ntopng\ntopng.exe
Faulting module path: C:\Windows\SYSTEM32\wpcap.dll
Report Id: 73973592-6884-11e5-8338-0c8bfd6c56aa
Faulting package full name: 
Faulting package-relative application ID: 

Installed winpcap is 4.1.3. Tried reinstalling but no dice.

**Comment by lucaderi** [comment]
You need to tell us how to reproduce the problem. Is there a special URL? What version of ntopng are you using?

**Comment by RHomie** [comment]
I can confirm the very same in windows server 2012 r2 x64. I am using the pre-built ntop version 2.0.150918 . this also happens in community mode. i can not quite pinpoint when this happens but happens quite frequently. one thing that i noticed, is that almost all the time, just before it crashes, these errors are produced:

02/Oct/2015 13:09:01 [NetworkInterface.cpp:973] Invalid packet received [len: 335544380][MTU: 1514].
02/Oct/2015 13:09:01 [NetworkInterface.cpp:974] WARNING: If you have TSO/GRO enabled, please disable it

**Comment by kYroL01** [comment]
@RHomie that error is because ntopng has a MTU limit, and you have to disable the TCP segmentation offload and generic segmentation offload.
Try **sudo ethtool -K [iface you use] gro off gso off tso off**

**Comment by RHomie** [comment]
@kYroL01 I am on windows so that specific command would not work. i did look through my lan driver settings and disabled couple of them that i thought might have something to do with it. I even tried a completely different NIC adapter which i'm fairly sure does not support any fancy offload feature. also, right after that error, ntopng crashes with the same error codes that kthkaya provided. So my guess is that this is a ntopng fault as the previous version is not crashing and not giving me that error.

**Comment by kthkaya** [comment]
Version	2.0.150918 - Professional Edition
Platform	Win64 (x64) - 64 bit
Built on	Windows

In order to reproduce, just install ntopng and nprobe without any fancy parameters. Right after the installation finishes, the ntopng service will fail to start and a reboot will fix that issue. Within couple of minutes after the reboot, login to localhost:3000 all works fine. In 3-5 minutes, web gui not accessible and ntopng service is down.

I was short of time therefore had to move to Ubuntu. I will keep this thread open as it seems there are others experiencing the same issue.

Btw it caught my attention once RHomie wrote about it, I have VPN adapters (Cisco VPN, Shrewsoft etc) that have different MTUs configured (none above 1500, one is 1300 another 1400).

**Comment by lucaderi** [comment]
With https://github.com/ntop/ntopng/commit/7359b5889d35ec59ea4f05218ee93d163235addf this problem should be solved A new ntopng build with the latest fixes has been integrated and according to out tests we have not seen crashes. Please give it a try and if working we'll close this bug.

**Comment by HRomie** [comment]
It's certainly gotten less frequent. But It's still getting crashed after a while (i tested it twice and got 2 crashes after 30 minutes or so. one of the crashes without any log message, the other one, with the same logs as i mentioned above, a second before the crash)

**Comment by RHomie** [comment]
It's certainly gotten less frequent. But It's still getting crashed after a while (i tested it twice and got 2 crashes after 30 minutes or so. one of the crashes without any log message, the other one, with the same logs as i mentioned above, a second before the crash).

**Comment by lucaderi** [comment]
Ok but is crashing while doing what? Are you visiting a specific page? Or are you just leaving it run as a daemon without any web access?

**Comment by kthkaya** [comment]
"Or are you just leaving it run as a daemon without any web access?"
For me it was this one. Web access for just browsing where the ntopng service starts with default settings. But when I stop the service and start with --zmq, there are absolutely no crashes. Since all my work requires --zmq, this problem is not that urgent for now

**Comment by lucaderi** [comment]
@kthkaya Can you please past the command line option that does NOT work for you and that produces crashes?

**Comment by RHomie** [comment]
lucaderi: I don't seem to be needing to do anything to trigger it. just running it in console and browsing the web is enough (no need to connect to its web interface).
The exact command that i used is: ntopng.exe /c --community -m "192.168.0.0/16,172.16.0.0/16"
I did try to reproduce it with -v switch enabled. i got a crash once which did not give much clue and still trying to get the another crash to see if i can get anything interesting.

**Comment by kthkaya** [comment]
@lucaderi 
I can't because there is none :) All command line options I tried so far works perfect. The problem is with the windows service parameters (i.e command-line options) that are set at the fresh install. Once I set the service parameters manually to anything other than fresh install parameters, all starts working like charm.

**Comment by RHomie** [comment]
To reproduce, try to download a torrent. ntopng will crash within minutes or less

**Comment by lucaderi** [comment]
I have downloaded many torrent without luck. Still trying

**Comment by RHomie** [comment]
@lucaderi Please also try to open some http websites while downloading a torrent. this could be what triggers it for me. i should also be able to provide you with crash dump if you think that could help.

If you want to get as close to my setup as it gets, i tested ntopng in vmware using a bridge interface with the host. now before you come to conclusion that its because of vmware, the old ntopng version does not crash there. and it also still crashes while using a usb lan adapter.

**Comment by lucaderi** [comment]
I don't think is VMware's fault. I have uploaded a new Win binary: please try it out and report.

**Comment by RHomie** [comment]
Confirmed. I am unable to reproduce the bug with the new build.

**Comment by lucaderi** [comment]
The above warning is ok with modern NICs. Better if you can disable TSO, but if not possible just ignore it. Glad to read I have fixed the bug. The issue is in winpcap, so mine is just a workaround but it seems  it worked. Enjoy ntopng and please star us ob github

**Comment by RHomie** [comment]
Thank you for the wonderful support. will recommend this awesome project to other colleagues as well.

**Comment by lucaderi** [comment]
Thank you for your kindness
