### ISSUE TITLE
Performance issues while using a Napatech capture card

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#2000]
Hi,

I am using ntopng with an enterprise license (for research purposes) and PF_RING ZC, with a Napatech NT4E card passed through to a KVM guest. It is assigned 4 cores and 4GB of RAM.

I'm running the latest snapshots of all the packages, the OS is Ubuntu 18.04. ntopng reads the 252 stream from the Napatech card which is configured to be an aggregate from the ports 0 and 1 of the card.

The only relevant options passed to ntopng:
-i=nt:stream252

It keeps locking up or having extremely low performance when I browse the UI. I have not pinpointed the cause of this but it is making the system unusable.  The CPU load stays at 28% give or take, so the guest is not hosed. 

I will happily provide more information if you request specifics. Is ntopng compatible with Napatech captures through PF_RING? The configuration for NTService is:

```
[Adapter0]
AdapterType = NT4E                       # NT40A01_4X1 - NT20E3_2_PTP - NT40E3_4_PTP - NT80E3_2_PTP - NT80E3_2_PTP_8X10 - NT100E3_1_PTP - NT200A01 - NT200A01_2X100 - NT200A01_2X40 - NT4E - NT20E - NT4E_STD - NT20E2 - NT40E2_1 - NT40E2_4 - NT4E2_PTP - NT20E2_PTP
DiscardSize = 16                         # 16 .. 63
HostBufferHandlerAffinity = -2           # -2 .. 3
HostBufferPollInterval = default         # default* - 100 - 250 - 500 - 1000 - 10000 - 25000 - 50000 - 100000
HostBufferSegmentTimeOut = default       # default* - 100 - 250 - 500 - 1000 - 10000 - 25000 - 50000 - 100000

HostBufferSegmentSizeRx = 4
HostBuffersTx = [4,128,-1]                # [x1, x2, x3], ...
HostBuffersRx = [4,128,-1]                # [x1, x2, x3], ...
```

**Comment by cardigliano** [comment]
Hi @vogelfreiheit, 
1. did you check the UI performance running ntopng on a standard interface?
2. could you try assigning more RAM to the VM?

**Comment by ghost** [comment]
Hi,

I have not checked running it on a normal interface yet, but I will now.
The VM has the following memory stats available:

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3992        3502         148          11         342         391
Swap:           975          13         962

$ cat /proc/meminfo | grep Huge
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:     512
HugePages_Free:      448
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

Currently 4 cores assigned, it's a 26xxv2 Xeon dual CPU system, so it can handle a good beating. 

The log with the sensitive bits edited out:

```
$ sudo ntopng -i nt:stream252 -m="10.0.0.0/8,192.168.0.0/16,172.16.0.0/16"  -n=1
08/Sep/2018 23:36:51 [Ntop.cpp:1547] Setting local networks to =10.0.0.0/8,192.168.0.0/16,172.16.0.0/16
08/Sep/2018 23:36:51 [Utils.cpp:2548] ERROR: Error parsing IPv4 =10.0.0.0
08/Sep/2018 23:36:51 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
08/Sep/2018 23:36:51 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
...
08/Sep/2018 23:36:52 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.3.0 interface nt:stream252...
08/Sep/2018 23:36:52 [Ntop.cpp:1641] Registered interface nt:stream252 [id: 3]
08/Sep/2018 23:36:52 [main.cpp:298] PID stored in file /var/run/ntopng.pid
08/Sep/2018 23:36:52 [Utils.cpp:507] User changed to ntopng
08/Sep/2018 23:36:52 [HTTPserver.cpp:1114] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
08/Sep/2018 23:36:52 [HTTPserver.cpp:1117] HTTP server listening on 3000
08/Sep/2018 23:36:52 [main.cpp:383] Working directory: /var/lib/ntopng
08/Sep/2018 23:36:52 [main.cpp:385] Scripts/HTML pages directory: /usr/share/ntopng
08/Sep/2018 23:36:52 [Ntop.cpp:390] Welcome to ntopng x86_64 v.3.7.180908 - (C) 1998-18 ntop.org
08/Sep/2018 23:36:52 [Ntop.cpp:400] Built on Ubuntu 18.04.1 LTS
...
08/Sep/2018 23:36:52 [PeriodicActivities.cpp:59] Started periodic activities loop...
08/Sep/2018 23:36:53 [PeriodicActivities.cpp:100] Each periodic activity script will use 2 threads
08/Sep/2018 23:36:53 [NetworkInterface.cpp:2564] Started packet polling on interface nt:stream252 [id: 3]...
08/Sep/2018 23:36:53 [NetworkInterface.cpp:2065] Invalid packet received [len: 1524][max len: 1518].
08/Sep/2018 23:36:53 [NetworkInterface.cpp:2066] WARNING: If you have TSO/GRO enabled, please disable it
08/Sep/2018 23:36:53 [NetworkInterface.cpp:2067] WARNING: Use sudo ethtool -K nt:stream252 gro off gso off tso off
```

I'm betting on two possible issues, one is using a single stream might lock down the polling to a single core and thus it is running on a single locking core, which could choke things a bit, but I don't know if ntopng is designed that way, and I would be surprised if this manifested in the UI.

The other issue is a problem with the PF_RING driver, but the card is cleanly passed through to the guest via vfio/IOMMU.

**Comment by ghost** [comment]
Running it on normal interfaces does not exhibit this problem.
Running multiple streams load balanced did not help, either.

**Comment by ghost** [comment]
Running nProbe works though: I can run ntopng in collector mode, with nProbe sending flows, and it works just fine. I am not sure about the implications of that or the reason nProbe is not choking while using the same interface with the same streams, but it works as expected. I suppose nProbe limits the amount of traffic it collects?

I will be happy to assist in debugging the source of the problem, as running ntopng directly with the interface is a better option in my opinion. I also don't know, yet, how to adequately protect exported flows and segregate them/classify them in ntopng.

**Comment by cardigliano** [comment]
@vogelfreiheit please try assigning more ram to the VM as it seems the system is running out of memory

**Comment by ghost** [comment]
The system is not running out of memory, check the output. A sizable part of the memory used is cached memory, which does not correlate with 1:1 physical memory footprint. 

If it was running out of memory, the OOM would kick in.

Turning off the biggest memory hose has no impact in this issue:
`n2disk    1326  132 23.0 1641592 940548 ?      SLsl 02:35 702:48 /usr/local/bin/n2disknt /run/n2disknt-uplink.conf`

Which brings us to a separate issue I might want to report in another ticket: there is no sane reason n2disk should be hitting CPU time like that when using a FPGA capture card. Something is clearly not functioning as it should within the ntop suite in this case. I haven't looked into how n2disk is implemented, but ideally, if it is done using Napatech's API (wherever it applies, be it at PF_RING or somewhere else), it should be polling an already optimized zero CPU time stream that feeds packets off the adapter's onboard RAM, into a (hopefully) RAM based hot storage (which can explain high RAM/virtual memory use) and then polled IO to disk (my single pcap file size is set to 400M). The fact that it is doing constant CPU time intensive work seems to indicate a failure to implement polling somewhere, a broken driver (or "glue code") or both. 

The documentation is a bit lacking about Napatech support, beyond bare basics. Is it possible to use Napatech's libpcap directly? ex. via LDSO redirection.

Generally speaking, in a situation like this, asking to increase physmem is a bandaid to hide a much bigger issue. 4G should be plenty to handle 50Mbit/s and very conservative settings like I have.

**Comment by cardigliano** [comment]
@vogelfreiheit we have been able to reproduce this with Napatech and ntopng, we already pushed a fix, please update from dev (github or packages) and let us know.
As of n2disk, it seems it is not affected by the same issue, it is using ~3% cpu in our lab with 50Mbit/s using Napatech, please open an issue at https://github.com/ntop/n2disk/issues providing your n2disk and napatech/ntservice configuration.

**Comment by cardigliano** [comment]
This works for me after the fix, please reopen in case.

**Comment by ghost** [comment]
I just had a chance to test... the problem is still very much present for me.

This is my NTPL file:

```
Delete = All

Setup[State=Active] = StreamId==252
Setup[State=Active] = StreamId==253
Setup[State=Active] = StreamId==253

Assign[StreamId = 252] = Port == 0 # Capture all packets from port 1
Assign[StreamId = 253] = Port == 1 # Capture all packets from port 2
Assign[StreamId = 254] = Port == 2 # Capture all packets from port 3
Assign[StreamId = 255] = Port == 3 # Capture all packets from port 4
```

If you have any thorough documentation for non-PCI passthrough/virtualized ZC, I can give that a go to see if the problem also exists there. However it should make no difference, in this case the card is passed through with IOMMU+vfio.

ntopng locks up.

**Comment by cardigliano** [comment]
@vogelfreiheit what ntopng version are you running? There is no special instruction for running ntopng on top of napatech, your ntpl configuration looks fine. After my previous fix ntopng is working smoothly on Napatech, strange that you still experience the same issue (did you see any difference?). Thank you.

**Comment by ghost** [comment]
This is the output of --version:

```
v.3.7.181019    [Enterprise/Professional build]
GIT rev:        dev:2b6673e1b4f7f1f55acffb1b3423f5ff10907cbc:20181019
Pro rev:        r2012
Built on:       Ubuntu 18.04.1 LTS
System Id:      AF8817960C030813
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:   REDACTED
License:        REDACTED
```

(I can confirm the license over e-mail)

The issues does not manifest when running nprobe as the source of flows:

```
-i=nt:stream252
-T="@NTOPNG@"
--zmq-probe-mode
--zmq=tcp://127.0.0.1:1234
-Q=1
```

The only unusual thing about this setup is that the card is passed through to the guest. I'm happy to test the ZC virtual machine capabilities if you guide me through the setup process, in that case we would not be using PCI passthrough anymore. But I doubt that is the problem. If it was, it would manifest elsewhere too.

**Comment by ghost** [comment]
```
$ sudo ntopng -i nt:stream252 --disable-autologout --verbose 5
20/Oct/2018 17:01:59 [Ntop.cpp:1558] Setting local networks to 127.0.0.0/8
20/Oct/2018 17:01:59 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
20/Oct/2018 17:01:59 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
(removed licensing information)
20/Oct/2018 17:01:59 [Ntop.cpp:347] Interfaces Available: 128
20/Oct/2018 17:01:59 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/boot.lua (iface=(nil))
20/Oct/2018 17:01:59 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:01:59 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:01:59 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:01:59 [main.cpp:164] System has 4 CPU cores
20/Oct/2018 17:01:59 [Utils.cpp:2092] Unable to read MTU for device nt:stream252
20/Oct/2018 17:01:59 [FlowProfile.cpp:18] Creating FlowProfile HTTP [0x561c95f5b670]
20/Oct/2018 17:01:59 [HostPools.cpp:84] Host Pools Available: 128
20/Oct/2018 17:01:59 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.3.0 interface nt:stream252...
20/Oct/2018 17:02:00 [Ntop.cpp:1652] Registered interface nt:stream252 [id: 3]
20/Oct/2018 17:02:00 [main.cpp:311] PID stored in file /var/run/ntopng.pid
20/Oct/2018 17:02:00 [Geolocation.cpp:162] Loaded database GeoLite2-ASN.mmdb [ip_version: 6]
20/Oct/2018 17:02:00 [Geolocation.cpp:162] Loaded database GeoLite2-City.mmdb [ip_version: 6]
20/Oct/2018 17:02:00 [HTTPserver.cpp:945] Found SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
20/Oct/2018 17:02:00 [Utils.cpp:558] User changed to ntopng
20/Oct/2018 17:02:00 [Utils.cpp:560] Umask: 022
20/Oct/2018 17:02:00 [HTTPserver.cpp:1118] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
20/Oct/2018 17:02:00 [HTTPserver.cpp:1121] HTTP server listening on 3000
20/Oct/2018 17:02:00 [main.cpp:393] Working directory: /var/lib/ntopng
20/Oct/2018 17:02:00 [main.cpp:395] Scripts/HTML pages directory: /usr/share/ntopng
20/Oct/2018 17:02:00 [Ntop.cpp:397] Welcome to ntopng x86_64 v.3.7.181019 - (C) 1998-18 ntop.org
20/Oct/2018 17:02:00 [Ntop.cpp:407] Built on Ubuntu 18.04.1 LTS
(more license data)
20/Oct/2018 17:02:00 [NtopPro.cpp:648] [LICENSE] Maintenance:   Until Sat Sep  7 16:46:16 2019 [321 days left]
20/Oct/2018 17:02:00 [Ntop.cpp:756] Local Interface Addresses (System Host)
20/Oct/2018 17:02:00 [Ntop.cpp:758] Local Networks
20/Oct/2018 17:02:00 [AddressTree.cpp:198] [AddressTree] 127.0.0.0/8
20/Oct/2018 17:02:00 [PeriodicActivities.cpp:68] Started periodic activities loop...
20/Oct/2018 17:02:00 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/startup.lua (iface=(nil))
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:00 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:01 [Utils.cpp:1194] [NAMELOOKUP_TIME 0.03][CONNECT_TIME 0.17][APPCONNECT_TIME 0.00][PRETRANSFER_TIME 0.17][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.31][TOTAL_TIME 0.58]
20/Oct/2018 17:02:01 [PeriodicActivities.cpp:109] Each periodic activity script will use 2 threads
20/Oct/2018 17:02:01 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:01 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/housekeeping.lua (iface=(nil))
20/Oct/2018 17:02:01 [NetworkInterface.cpp:2734] Started packet polling on interface nt:stream252 [id: 3]...
20/Oct/2018 17:02:01 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/discover.lua (iface=(nil))
20/Oct/2018 17:02:01 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:01 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:01 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:01 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:02 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:02 [NetworkInterface.cpp:2163] Going to reload categories..
20/Oct/2018 17:02:02 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 2]
20/Oct/2018 17:02:02 [NetworkInterface.cpp:2181] Invalid packet received [len: 1524][max len: 1518].
20/Oct/2018 17:02:02 [NetworkInterface.cpp:2182] WARNING: If you have TSO/GRO enabled, please disable it
20/Oct/2018 17:02:02 [NetworkInterface.cpp:2183] WARNING: Use sudo ethtool -K nt:stream252 gro off gso off tso off
20/Oct/2018 17:02:03 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:04 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 27]
20/Oct/2018 17:02:04 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:04 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/housekeeping.lua (iface=(nil))
20/Oct/2018 17:02:04 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:04 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:06 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 33]
20/Oct/2018 17:02:06 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/discover.lua (iface=(nil))
20/Oct/2018 17:02:06 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:06 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:06 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:07 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/housekeeping.lua (iface=(nil))
20/Oct/2018 17:02:07 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:07 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:07 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:08 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 47]
20/Oct/2018 17:02:08 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:09 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:10 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 55]
20/Oct/2018 17:02:10 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/housekeeping.lua (iface=(nil))
20/Oct/2018 17:02:10 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:10 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:10 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:11 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/discover.lua (iface=(nil))
20/Oct/2018 17:02:11 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:11 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:11 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:12 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 61]
20/Oct/2018 17:02:12 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:13 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/housekeeping.lua (iface=(nil))
20/Oct/2018 17:02:13 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:13 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:13 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
20/Oct/2018 17:02:14 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 61]
20/Oct/2018 17:02:14 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
^C20/Oct/2018 17:02:14 [main.cpp:73] Shutting down...
20/Oct/2018 17:02:14 [Ntop.cpp:1734] Terminating periodic activities
20/Oct/2018 17:02:16 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 62]
20/Oct/2018 17:02:16 [Ntop.cpp:1740] Executing shutdown script
20/Oct/2018 17:02:16 [ThreadedActivity.cpp:163] Running /usr/share/ntopng/scripts/callbacks/system/shutdown.lua (iface=(nil))
20/Oct/2018 17:02:16 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:16 [LuaEngine.cpp:187] NULL interface: did you restart ntopng in the meantime?
20/Oct/2018 17:02:16 [Ntop.cpp:1749] Terminating network interfaces
20/Oct/2018 17:02:16 [Ntop.cpp:1754] Waiting for the application to shutdown
20/Oct/2018 17:02:18 [NetworkInterface.cpp:5052] Purging idle flows [ifname: nt:stream252] [ifid: 3] [current size: 70]
20/Oct/2018 17:02:18 [ProtoStats.cpp:35] [IPv4]  255.63 KB/1.09 K Packets
20/Oct/2018 17:02:18 [ProtoStats.cpp:35] [IPv6]  368 B/4.00 Packets
20/Oct/2018 17:02:18 [ProtoStats.cpp:35] [ARP]   240 B/4.00 Packets
20/Oct/2018 17:02:18 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
20/Oct/2018 17:02:18 [ProtoStats.cpp:35] [Other] 776 B/12.00 Packets
20/Oct/2018 17:02:18 [PF_RINGInterface.cpp:242] Terminated packet polling for nt:stream252
20/Oct/2018 17:02:18 [Ntop.cpp:1722] Interface nt:stream252 [running: 0]
20/Oct/2018 17:02:18 [Ntop.cpp:1764] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
20/Oct/2018 17:02:18 [HTTPserver.cpp:1144] HTTP server terminated
20/Oct/2018 17:02:18 [NetworkInterface.cpp:748] Flushing host contacts for interface nt:stream252
```

**Comment by cardigliano** [comment]
@vogelfreiheit I tried with the same configuration, however it is working smoothly for me:

/opt/napatech3/bin/ntpl -e "Delete=All"
/opt/napatech3/bin/ntpl -e "Setup[State=Active] = StreamId==252"
/opt/napatech3/bin/ntpl -e "Assign[StreamId = 252] = Port == 0"

sudo ntopng -i nt:stream252

PCI passthrough should be fine, I would keep using your current configuration.
While we keep investigating, please provide:
- output from top/htop while ntopng is running (better if you set core affinity with -g to ntopng)
- napatech sdk version
- ingress traffic rate (bps/pps)
- any useful info from what you are seeing (discarded traffic, a detailed description of what is the behaviour now wrt the issue)
Thank you

**Comment by ghost** [comment]
I will send over the files to your e-mail address if you can provide a (spam-proof) address here.
 The Napatech SDK is the latest version. Ingress traffic is under 1gbps, usualyl 2-50mbit. Nothing to break a sweat for.

I do have a new observation: n2disk grabbing off the same stream, with ntopng, makes ntopng bite the dust. I forgot how to duplicate/serve non round robin traffic across streams so I can't test right now with different streams assigned to each application.

Edit: 23.92 Mbit/s [2,166 pps] is pretty much the peak it seems.

**Comment by cardigliano** [comment]
Please send the files to cardigliano at ntop.org

**Comment by ghost** [comment]
Sending those today!

Could you send me a barebones list of instructions to setup the PF_RING ZC virtualization so that I don't need to use PCI-E passthrough. It works but I can't really reboot the VM as the PCI-E card does not seem to know how to reset itself properly:

```
[235492.385266] vfio_bar_restore: 0000:xx:00.0 reset recovery - restoring bars
[235498.804648] vfio_bar_restore: 0000:xx:00.0 reset recovery - restoring bars
[235498.805429] vfio_bar_restore: 0000:xx:00.0 reset recovery - restoring bars
```

That will obviously slow down whatever tests I can run as hard resets are needed.

**Comment by cardigliano** [comment]
@vogelfreiheit the PF_RING ZC support for KVM is not meant to be used for replacing the PCI-e passthrough, it should be used to create inter-VM processing patterns, with a master application running on the host, and the configuration is a bit more complicated. However you can find instructions at http://www.ntop.org/guides/pf_ring/vm/kvm_zc.html
