### ISSUE TITLE
Segfault after upgrading ....

### ISSUE THREAD

**Issue by pchenry** [ntop/ntopng#2530]
Apr 15 00:53:15 netflow kernel: [ 6154.036036] ntopng[3424]: segfault at 7f87c8e58438 ip 00007f87c8e58438 sp 00007f87837fb588 error 15 in libstdc++.so.6.0.25[7f87c8e56000+a000]

root@netflow:/var/log# ntopng -V
v.3.9.190414	[Enterprise/Professional build]
GIT rev:	dev:e04c956116279d7f2bfc860e8e477f611b296d6f:20190414
Pro rev:	r2310
Built on:	Ubuntu 18.04.2 LTS

Platform:	x86_64
Edition:	Enterprise
License Type:	Permanent
Maintenance:	Until Mon Oct  7 04:33:12 2019 [175 days left]

**Comment by emanuele-f** [comment]
Please update to the today version of ntopng, as this may be already fixed in e04c956116279d7f2bfc860e8e477f611b296d6f. If not, please check out https://github.com/ntop/ntopng/blob/dev/doc/README.crash for instructions on how to get a stack trace

**Comment by pchenry** [comment]
Still happening with latest version .....     ONLY with traffic
disaggregation turned on .... this was with Ingress Interface selected ....
if I stop nprobe or set to NONE it doesnt crash.

*Apr 15 16:14:31 netflow kernel: [  428.183111] show_signal_msg: 6
callbacks suppressed*

*Apr 15 16:14:31 netflow kernel: [  428.183115] ntopng[11081]: segfault at
7f7a43b42438 ip 00007f7a43b42438 sp 00007f79fdff8588 error 15 in
libstdc++.so.6.0.25[7f7a43b40000+a000]*


*root@netflow:/etc/ntopng# ntopng -V*

*v.3.9.190415 [Enterprise/Professional build]*

*GIT rev: dev:a10c6483a2924d8a34e1978e9d9cc01d5a27fd71:20190415*

*Pro rev: r2310*

*Built on: Ubuntu 18.04.2 LTS*

*System Id: 6007602876066B13*

*Platform: x86_64*

*Edition: Enterprise*

*License Type: Permanent*

*Maintenance: Until Mon Oct  7 04:33:12 2019 [174 days left]*

*License Hash: *

*Daniel Henry*
*CEO*
*Omega Networks*
*http://omegaconnect.us <http://omegaconnect.us>*

**Comment by emanuele-f** [comment]
Please use the link above to get a stack trace

**Comment by pchenry** [comment]
Didnt get a link

*Daniel Henry*
*CEO*
*Omega Networks*
*http://omegaconnect.us <http://omegaconnect.us>*

**Comment by emanuele-f** [comment]
Maybe from email your cannot read it, here is the link again: https://github.com/ntop/ntopng/blob/dev/doc/README.crash

**Comment by emanuele-f** [comment]
Please check out the new version and in case post here a stack trace

**Comment by pchenry** [comment]
Not fixed .... Ill get a stack trace ASAP
*Daniel Henry*
*CEO*
*Omega Networks*
*http://omegaconnect.us <http://omegaconnect.us>*

**Comment by pchenry** [comment]
*root@netflow:/etc/ntopng# gdb --args ntopng /etc/ntopng/ntopng.conf*

*GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git*

*Copyright (C) 2018 Free Software Foundation, Inc.*

*License GPLv3+: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html <http://gnu.org/licenses/gpl.html>>*

*This is free software: you are free to change and redistribute it.*

*There is NO WARRANTY, to the extent permitted by law.  Type "show copying"*

*and "show warranty" for details.*

*This GDB was configured as "x86_64-linux-gnu".*

*Type "show configuration" for configuration details.*

*For bug reporting instructions, please see:*

*<http://www.gnu.org/software/gdb/bugs/
<http://www.gnu.org/software/gdb/bugs/>>.*

*Find the GDB manual and other documentation resources online at:*

*<http://www.gnu.org/software/gdb/documentation/
<http://www.gnu.org/software/gdb/documentation/>>.*

*For help, type "help".*

*Type "apropos word" to search for commands related to "word"...*

*Reading symbols from ntopng...done.*

*(gdb) run*

*Starting program: /usr/local/bin/ntopng /etc/ntopng/ntopng.conf*

*[Thread debugging using libthread_db enabled]*

*Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".*

*26/Apr/2019 02:11:41 [Ntop.cpp:1969] Setting local networks to
0.0.0.0/24,204.11.24.0/22,66.209.32.0/20,23.236.80.0/20,63.246.48.0/20,76.10.240.0/20,104.152.132.0/22,162.248.12.0/22,162.253.216.0/22,192.34.105.0/24,198.17.95.0/24,198.151.179.0/24,198.151.180.0/24,208.14.24.0/21,208.67.96.0/21,209.177.72.0/24
<http://0.0.0.0/24,204.11.24.0/22,66.209.32.0/20,23.236.80.0/20,63.246.48.0/20,76.10.240.0/20,104.152.132.0/22,162.248.12.0/22,162.253.216.0/22,192.34.105.0/24,198.17.95.0/24,198.151.179.0/24,198.151.180.0/24,208.14.24.0/21,208.67.96.0/21,209.177.72.0/24>*

*26/Apr/2019 02:11:41 [Redis.cpp:152] Successfully connected to redis
127.0.0.1:6379@0*

*26/Apr/2019 02:11:41 [Redis.cpp:152] Successfully connected to redis
127.0.0.1:6379@0*

*26/Apr/2019 02:11:41 [NtopPro.cpp:314] [LICENSE] Reading license from
Redis*

*26/Apr/2019 02:11:41 [NtopPro.cpp:208] [LICENSE]
EC4C400AD2B52EE5CEFDFE625A2B24F91570422792FDE34C59: found valid Enterprise
license*

*[New Thread 0x7fffe8ee3700 (LWP 4341)]*

*[New Thread 0x7fffe86e2700 (LWP 4342)]*

*26/Apr/2019 02:11:42 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [id: 4]*

*26/Apr/2019 02:11:42 [main.cpp:304] PID stored in file /var/run/ntopng.pid*

*26/Apr/2019 02:11:42 [Utils.cpp:690] User changed to ntopng*

*[New Thread 0x7fffe6f5b700 (LWP 4343)]*

*[New Thread 0x7fffe675a700 (LWP 4344)]*

*[New Thread 0x7fffe5f59700 (LWP 4345)]*

*[New Thread 0x7fffe5758700 (LWP 4346)]*

*[New Thread 0x7fffe4f57700 (LWP 4347)]*

*[New Thread 0x7fffcffff700 (LWP 4348)]*

*26/Apr/2019 02:11:42 [HTTPserver.cpp:1333] Web server dirs
[/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]*

*26/Apr/2019 02:11:42 [HTTPserver.cpp:1336] HTTP server listening on 3000*

*26/Apr/2019 02:11:42 [main.cpp:379] Working directory: /var/lib/ntopng*

*26/Apr/2019 02:11:42 [main.cpp:381] Scripts/HTML pages directory:
/usr/share/ntopng*

*26/Apr/2019 02:11:42 [Ntop.cpp:429] Welcome to ntopng x86_64 v.3.9.190425
- (C) 1998-19 ntop.org <http://ntop.org>*

*26/Apr/2019 02:11:42 [Ntop.cpp:439] Built on Ubuntu 18.04.2 LTS*

*26/Apr/2019 02:11:42 [NtopPro.cpp:650] [LICENSE] System Id:
6007602876066B13*

*26/Apr/2019 02:11:42 [NtopPro.cpp:651] [LICENSE] Edition: Enterprise*

*26/Apr/2019 02:11:42 [NtopPro.cpp:652] [LICENSE] License Type: Permanent
License*

*26/Apr/2019 02:11:42 [NtopPro.cpp:666] [LICENSE] License Hash:
EC4C400AD2B52EE5CEFDFE625A2B24F91570422792FDE34C59*

*26/Apr/2019 02:11:42 [NtopPro.cpp:676] [LICENSE] Maintenance: Until Mon
Oct  7 04:33:12 2019 [164 days left]*

*[New Thread 0x7fffcf7fe700 (LWP 4349)]*

*[New Thread 0x7fffceffd700 (LWP 4350)]*

*26/Apr/2019 02:11:42 [PeriodicActivities.cpp:72] Started periodic
activities loop...*

*26/Apr/2019 02:11:44 [PeriodicActivities.cpp:113] Each periodic activity
script will use 2 threads*

*[New Thread 0x7fffce7fc700 (LWP 4369)]*

*[New Thread 0x7fffcdffb700 (LWP 4370)]*

*[New Thread 0x7fffcd7fa700 (LWP 4371)]*

*[New Thread 0x7fffccff9700 (LWP 4372)]*

*[New Thread 0x7fffb7fff700 (LWP 4373)]*

*[New Thread 0x7fffb77fe700 (LWP 4374)]*

*[New Thread 0x7fffb6ffd700 (LWP 4375)]*

*[New Thread 0x7fffb67fc700 (LWP 4376)]*

*[New Thread 0x7fffb5ffb700 (LWP 4377)]*

*[New Thread 0x7fffb57fa700 (LWP 4378)]*

*[New Thread 0x7fffb4ff9700 (LWP 4379)]*

*[New Thread 0x7fffaffff700 (LWP 4380)]*

*[New Thread 0x7fffaf7fe700 (LWP 4381)]*

*[New Thread 0x7fffaeffd700 (LWP 4382)]*

*[New Thread 0x7fffae7fc700 (LWP 4383)]*

*26/Apr/2019 02:11:44 [NetworkInterface.cpp:2717] Started packet polling on
interface tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [id: 4]...*

*26/Apr/2019 02:11:45 [ZMQCollectorInterface.cpp:148] Collecting flows on
tcp://127.0.0.1:5555 <http://127.0.0.1:5555>*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 108] [id: 13]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 74] [id: 12]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 75] [id: 8]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 126] [id: 9]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 112] [id: 7]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 116] [id: 10]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 115] [id: 11]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 13] [id: 5]*

*26/Apr/2019 02:11:45 [Ntop.cpp:2061] Registered interface
tcp://127.0.0.1:5555 <http://127.0.0.1:5555> [If Idx: 12] [id: 6]*


*Thread 26 "ntopng" received signal SIGSEGV, Segmentation fault.*

*[Switching to Thread 0x7fffae7fc700 (LWP 4383)]*

*0x00007ffff492e438 in vtable for __cxxabiv1::__si_class_type_info ()*

*   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6*

*(gdb) bt*

*#0  0x00007ffff492e438 in vtable for __cxxabiv1::__si_class_type_info ()*

*   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6*

*#1  0x0000555555654743 in ZMQParserInterface::parseEvent
(this=0x555555e726f0, *

*    payload=0x7fff9c000e30 "{ \"iface\": { \"name\": \"none\", \"speed\":
1000, \"ip\": \"\" }, \"probe\": { \"ip\": \"104.239.141.196\",
\"public_ip\": \"\" }, \"time\" : 1556244702.855, \"bytes\": 0,
\"packets\": 0, \"avg\": { \"bps\": 0, \"pps\": 0 }, \"drops\""...,
payload_size=439, source_id=0 '\000', *

*    data=0x555555e726f0) at src/ZMQParserInterface.cpp:244*

*#2  0x00005555555a1d86 in ZMQCollectorInterface::collect_flows (*

*    this=0x555555e726f0) at src/ZMQCollectorInterface.cpp:264*

*#3  0x00005555555a1f91 in packetPollLoop (ptr=0x555555e726f0)*

*    at src/ZMQCollectorInterface.cpp:310*

*#4  0x00007ffff675c6db in start_thread (arg=0x7fffae7fc700)*

*    at pthread_create.c:463*

*#5  0x00007ffff40cb88f in clone ()*

*    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95*
*(gdb) *


*Daniel Henry*
*CEO*
*Omega Networks*
*http://omegaconnect.us <http://omegaconnect.us>*

**Comment by emanuele-f** [comment]
What is the "Disaggregation Criterion" you have set in the "Network Interfaces" preferences in ntopng?

**Comment by simonemainardi** [comment]
I've pushed a fix for this. New builds are being generated. Please, hold on an our and re-try. Thank you.
