### ISSUE TITLE
ElasticSearch flow-dump stopped working...

### ISSUE THREAD

**Issue by dboehlke** [ntop/ntopng#257]
I thought I had ElasticSearch configured, however when I went to use Kibana, I didn't see the number of records there that I expected.  I had a few hundred, but I expected many many more.

Thinking this was an ElasticSearch problem, I removed and reinstalled ElasticSearch and Kibana4, in the process I went from ElasticSearch 1.7 to version 2.

Here is my configuration:

```
cat /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-d=/var/tmp/ntopng
-p=/etc/ntopng/protos.txt 
-i=tcp://10.60.59.14:5556
-i=tcp://10.60.59.14:5557
--dump-flows="es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;"
--dns-mode=1
--sticky-hosts=none
--disable-login=1
--local-networks="2606:4A80::/32,192.168.0.0/24,172.16.0.0/16,10.0.0.0/8,38.81.66.0/23,209.208.232.0/23,209.208.241.0/24,209.208.250.0/24,50.93.246.0/23,50.93.255.0/24,162.222.47.0/24,216.17.8.0/24,38.92.136.0/24,162.222.40.0/21,162.222.40.0/23,162.222.46.0/24,103.8.239.0/24,149.5.7.0/24"
-w=3000
```

I used sysdig to monitor traffic on port 9200 and I saw:

```
$ sudo sysdig -A  -c echo_fds fd.port=9200
...
------ Write 6.26KB to   127.0.0.1:34335->127.0.0.1:9200 (ntopng)

{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "10.60.81.2", "L4_SRC_PORT": 60981, "IPV4_DST_ADDR": "10.60.126.200", "L4_DST_PORT": 514, "PROTOCOL": 17, "L7_PROTO": 17, "L7_PROTO_NAME": "Syslog", "IN_PKTS": 5000, "IN_BYTES": 1830000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "522", "14": "605", "152": "1446672904000", "153": "1446672904000", "5": "0", "16": "0", "17": "0", "9": "0", "13": "0", "42": "1296145" }, "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.52", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "24.15.235.77", "L4_DST_PORT": 56664, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 10000, "IN_BYTES": 400000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "518", "14": "551", "152": "1446672906000", "153": "1446672906000", "5": "0", "16": "62715", "17": "7922", "9": "0", "13": "0", "42": "1296330" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.433899, 44.951801 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -88.079803, 42.042801 ], "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.7", "L4_SRC_PORT": 46976, "IPV4_DST_ADDR": "38.81.67.32", "L4_DST_PORT": 4283, "PROTOCOL": 6, "L7_PROTO": 221, "L7_PROTO_NAME": "CrashPlan-Engine", "TCP_FLAGS": 24, "IN_PKTS": 10000, "IN_BYTES": 7410000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "517", "14": "552", "152": "1446672905000", "153": "1446672905000", "5": "0", "16": "62715", "17": "174", "9": "0", "13": "0",
------ Read 6.26KB from   127.0.0.1:34335->127.0.0.1:9200 (java)

{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "10.60.81.2", "L4_SRC_PORT": 60981, "IPV4_DST_ADDR": "10.60.126.200", "L4_DST_PORT": 514, "PROTOCOL": 17, "L7_PROTO": 17, "L7_PROTO_NAME": "Syslog", "IN_PKTS": 5000, "IN_BYTES": 1830000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "522", "14": "605", "152": "1446672904000", "153": "1446672904000", "5": "0", "16": "0", "17": "0", "9": "0", "13": "0", "42": "1296145" }, "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.52", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "24.15.235.77", "L4_DST_PORT": 56664, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 10000, "IN_BYTES": 400000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "518", "14": "551", "152": "1446672906000", "153": "1446672906000", "5": "0", "16": "62715", "17": "7922", "9": "0", "13": "0", "42": "1296330" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.433899, 44.951801 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -88.079803, 42.042801 ], "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.7", "L4_SRC_PORT": 46976, "IPV4_DST_ADDR": "38.81.67.32", "L4_DST_PORT": 4283, "PROTOCOL": 6, "L7_PROTO": 221, "L7_PROTO_NAME": "CrashPlan-Engine", "TCP_FLAGS": 24, "IN_PKTS": 10000, "IN_BYTES": 7410000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "517", "14": "552", "152": "1446672905000", "153": "1446672905000", "5": "0", "16": "62715", "17": "174", "9": "0", "13": "0",
------ Write 135B to   127.0.0.1:34335->127.0.0.1:9200 (java)

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=UTF-8
Content-Length: 46

No handler found for uri [/] and method [POST]
...
```

I am able to post this data into ElasticSearch by hand using curl:

```
$ curl -XPOST localhost:9200/_bulk -d '
> {"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
> { "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.88", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "69.120.158.254", "L4_DST_PORT": 58018, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 40000, "IN_BYTES": 1600000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "522", "14": "552", "152": "1446672875000", "153": "1446672906000", "5": "0", "16": "62715", "17": "6128", "9": "0", "13": "0", "42": "1296332" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.433899, 44.951801 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -73.920898, 40.819500 ], "PASS_VERDICT": true }
> {"index": {"_type": "ntopng", "_index": "ntopng-2015.11.04"}}
> { "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "10.60.50.1", "L4_SRC_PORT": 50897, "IPV4_DST_ADDR": "10.60.126.200", "L4_DST_PORT": 514, "PROTOCOL": 17, "L7_PROTO": 17, "L7_PROTO_NAME": "Syslog", "IN_PKTS": 5000, "IN_BYTES": 2225000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "521", "14": "605", "152": "1446672904000", "153": "1446672904000", "5": "0", "16": "0", "17": "0", "9": "0", "13": "0", "42": "1296103" }, "PASS_VERDICT": true }
> '
{"took":65,"errors":false,"items":[{"create":{"_index":"ntopng-2015.11.04","_type":"ntopng","_id":"AVDUbuWdaPfKFbT_UFX5","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.04","_type":"ntopng","_id":"AVDUbuWdaPfKFbT_UFX6","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}}]}
```

I can then see the document in the Index:

```
$ sudo curl 'localhost:9200/_cat/indices?v'
health status index             pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   ntopng-2015.11.04   5   1          4            0     64.6kb         64.6kb 
yellow open   .kibana             1   1          3            0     12.9kb         12.9kb 
```

I can retrieve the documents I have stored:

```
$ curl 'localhost:9200/ntopng-2015.11.04/_search?pretty'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 4,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "ntopng-2015.11.04",
      "_type" : "ntopng",
      "_id" : "AVDUbuWdaPfKFbT_UFX5",
      "_score" : 1.0,
      "_source":{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.88", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "69.120.158.254", "L4_DST_PORT": 58018, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 40000, "IN_BYTES": 1600000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "522", "14": "552", "152": "1446672875000", "153": "1446672906000", "5": "0", "16": "62715", "17": "6128", "9": "0", "13": "0", "42": "1296332" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.433899, 44.951801 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -73.920898, 40.819500 ], "PASS_VERDICT": true }
    }, {
      "_index" : "ntopng-2015.11.04",
      "_type" : "ntopng",
      "_id" : "AVDUXSQWaPfKFbT_UFXy",
      "_score" : 1.0,
      "_source":{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "216.17.8.11", "L4_SRC_PORT": 43617, "IPV4_DST_ADDR": "162.222.41.178", "L4_DST_PORT": 4283, "PROTOCOL": 6, "L7_PROTO": 221, "L7_PROTO_NAME": "CrashPlan-Engine", "TCP_FLAGS": 24, "IN_PKTS": 0, "IN_BYTES": 0, "OUT_PKTS": 20000, "OUT_BYTES": 800000, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "640", "14": "528", "152": "1446671781000", "153": "1446671781000", "5": "0", "16": "62715", "17": "62715", "9": "0", "13": "0", "42": "2667076" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.433899, 44.951801 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -93.216599, 44.975899 ], "PASS_VERDICT": true }
    }, {
      "_index" : "ntopng-2015.11.04",
      "_type" : "ntopng",
      "_id" : "AVDUbuWdaPfKFbT_UFX6",
      "_score" : 1.0,
      "_source":{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "10.60.50.1", "L4_SRC_PORT": 50897, "IPV4_DST_ADDR": "10.60.126.200", "L4_DST_PORT": 514, "PROTOCOL": 17, "L7_PROTO": 17, "L7_PROTO_NAME": "Syslog", "IN_PKTS": 5000, "IN_BYTES": 2225000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "521", "14": "605", "152": "1446672904000", "153": "1446672904000", "5": "0", "16": "0", "17": "0", "9": "0", "13": "0", "42": "1296103" }, "PASS_VERDICT": true }
    }, {
      "_index" : "ntopng-2015.11.04",
      "_type" : "ntopng",
      "_id" : "AVDUXSQWaPfKFbT_UFXz",
      "_score" : 1.0,
      "_source":{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "162.222.41.91", "L4_SRC_PORT": 4283, "IPV4_DST_ADDR": "216.17.8.48", "L4_DST_PORT": 44257, "PROTOCOL": 6, "L7_PROTO": 221, "L7_PROTO_NAME": "CrashPlan-Engine", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 800000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "624", "14": "528", "152": "1446671781000", "153": "1446671781000", "5": "0", "16": "62715", "17": "62715", "9": "0", "13": "0", "42": "2666853" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.216599, 44.975899 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -93.433899, 44.951801 ], "PASS_VERDICT": true }
    } ]
  }
}
```

The retrieved records are all ones that I have written by hand testing.

However ntopng appears to be unable to write any records into ElasticSearch.  Is this an incompatibility with ElasticSearch2, if so, what versions are supported.

Thank you in advance for your help.

**Comment by lmangani** [comment]
Confirmed, investigating

**Comment by dboehlke** [comment]
As further information I offer my ElasticSearch version and ntopng version:

```
$ curl localhost:9200
{
  "name" : "Chondu the Mystic",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

I am running ntopng Professional v.2.1.151104.

```
04/Nov/2015 15:13:24 [Prefs.cpp:661] Using ElasticSearch for data dump [ntopng][ntopng-%Y.%m.%d][http://localhost:9200/_bulk]
04/Nov/2015 15:13:24 [Prefs.cpp:612] All HTTP user login disabled
04/Nov/2015 15:13:24 [Ntop.cpp:931] Setting local networks to 2606:4A80::/32,192.168.0.0/24,172.16.0.0/16,10.0.0.0/8,38.81.66.0/23,209.208.232.0/23,209.208.241.0/24,209.208.250.0/24,50.93.246.0/23,50.93.255.0/24,162.222.47.0/24,216.17.8.0/24,38.92.136.0/24,162.222.40.0/21,162.222.40.0/23,162.222.46.0/24,103.8.239.0/24,149.5.7.0/24
04/Nov/2015 15:13:24 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
04/Nov/2015 15:13:24 [NtopPro.cpp:120] [LICENSE] Reading license from /etc/ntopng.license
04/Nov/2015 15:13:24 [Ntop.cpp:1180] Registered interface view tcp://10.60.59.14:5556 [id: 1]
04/Nov/2015 15:13:24 [Ntop.cpp:1150] Registered interface tcp://10.60.59.14:5556 [id: 0]
04/Nov/2015 15:13:24 [Ntop.cpp:1180] Registered interface view tcp://10.60.59.14:5557 [id: 11]
04/Nov/2015 15:13:24 [Ntop.cpp:1150] Registered interface tcp://10.60.59.14:5557 [id: 1]
04/Nov/2015 15:13:24 [Utils.cpp:304] User changed to nobody
04/Nov/2015 15:13:24 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
04/Nov/2015 15:13:24 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
04/Nov/2015 15:13:24 [HTTPserver.cpp:501] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
04/Nov/2015 15:13:24 [HTTPserver.cpp:504] HTTP server listening on port 3000
04/Nov/2015 15:13:24 [main.cpp:290] Working directory: /var/tmp/ntopng
04/Nov/2015 15:13:24 [main.cpp:292] Scripts/HTML pages directory: /usr/share/ntopng
04/Nov/2015 15:13:24 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.1.151104 - (C) 1998-15 ntop.org
04/Nov/2015 15:13:24 [Ntop.cpp:265] Built on Ubuntu 12.04.5 LTS
04/Nov/2015 15:13:24 [PeriodicActivities.cpp:53] Started periodic activities loop...
04/Nov/2015 15:13:24 [RuntimePrefs.cpp:32] Dumping alerts into syslog
04/Nov/2015 15:13:24 [NtopPro.cpp:234] [LICENSE] ntopng systemId: CDD6A54E9206AB23
04/Nov/2015 15:13:24 [NtopPro.cpp:245] [LICENSE] ntopng license: DCF4E7A8AFF4F27B49E12B8E19B2D51A1475685990201C735E
04/Nov/2015 15:13:24 [NtopPro.cpp:266] [LICENSE] Maintenance is available until Wed Oct  5 11:46:30 2016 [335 days left]
04/Nov/2015 15:13:24 [NetworkInterface.cpp:1452] Started packet polling on interface tcp://10.60.59.14:5556 [id: 1]...
04/Nov/2015 15:13:24 [NetworkInterface.cpp:1452] Started packet polling on interface tcp://10.60.59.14:5557 [id: 11]...
04/Nov/2015 15:13:25 [CollectorInterface.cpp:93] Collecting flows on tcp://10.60.59.14:5556
04/Nov/2015 15:13:25 [CollectorInterface.cpp:93] Collecting flows on tcp://10.60.59.14:5557
```

:-)

**Comment by lmangani** [comment]
The CURL address in POST seems to be missing the trailing /_bulk causing the error

**Comment by lmangani** [comment]
Suspended offending new function while fix in progress. 
Please re-test from GIT or nightly build tomorrow.

**Comment by simonemainardi** [comment]
Thanks @dboehlke  and @lmangani for pointing out the issue. It should have been fixed now. Please, let me know.

**Comment by dboehlke** [comment]
It looks like it is working now:

```
$ sudo sysdig -A -pc -c echo_fds fd.port=9200 | head -1000
------ Write 6.48KB to  [host] [host]  127.0.0.1:50817->127.0.0.1:9200 (ntopng)

{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.05"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "162.222.40.85", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "96.88.197.217", "L4_DST_PORT": 20930, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 800000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "579", "14": "597", "152": "1446743850000", "153": "1446743850000", "5": "0", "16": "62715", "17": "7922", "9": "0", "13": "0", "42": "72945" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.216599, 44.975899 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -76.989799, 38.879002 ], "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.05"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "65.90.67.4", "L4_SRC_PORT": 2495, "IPV4_DST_ADDR": "162.222.46.22", "L4_DST_PORT": 443, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 28400000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "528", "14": "662", "152": "1446743849000", "153": "1446743849000", "5": "0", "16": "3356", "17": "62715", "9": "0", "13": "0", "42": "72904" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -73.542900, 41.061001 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -93.216599, 44.975899 ], "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.05"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "162.222.41.60", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "67.188.37.206", "L4_DST_PORT": 63200, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 1040000, "OUT_PKTS": 0
------ Read 6.48KB from  [host] [host]  127.0.0.1:50817->127.0.0.1:9200 (java)

{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.05"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "162.222.40.85", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "96.88.197.217", "L4_DST_PORT": 20930, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 800000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "579", "14": "597", "152": "1446743850000", "153": "1446743850000", "5": "0", "16": "62715", "17": "7922", "9": "0", "13": "0", "42": "72945" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -93.216599, 44.975899 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -76.989799, 38.879002 ], "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.05"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "65.90.67.4", "L4_SRC_PORT": 2495, "IPV4_DST_ADDR": "162.222.46.22", "L4_DST_PORT": 443, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 28400000, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 0, "LAST_SWITCHED": 0, "json": { "15": "0.0.0.0", "10": "528", "14": "662", "152": "1446743849000", "153": "1446743849000", "5": "0", "16": "3356", "17": "62715", "9": "0", "13": "0", "42": "72904" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -73.542900, 41.061001 ], "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -93.216599, 44.975899 ], "PASS_VERDICT": true }
{"index": {"_type": "ntopng", "_index": "ntopng-2015.11.05"}}
{ "@timestamp": "1970-01-01T00:00:00.0Z", "type": "ntopng", "IPV4_SRC_ADDR": "162.222.41.60", "L4_SRC_PORT": 443, "IPV4_DST_ADDR": "67.188.37.206", "L4_DST_PORT": 63200, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 16, "IN_PKTS": 20000, "IN_BYTES": 1040000, "OUT_PKTS": 0
------ Write 1.39KB to  [host] [host]  127.0.0.1:50817->127.0.0.1:9200 (java)

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 1331

{"took":3,"errors":false,"items":[{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXa","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXb","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXc","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXd","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXe","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXf","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXg","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXh","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}}]}
------ Read 1.39KB from  [host] [host]  127.0.0.1:50817->127.0.0.1:9200 (ntopng)

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 1331

{"took":3,"errors":false,"items":[{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXa","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXb","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXc","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXd","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXe","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXf","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXg","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}},{"create":{"_index":"ntopng-2015.11.05","_type":"ntopng","_id":"AVDYp7hlaPfKFbT_UmXh","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"status":201}}]}
```

I am still not getting as many records as I expect in ElasticSearch, but it appears to be a timestamp issue.  I will open another ticket for this.

--
Dan Boehlke

**Comment by lmangani** [comment]
Thanks for the confirmation @dboehlke 
For timestamp related issues, please make sure all your probes are ntp synced
