### ISSUE TITLE
ubuintu 18.04LTS / Logrotate package  require ntopng to be mode 644

### ISSUE THREAD

**Issue by HaleyACS** [ntop/ntopng#2815]
Out of the Box and Update of ntopng package on Ubunt 18.04.x LTS causes
logrotate for ntopng to be skipped skipped if mode of /etc/logrotate.d/ntopng is not 644.

Error message coming via mail from cron looks like this:
`/etc/cron.daily/logrotate:
error: Ignoring ntopng because of bad file mode - must be 0644 or 0444.`

Changing the file mode to 0644 is enough.

**Comment by cardigliano** [comment]
Fixed

# ls -al /etc/logrotate.d/ntopng
-rw-r--r-- 1 root root 151 Sep 17 11:06 /etc/logrotate.d/ntopng

**Comment by noybman** [comment]
This is still a problem. It has been happening since November 2019 easily. I've fixed this last month and recent updates my emails (even tonight's):

/etc/cron.daily/logrotate:
error: Ignoring disk2n because of bad file mode - must be 0644 or 0444.
error: Ignoring n2disk because of bad file mode - must be 0644 or 0444.
error: Ignoring nprobe because of bad file mode - must be 0644 or 0444.

**Comment by cardigliano** [comment]
@noybman please note those errors were related to nprobe/n2disk, not ntopng. The've been also fixed now, next package will contain the fix. Thank you for reporting.
