### ISSUE TITLE
Various errors in logs & GUI

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#3014]
Hello,

After updating to 3.9.191027-7971 on debian buster I can see these in logs:

```
Oct 27 11:04:36 gemma ntopng[4841]: 27/Oct/2019 11:04:36 [LuaEngine.cpp:11050] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...backs/status_defs/status_device_protocol_not_allowed.lua:30: attempt to concatenate a nil value (local 'devtype')]
Oct 27 11:04:39 gemma ntopng[4841]: 27/Oct/2019 11:04:39 [LuaEngine.cpp:11050] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...backs/status_defs/status_device_protocol_not_allowed.lua:30: attempt to concatenate a nil value (local 'devtype')]
Oct 27 11:04:42 gemma ntopng[4841]: 27/Oct/2019 11:04:42 [LuaEngine.cpp:11050] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...backs/status_defs/status_device_protocol_not_allowed.lua:30: attempt to concatenate a nil value (local 'devtype')]
```
Also, the flows tab doesn't display any flow information (active flows says No results found) but I can see traffic information in traffic dashboard.

![image](https://user-images.githubusercontent.com/38040820/67631008-dea49400-f8a9-11e9-8580-dd1241a03cb9.png)
![image](https://user-images.githubusercontent.com/38040820/67631012-eb28ec80-f8a9-11e9-83db-d2f2d7d643a9.png)

Also, going back and forth between different interfaces crashes ntopng:

```
Oct 27 11:08:18 gemma systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Oct 27 11:08:18 gemma systemd[1]: ntopng.service: Failed with result 'signal'.
Oct 27 11:08:24 gemma systemd[1]: ntopng.service: Service RestartSec=5s expired, scheduling restart.
Oct 27 11:08:24 gemma systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 6.
Oct 27 11:08:24 gemma systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Oct 27 11:08:24 gemma systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...

```

**Comment by emanuele-f** [comment]
For the device type nil issue, please wait for the next package (fixed in aea6d00c56b27b7cfd2f7bb000d3d377f663375d). Regarding empty active flows page, please check out the ntopng logs to see if there is an error reported `sudo journalctl -u ntopng`. For the crash, can you please provide a stack trace as described in https://github.com/ntop/ntopng/blob/dev/doc/README.crash ?

**Comment by fsamareanu** [comment]
Problem 1: waiting for the build. 3.9.191028-7984 doesn't fix it.
Problem 2: empty active flows: nothing in the log (attached)
[startup log.txt](https://github.com/ntop/ntopng/files/3779819/startup.log.txt)

Problem 3: Attached the stack trace.
[bt.txt](https://github.com/ntop/ntopng/files/3779810/bt.txt)

**Comment by fsamareanu** [comment]
With the latest update (3.9.191029-7992) my syslog gets filled with lines like this:

`Oct 29 09:42:06 gemma ntopng: [29/10/2019 09:38:50][Error][Suspicious Device Protocol][Flow][flow] Suspicious Device Protocol [Flow: redacted-pihole.local.lan@1... one.one.one.one@100] [UDP] [Application: DNS]`

And these:

```
Oct 29 10:03:03 gemma ntopng: [29/10/2019 10:02:01][Error][Packet Drops][Interface][iface_13][Released] interface enp4s0.102 has too many dropped packets [&gt 5%]
Oct 29 10:03:03 gemma ntopng: [29/10/2019 10:02:01][Error][Packet Drops][Interface][iface_17][Released] interface view:enp4s0.100,enp4s0.101,enp4s0.102,enp4s0.103,enp4s0.104 has too many dropped packets [&gt 5%]

```
However, there are no drops on the interface:

```
enp4s0.102: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::4262:31ff:fe01:77c5  prefixlen 64  scopeid 0x20<link>
        ether 40:62:31:01:77:c5  txqueuelen 1000  (Ethernet)
        RX packets 54639032  bytes 55841655684 (52.0 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4257  bytes 365469 (356.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by emanuele-f** [comment]
Can you post your /etc/ntopng/ntopng.conf configuration?

**Comment by emanuele-f** [comment]
Crash should be fixed in 883c268f7c9824c733f5a5c07e1399bc138f8d7e (new package available in one hour).

Regarding the syslog issue, do you have the syslog alert endpoint enabled into the ntopng preferences?

**Comment by fsamareanu** [comment]
Sure, config below:

```
-G=/var/run/ntopng.pid
-i=enp4s0.100
-i=enp4s0.101
-i=enp4s0.102
-i=enp4s0.103
-i=enp4s0.104
-i view:enp4s0.100,enp4s0.101,enp4s0.102,enp4s0.103,enp4s0.104
-m="192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
-n=0
-F "mysql;127.0.0.1;ntopng;flows;ntopng;RedactedP@ssw0rd"
--http-prefix="/ntopng"
-l=1
-w :3000
-d=/data/var/lib/ntopng
--redis=127.0.0.1:6379:RedactedP@ssw0rd
```
Also, yes I did seem to have syslog alert endpoint enabled although I don't remember ever doing it. Besides, why do DNS requests qualify as "suspicious" flow?
Regarding the empty flow list, any more ideas?

**Comment by emanuele-f** [comment]
Such alerts are generated based on the "Device Applications" configuration. If you browse the past flow alerts via the ntopng gui and filter by "Suspicious Device Protocols" you should be able to get more information about a specific alert.
Regarding the empty flows list, does this only happen on the View interface (`-i view:enp4s0...`)?

**Comment by fsamareanu** [comment]
For example this flow:

192.168.100.3:44764  9.9.9.10:53

Under additional flow status there's this:

Remote client and remote server
Suspicious Device Protocol

But 192.168.100.3 is local (based on -m setting)

And yes, seems only the view is not reporting any flows. If i select the individual interfaces I see traffic (but the counters are much lower than actual traffic).

From a linux server in the same vlan (100) I did this:

fsamareanu@gemma:~$ curl -o /dev/null http://209.58.153.1/speedtest/10000mb.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 9536M    1  121M    0     0  5383k      0  0:30:13  0:00:23  0:29:50 6513k

This flow doesn't show at all in flow list and traffic is capped @ 33 kbps

**Comment by fsamareanu** [comment]
After today's update (3.9.191104-8040) I changed the config to this:

-G=/var/run/ntopng.pid
-i=enp4s0
-m="192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
-n=0
-F "mysql;127.0.0.1;ntopng;flows;ntopng;PasswordHere"
--http-prefix="/ntopng"
-l=1
-w :3000
-d=/data/var/lib/ntopng
--redis=127.0.0.1:6379:PasswordHere

and all VLANs on the mirror port were discovered (not sure if automatically or there's another setting that was enabled previously) and traffic counters seem ok as well. I'm not really sure if you fixed it or not but a confirmation wouldn't hurt anyway.

Thank you for the work done on ntopng, it's a great product.

**Comment by simonemainardi** [comment]
Thanks for reporting.
