### ISSUE TITLE
ntopng sizing recommendations

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#312]
I have ntopng collecting sflow from a few network devices (~10% of my planned total deployment) but I seem to be crashing ntopng after a day or so of operation.

When I navigate through the web interface I end up generating page load timeouts which stops any page from loading
Logs I see are:
```
09/Dec/2015 12:40:02 [Lua.cpp:4766] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_grouped_hosts_data.lua][not enough memory]
```

at that point I am tracking ~117,000 hosts and ~750 flows

my server is 2 cpu 4GB memory
i have data purge set to the following:
local host idle timeout: 900s
remote host idle timeout: 180s
flow idle timeout: 180s

i expect that it is a sizing issue on my part
is there any sizing guideline? if i expect to handle 10-20 times the amount of data (which would only be ~30Mbps from the sum of my sflow generators) what would i need to do?

i collected a core from after ntopng hung if it's any help (https://www.dropbox.com/s/11hzzyizehwtbns/core.ntopng.18366.flows.1449694157.gz?dl=0)

**Comment by simonemainardi** [comment]
Hi, ntopng can handle traffic at rates that are much higher than ~30Mbps.

The fact that you have only 750 flows with 117k hosts, suggest me that you should purge hosts more frequently. Try to purge remote hosts once every minute and local hosts every 3 to 5 minutes. 

Also, could you please check the load of the server that is running ntopng. Is it heavily loaded?

**Comment by seismiccollision** [comment]
@lmangani The vast majority of hosts are remote hosts but per my above settings I had the remote hosts clearing every 3 minutes. I have reduced the timeouts to the following and will see if that helps:
local host idle timeout: 300s
remote host idle timeout: 60s
flow idle timeout: 180s

the server does seem to be under load when it crashes but for two cores i wasn't too concerned (sample below):
```
top - 12:39:25 up 20 days, 23:45,  1 user,  load average: 0.69, 0.59, 0.59
Tasks: 153 total,   3 running, 150 sleeping,   0 stopped,   0 zombie
%Cpu(s): 48.2 us,  9.1 sy,  0.0 ni, 38.9 id,  0.0 wa,  0.0 hi,  3.8 si,  0.0 st
KiB Mem:   4047452 total,  3717972 used,   329480 free,   196572 buffers
KiB Swap:  1048572 total,    91444 used,   957128 free.  1374056 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                   
18366 nobody    20   0 2767244 1.453g  12608 S  98.4 37.6 273:04.52 ntopng                                                                                                                                    
  973 redis     20   0  290952 195684   2372 S  23.3  4.8 734:00.95 redis-server                                                                                                                              
 1096 mysql     20   0  877984 165708   4708 S   0.3  4.1  73:46.52 mysqld     
```

**Comment by seismiccollision** [comment]
@lmangani I still seem to get crashes at around 115,000 hosts tracked with the newest settings. I will try adding more memory to the server but it would be nice to have some guidance (maybe it's sflow specific sizing i need)

**Comment by seismiccollision** [comment]
I'm still having this problem, is there anything I can provide to help? I've increased my memory to 5Gb and I still see the symptoms

**Comment by simonemainardi** [comment]
@seismiccollision we are designing a virtual interface that simulates high-load environments. This may help in implementing more efficient host and flow management tools.

In the meanwhile, I really think you should at least double the ram to 8Gb.

**Comment by seismiccollision** [comment]
@simonemainardi thanks! i have set the ram to 8GB and set the CPUs to 4 from 2 and i will report back in a few days whether the issue occurs or not

**Comment by seismiccollision** [comment]
@simonemainardi I'm still having issues at the new specs. got up to ~106k tracked hosts and ~900 flows and then when I try using the web interface things stop working after a few page navigations and ntopng sometimes crashes but sometimes just hangs requiring a restart to fix and this usually happens within 24 hours of starting the application

```
23/Dec/2015 09:32:29 [Lua.cpp:4750] WARNING: Script failure [/usr/share/ntopng/scripts/lua/top_generic.lua][not enough memory]
23/Dec/2015 09:32:29 [Lua.cpp:4750] WARNING: Script failure [/usr/share/ntopng/scripts/lua/top_generic.lua][not enough memory]
23/Dec/2015 09:32:33 [Lua.cpp:4750] WARNING: Script failure [/usr/share/ntopng/scripts/lua/top_generic.lua][not enough memory]
23/Dec/2015 09:32:51 [Lua.cpp:4750] WARNING: Script failure [/usr/share/ntopng/scripts/lua/top_generic.lua][not enough memory]
23/Dec/2015 09:32:53 [Lua.cpp:4750] WARNING: Script failure [/usr/share/ntopng/scripts/lua/top_generic.lua][not enough memory]
23/Dec/2015 09:33:00 [Lua.cpp:4750] WARNING: Script failure [/usr/share/ntopng/scripts/lua/top_generic.lua][not enough memory]
```

**Comment by simonemainardi** [comment]
@seismiccollision, @lucaderi's commit 440a2c83 introduces very interesting changes that significantly improve sorting algorithms and memory management. Now it is a lot more efficient to retrieve sorted hosts/flows. Please, try and test the latest dev version.

**Comment by seismiccollision** [comment]
@simonemainardi @lucaderi Thank you! I have updated to 2.3.151228 and will let you know how it goes

**Comment by lucaderi** [comment]
@seismiccollision Please refresh just now where I have made a few fixes. In case you crash ntopng please send us both ntopng (the binary) and the core. Thanks

**Comment by seismiccollision** [comment]
@lucaderi @simonemainardi 
Thanks guys! I just upgraded to the latest commit but before I did I saw that ntopng was still functional at ~1000 tracked flows as ~115K hosts
The "Hosts > Hosts" and "Hosts > Networks" load time was significantly improved

I did notice when clicking on a network (/22) that loading the list of hosts (65 hosts tracked in that network) the loading seemed sluggish

I will let it run and report back

On a tangent but since you guys have been so helpful, I had the following two questions:
Is there any way to "name" networks? It would be very cool if I could include my local subnet names or even name specific remote networks to add meaning for less technical users
Also, using sflow the MAC addresses don't seem to get populated. Am I doing something wrong?

**Comment by seismiccollision** [comment]
@lucaderi @simonemainardi 
so far so good today in respect to performance and crashing
I noticed however that when I try loading pages such as:
...:3001/lua/host_details.lua?ifname=2&host=1.1.1.1&page=packets#

the page doesn't seem to fully load and ntopng.log starts slowly filling with the following:
29/Dec/2015 16:48:43 [Utils.cpp:695] WARNING: Found possible XSS attempt: type [type]
29/Dec/2015 16:48:43 [Utils.cpp:695] WARNING: Found possible XSS attempt: type [type]

**Comment by simonemainardi** [comment]
@seismiccollision thanks for reporting. The original issue is solved and is safe to close this.

Please make separate posts for any other possible issue.

Just to briefly answer your questions:
- it is not possibly to 'name' networks.
- MAC addresses are populated if the corresponding field is present
- we've made some changes to the cross site scripting detection that may be the cause of the warning shown

**Comment by simonemainardi** [comment]
btw, I've just fixed the cause of your XSS warnings above.

**Comment by seismiccollision** [comment]
@simonemainardi thanks for your help! i'll open new tickets for anything new
i upgraded to v.2.3.151230 but still see the XSS warning

**Comment by lucaderi** [comment]
@seismiccollision Now the XSS is fixed. Please retry
