### ISSUE TITLE
Hash table idle entries purging on interface xxx is too slow. 

### ISSUE THREAD

**Issue by PawelConnectio** [ntop/ntopng#3204]
| Hash table idle entries purging on interface all is too slow. This could lead to high memory utilization, data accuracy loss and missing alerts. [> 0%]
-- | --

` ntopng --version
v.3.9.200109    [Enterprise/Professional build]
GIT rev:        dev:3827baeab3860bf4be73a970c97fb1f2a1453eb4:20200109
Pro rev:        r2648
Built on:       Debian GNU/Linux 9.1 (stretch)
System Id:      6894571582072B23
Platform:       x86_64
Edition:        Enterprise
`
Edit: 
its related to :
![Bez tytułu](https://user-images.githubusercontent.com/59692777/72077338-5bff7280-32f7-11ea-99a0-641181ef24c0.jpg)

**Comment by emanuele-f** [comment]
Closing this to avoid splitting information across multiple sources as we are currently discussing this via email. Will reopen if necessary.

**Comment by tusc** [comment]
ntopng --version
v.4.1.200705    [Community build]
GIT rev:        dev:d1eca8dbafc00a8a87ef6009560104509eacff84:20200705

Was this ever addressed? This still appears in the latest version.

Hash table idle entries purging on host udm.*****.local is too slow. This could lead to high memory utilization, data accuracy loss and missing alerts.

**Comment by simonemainardi** [comment]
Alert mentioned is suspicious: it is about hash table idle entries for an host. This is not possible, hash table entries are only a per-interface concept. I have pushed a fix. Wait for new builds to be generated and update.

In general, hash table idle entries alerts occur when there are too many hosts/flows in the system, so they cannot be handled timely by ntopng. In this case you can try (a combination of):

- Increase -x and -X
- Balance the traffic across multiple interfaces to better leverage multi-core architectures
- Use more powerful CPUs

**Comment by bpersonick** [comment]
I'm using nTop and still see this issue I just downloaded the latest binary 10 days ago and it still an issue
