### ISSUE TITLE
WARNING: Script failure

### ISSUE THREAD

**Issue by jasonamorrow** [ntop/ntopng#3332]
I'm currently getting the following lua scipt failure messages in the log trace. This started occurring after I tried to disable alerts in preferences.

Below are the error messages from the trace log:
27/Jan/2020 10:40:11 [LuaEngine.cpp:12484] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:247: attempt to index a nil value (field 'status_normal')]
27/Jan/2020 10:40:02 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:40:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:40:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:40:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:39:35 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:39:30 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:39:30 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 10:39:30 [NetworkInterface.cpp:2355] Started packet polling on interface eth0 [id: 3]...
27/Jan/2020 10:39:30 [PeriodicActivities.cpp:149] Each periodic activity script will use 1 threads
27/Jan/2020 10:39:30 [LuaEngine.cpp:11979] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][/usr/share/ntopng/scripts/lua/modules/flow_consts.lua:100: bad argument #3 to 'format' (number expected, got nil)]
27/Jan/2020 10:39:30 [PeriodicActivities.cpp:101] Started periodic activities loop...

I'm running version v.3.9.200125 on Raspbian Buster.

**Comment by simonemainardi** [comment]
please, try and update to the latest version and report. if planning to use only community add `--community`

**Comment by jasonamorrow** [comment]
I'm on the latest version for Raspbian and I'm using --community.

**Comment by simonemainardi** [comment]
Latest is 200127

**Comment by jasonamorrow** [comment]
After upgrading I continue to get the following in the trace log: 

27/Jan/2020 13:21:25 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:21:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:21:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:21:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:21:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:02 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:02 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:20:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:19:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:19:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:19:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:19:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:18:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:18:01 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:18:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]
27/Jan/2020 13:18:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [cannot open /var/ntopng/plugins/plugins_metadata.lua: No such file or directory]

**Comment by jasonamorrow** [comment]
The Flows page gives the following error: SyntaxError: Unexpected token H in JSON at position 0

There are additional errors in the trace log. Below is a sample:

28/Jan/2020 09:07:13 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:37: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk28/Jan/2020 09:07:13 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744073182e+1928/Jan/2020 09:07:13 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk28/Jan/2020 09:07:13 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744073182e+1928/Jan/2020 09:07:12 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:37: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk28/Jan/2020 09:07:12 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744073181e+1928/Jan/2020 09:07:12 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk28/Jan/2020 09:07:12 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744073182e+19
--

**Comment by emanuele-f** [comment]
Please run on the raspberry `ntopng --version`

**Comment by jasonamorrow** [comment]
jason@monitor:~ $ ntopng --version
v.3.9.200127    [Enterprise/Professional/Embedded build]
GIT rev:        dev:35a3c9ab0793721721b22d9a7b1d549c301fbe90:20200127
Pro rev:        r2685
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      440C3FC9499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Tue Jan 28 09:24:18 2020

**Comment by emanuele-f** [comment]
How are you starting ntopng? What are the contents of /etc/ntopng/ntopng.conf?

**Comment by jasonamorrow** [comment]
jason@monitor:~ $ cat /etc/ntopng/ntopng.conf
```
#         The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
#       -G|--pid-path
#        Specifies the path where the PID (process ID) is saved. This option is ignored when
#        ntopng is controlled with systemd (e.g., service ntopng start).
#
-G=/var/run/ntopng.pid
#
#       -e|--daemon
#        This  parameter  causes ntop to become a daemon, i.e. a task which runs in the background
#        without connection to a specific terminal. To use ntop other than as a casual  monitoring
#        tool, you probably will want to use this option. This option is ignored when ntopng is
#        controlled with systemd (e.g., service ntopng start)
#
-e=
#
#       -i|--interface
#        Specifies  the  network  interface or collector endpoint to be used by ntopng for network
#        monitoring. On Unix you can specify both the interface name  (e.g.  lo)  or  the  numeric
#        interface id as shown by ntopng -h. On Windows you must use the interface number instead.
#        Note that you can specify -i multiple times in order to instruct ntopng to create  multi-
#        ple interfaces.
#
-i=eth0
# -i=eth2
#
#       -w|--http-port
#        Sets the HTTP port of the embedded web server.
#
-w=0
-W=3001
#
#       -m|--local-networks
#        ntopng determines the ip addresses and netmasks for each active interface. Any traffic on
#        those  networks  is considered local. This parameter allows the user to define additional
#        networks and subnetworks whose traffic is also considered local in  ntopng  reports.  All
#        other hosts are considered remote. If not specified the default is set to 192.168.1.0/24.
#
#        Commas  separate  multiple  network  values.  Both netmask and CIDR notation may be used,
#        even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0".
#
-m=192.168.0.0/24,192.168.1.0/24,192.168.2.0/24
# -m=10.10.124.0/24
#
#       -n|--dns-mode
#        Sets the DNS address resolution mode: 0 - Decode DNS responses  and  resolve  only  local
#        (-m)  numeric  IPs  1  -  Decode DNS responses and resolve all numeric IPs 2 - Decode DNS
#        responses and don't resolve numeric IPs 3 - Don't decode DNS responses and don't  resolve
#
-n=1
#
#       -S|--sticky-hosts
#        ntopng  periodically purges idle hosts. With this option you can modify this behaviour by
#        telling ntopng not to purge the hosts specified by -S. This parameter requires  an  argu-
#        ment  that  can  be  "all"  (Keep  all hosts in memory), "local" (Keep only local hosts),
#        "remote" (Keep only remote hosts), "none" (Flush hosts when idle).
#
-S=local
#
#       -d|--data-dir
#        Specifies the data directory (it must be writable by the user that is executing ntopng).
#
-d=/var/ntopng
#
#       -q|--disable-autologout
#        Disable web interface logout for inactivity.
-q=
--community
```

**Comment by popmonkey** [comment]
i'm seeing the same problems (ERROR: Number out of integers range) and flows are no longer getting cleaned up

```sh
ntopng --version
v.3.9.200205	[Enterprise/Professional/Embedded build]
GIT rev:	dev:5f2d9a1dd2c463dfdae4566f671e55acf714e651:20200205
Pro rev:	r2697
Built on:	Raspbian GNU/Linux 10 (buster)
System Id:	FD9B86E0499602D2
Platform:	armv7l
Edition:	Enterprise Embedded
License Type:	Time-Limited [Empty license file]
Validity:	Until Wed Feb 12 11:59:52 2020
```

my config:
```
--interface eth0
--http-port 3000
--local-networks "XXX"
--community
--ignore-vlans
```

**Comment by popmonkey** [comment]
restarting `ntopng` (and `redis-server`) is a workaround for `ERROR: Number out of integers range`

**Comment by emanuele-f** [comment]
For some reason, the interface bytes counter on your system is exceeding the maximum 64 bit integer of lua. Can you post a screenshot of the eth0 Interface page?

**Comment by emanuele-f** [comment]
Can you check out the new raspbian package? The flows purge problem should be solved, I cannot reproduce the traffic counter integer problem.

**Comment by jasonamorrow** [comment]
I've installed 3.9.200209 (8920) and will look out for errors. No issues so far.

**Comment by jasonamorrow** [comment]
Still getting errors after the latest update. Below is an example from the trace log:

14/Feb/2020 07:19:39 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
14/Feb/2020 07:19:39 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.844674407371e+19
14/Feb/2020 07:19:38 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
14/Feb/2020 07:19:38 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.844674407371e+19
14/Feb/2020 07:19:37 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback: /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319> (...tail calls...) .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append' /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface' /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk

**Comment by jasonamorrow** [comment]
Screenshot of interface config:

![image](https://user-images.githubusercontent.com/14959305/74551749-c1abd380-4f21-11ea-9497-87d4709d0b76.png)

**Comment by emanuele-f** [comment]
@jasonamorrow for the "Number out of integers range" error and fix please see #3398 . Please check out the new package when available to see if the AlertCheckLuaEngine is solved.

**Comment by simonemainardi** [comment]
any news here?

**Comment by jasonamorrow** [comment]
I upgraded to version 3.9.200225 today and will watch for any errors.

**Comment by jasonamorrow** [comment]
No more errors. Going to go ahead and close this out.

**Comment by ajaufura** [comment]
I am having the same issue here. Any idea how to resolve this? Thanks.

Error :
27/Feb/2021 20:09:06 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]

27/Feb/2021 20:09:07 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]

Ntopng Version :
Version:        4.3.210226 [Enterprise/Professional/Embedded build]
GIT rev:        dev:9b6c9b7c602aaac0d10f33a49e01cdf4262d66eb:20210226
Pro rev:        r3610
Built on:       Raspbian GNU/Linux 10 (buster)
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Sat Feb 27 20:16:35 2021

**Comment by bageheyalu** [comment]
I also encountered this problem. Did you solve this problem？

**Comment by simonemainardi** [comment]
yes. Please update.

**Comment by ajaufura** [comment]
I'm still having the issue. I use the dockerfile here : https://github.com/ntop/docker-ntop
I created the dockerfile "Dockerfile.ntopng-raspberry" on my raspberrypi, then i run the following : 

docker build -t ntopng -f Dockerfile.ntopng-raspberry .
docker run -it --net=host ntopng -i eth0

And I have those erreors : 

,01/Mar/2021 19:05:00 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/5min.lua][.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]
,01/Mar/2021 19:05:05 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]
,01/Mar/2021 19:05:06 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]
,01/Mar/2021 19:05:06 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]

**Comment by ajaufura** [comment]
And on typing the IP and the port number on a browser, I have the page to log as admin/admin then to change password. But I cannot go further to access the webUI of ntopng. Have you an idea of the issue?

**Comment by simonemainardi** [comment]
what do you mean? please explain and attach screenshots

**Comment by ajaufura** [comment]
I explained it in the comment upwards. I deploy it again using the file "Dockerfile.ntopng-raspberry". Still having same issue
