### ISSUE TITLE
Pro report toggles not working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3449]
Clicking on the toggles shown has strange effects. Sometimes nothing happens, some other times a toggle different from the one clicked changes.

![image](https://user-images.githubusercontent.com/3397663/75177156-e8de7e00-5735-11ea-9e2f-68a491266f2a.png)

**Comment by gabryon99** [comment]
The problem was caused by wrong ids for checkboxes.

**Comment by gabryon99** [comment]
Fixed in the last commit.

**Comment by simonemainardi** [comment]
Not fixed. Toggles now work but clicking "Submit filter" does not actually change any value. Values come back to their previously set values.

Please, also fix the layout: as you can see there's an 'Applications' written on top which makes no sense as applications are at the bottom

![image](https://user-images.githubusercontent.com/3397663/75551505-a322fd80-5a34-11ea-9208-bab6f88c453a.png)

**Comment by gabryon99** [comment]
I fixed the problem. The bug was caused by a double class inside the toggles, the javascript function who takes the parameters didn't find the elements to serialize and save.
