### ISSUE TITLE
Manage Data - Delete Host Data Not Working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3537]
Entering the IP address of an host doesn't enable the 'Delete Host Data Button'.

![image](https://user-images.githubusercontent.com/3397663/76319319-55817d00-62df-11ea-82d2-166b06b4999b.png)

VLAN must be optional, assumed zero if not specified.

**Comment by gabryon99** [comment]
Fixed, now VLAN is an optional. See this commit: https://github.com/ntop/ntopng/commit/4c692e2c6e4250984992a2fd63153f459e673933

**Comment by simonemainardi** [comment]
still not working for hosts with vlan

![image](https://user-images.githubusercontent.com/3397663/76508867-5c2f0200-644f-11ea-8b04-e680308e671c.png)

clicking on delete host data has no effect

![image](https://user-images.githubusercontent.com/3397663/76508904-6c46e180-644f-11ea-8c8b-6d8ed344d467.png)

**Comment by simonemainardi** [comment]
you can add `--simulate-vlans` to simulate hosts with vlans

**Comment by gabryon99** [comment]
<img width="1688" alt="Screenshot 2020-03-12 at 16 41 08" src="https://user-images.githubusercontent.com/14114916/76538873-48e85a80-6480-11ea-9b01-4940745ae8b3.png">

Thank you for the option, that helped me. Ok, I figured out the problem, it was a conditional branch that return too soon. As you can see, now it works. See: https://github.com/ntop/ntopng/commit/b0a3610f057329ede2a7aa885dffe0dd5b19694c
