### ISSUE TITLE
Unsupported protocol error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3551]
![Screen Shot 2020-03-12 at 16 56 58](https://user-images.githubusercontent.com/4493366/76540585-9c5ba800-6482-11ea-8ee3-e5a8ba09ec9a.png)

**Comment by lucaderi** [comment]
Fixed in latest Win build

**Comment by simonemainardi** [comment]
still getting it

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/3397663/77056514-cb1dd500-69d2-11ea-9714-fb217dd7ac56.png">

**Comment by simonemainardi** [comment]
Fixed in https://github.com/ntop/ntopng/commit/49c80c46152d4d32292170d893eea2e78dcee514
