### ISSUE TITLE
No details in Flow - Internal server error

### ISSUE THREAD

**Issue by lzalewsk** [ntop/ntopng#424]
ntopng version: 2.3.160226
In case of nprobe -> ntopng setup
nprobe.conf:

```
-n=none
-i=eth1,eth5
-b=1
-s=128
-t=60
-d=30
-a=0
-e=1
-S=1:1
-g=/var/run/nprobe-eth1eth5.pid
--dont-nest-dump-dirs
--elastic=flows;nprobe-%Y.%m.%d;http://localhost:9200/_bulk;
--dump-stats=/var/log/nprobe/eth1eth5-0_flows_stats.txt
--timestamp-format=2
-T=%IPV4_SRC_ADDR %IPV4_DST_ADDR %IN_PKTS %OUT_PKTS %L4_DST_PORT %L4_SRC_PORT %IN_BYTES %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %PROTOCOL %IN_SRC_MAC %OUT_DST_MAC %TCP_FLAGS %APPL_LATENCY_MS %SRC_IP_COUNTRY %DST_IP_COUNTRY %L7_PROTO %L7_PROTO_NAME %ICMP_TYPE %IP_PROTOCOL_VERSION %NUM_PKTS_UP_TO_128_BYTES %NUM_PKTS_128_TO_256_BYTES %NUM_PKTS_256_TO_512_BYTES %NUM_PKTS_512_TO_1024_BYTES %NUM_PKTS_1024_TO_1514_BYTES %NUM_PKTS_OVER_1514_BYTES %DNS_QUERY %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS %DNS_TTL_ANSWER %DNS_RESPONSE %HTTP_URL %HTTP_METHOD %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME %HTTP_HOST %HTTP_SITE %DOT1Q_SRC_VLAN %DOT1Q_DST_VLAN %SRC_IP_CITY %DST_IP_CITY
--json-labels=
-A=/usr/local/nprobe/GeoIPASNum.dat
--city-list=/usr/local/nprobe/GeoLiteCity.dat
--zmq=tcp://*:5556

```

ntopng -i tcp://localhost:5556

In ntopng GUI after going into FLOW details I receive
`/usr/share/ntopng/scripts/lua/modules/flow_utils.lua:1047: attempt to perform arithmetic on global 'time_epoch' (a string value)`

![ntopng](https://cloud.githubusercontent.com/assets/14045566/13371162/8d982116-dd1f-11e5-91eb-8389e90aa23e.png)

**Comment by rathnaTech** [comment]
yes, I am also facing the same problem.I extracted GTP packets through ntopng .When i opened the flow there is no information found(eg. IMSI,IP,SERVICR NUMBER ETC.,). Please provide sufficient information as soon as possible.
Thank You,

**Comment by rathnaTech** [comment]
![screenshot from 2016-03-01 12 48 39](https://cloud.githubusercontent.com/assets/16934803/13427831/81f5bb24-dfdc-11e5-8ccd-bff037a0b26d.png)

while feeding capture file to the nprobe  it was not executed

**Comment by lucaderi** [comment]
The warning issue should have been fixed

**Comment by lzalewsk** [comment]
Hi,
I still have a problem
After upgrade ntopng x86_64 v.2.3.160301

![ntopng_crash](https://cloud.githubusercontent.com/assets/14045566/13442649/8ea66a14-dffd-11e5-8561-8d7ce11fc7eb.png)

Additionaly after few click's / navigations it's crash.

```
01/Mar/2016 22:30:38 [main.cpp:295] Working directory: /var/tmp/ntopng
01/Mar/2016 22:30:38 [main.cpp:297] Scripts/HTML pages directory: /usr/share/ntopng
01/Mar/2016 22:30:38 [Ntop.cpp:258] Welcome to ntopng x86_64 v.2.3.160301 - (C) 1998-16 ntop.org
01/Mar/2016 22:30:38 [Ntop.cpp:263] Built on Debian GNU/Linux 8.2 (jessie)
01/Mar/2016 22:30:38 [PeriodicActivities.cpp:53] Started periodic activities loop...
01/Mar/2016 22:30:38 [RuntimePrefs.cpp:34] Dumping alerts into syslog
01/Mar/2016 22:30:38 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 3C0E6232B206AB23
01/Mar/2016 22:30:38 [NtopPro.cpp:238] [LICENSE] ntopng is starting in demo mode
01/Mar/2016 22:30:38 [Ntop.cpp:514] Adding 127.0.0.0/8 as IPv4 local network for tcp://localhost:5556
01/Mar/2016 22:30:38 [Ntop.cpp:544] Adding ::1/128 as IPv6 local network for tcp://localhost:5556
01/Mar/2016 22:30:38 [NetworkInterface.cpp:1431] Started packet polling on interface tcp://localhost:5556 [id: 17]...
01/Mar/2016 22:30:39 [CollectorInterface.cpp:104] Collecting flows on tcp://localhost:5556 [ntopng->nprobe]
01/Mar/2016 22:30:56 [Lua.cpp:4815] WARNING: Script failure [/usr/share/ntopng/scripts/lua/flow_details.lua][error loading module 'flow_utils' from file '/usr/share/ntopng/scripts/lua/modules/flow_utils.lua':
        /usr/share/ntopng/scripts/lua/modules/flow_utils.lua:1072: ')' expected near '_1']

```

**Comment by lucaderi** [comment]
@rathnaTech Please open a different issue where you explain how you have started nProbe and ntopng. Note that you need to enable the GTP plugin for handling GTP traffic

**Comment by lucaderi** [comment]
I have fixed the warning/error. A new build is in progress

**Comment by simonemainardi** [comment]
@lzalewsk I confirm the issue

```
01/Mar/2016 22:30:56 [Lua.cpp:4815] WARNING: Script failure [/usr/share/ntopng/scripts/lua/flow_details.lua][error loading module 'flow_utils' from file '/usr/share/ntopng/scripts/lua/modules/flow_utils.lua':
        /usr/share/ntopng/scripts/lua/modules/flow_utils.lua:1072: ')' expected near '_1']
```

has been fixed 14 day ago in f97ee78d4 .
