### ISSUE TITLE
nearly all hosts generate low goodput alerts

### ISSUE THREAD

**Issue by arifyn** [ntop/ntopng#449]
Since low goodput warnings were added to the nightly build, my installation of ntopng has been throwing low goodput alerts for every host that connects to the network. I have a hard time believing that nearly all of our TCP and ICMP flows are low goodput.

I assume this is not the intended behavior and that this is not affecting all installations of ntopng, but I am not sure what is unique about our setup. The only thing that comes to mind is that we're using ntopng to monitor a mirrored port from our main router (connected to a spare ethernet port on our debian machine). Let me know if there is any further information I can provide to help nail down this issue.

Alternately, a way to simply disable the low goodput warnings entirely (short of recompiling ntopng) would be appreciated.

**Comment by whoknowz** [comment]
Second that. Woke up to 180K alerts, anyway to disable this?

**Comment by mjgehrmann** [comment]
Any chance goodput may false alert for sampled flow data? I see the same issue. 

Mike

**Comment by lucaderi** [comment]
This has been fixed already. What version are you using?

**Comment by arifyn** [comment]
oops - for some reason the running version was still v.2.3.160311. I restarted and purged existing alerts and am having no further issues with 316.

**Comment by whoknowz** [comment]
Doesn't fix for me. See attached screenshot.
![capture](https://cloud.githubusercontent.com/assets/7417874/13898315/255de03c-edef-11e5-81ea-5bd7dedeea9b.JPG)

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/4bd964859ffca356a7d5400f17de15f378540858
