### ISSUE TITLE
No external alerts from suricata

### ISSUE THREAD

**Issue by AmCrNi** [ntop/ntopng#4895]
After update to following version:
```
v.4.3.201227    [Enterprise/Professional/Embedded build]
GIT rev:        dev:7c1926fde007a704004bde3b4f5297f9d8c93574:20201227
Pro rev:        r3435
Built on:       Raspbian GNU/Linux 10 (buster)
```
external alerts are not visible and following error appears in the log:
```
09/Jan/2021 11:26:00 [AlertCheckLuaEngine.cpp:168] WARNING Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...ugins0/callbacks/interface/flow/external_alert_check.lua:39: attempt to index a nil value (field 'alert_external')]
09/Jan/2021 11:26:00 [AlertCheckLuaEngine.cpp:168] WARNING Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...ugins0/callbacks/interface/flow/external_alert_check.lua:39: attempt to index a nil value (field 'alert_external')]
09/Jan/2021 11:26:00 [AlertCheckLuaEngine.cpp:168] WARNING Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...ugins0/callbacks/interface/flow/external_alert_check.lua:39: attempt to index a nil value (field 'alert_external')]
```

**Comment by simonemainardi** [comment]
Issue is fixed. New rpi builds are in progress and will be ready in the next couple of hours

**Comment by AmCrNi** [comment]
@simonemainardi Thanks for an update. I've checked with new version and the problem still persist but now ntopng is being restarted:

```
Jan 11 20:16:11 malina2 ntopng[17039]: 11/Jan/2021 20:16:11 [LuaEngine.cpp:571] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:1994: bad argument #2 to 'format' (number expected, got nil)]
Jan 11 20:16:12 malina2 ntopng[17039]: [LuaEngine.cpp:571] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:1994: bad argument #2 to 'format' (number expected, got nil)]
Jan 11 20:16:12 malina2 ntopng[17039]: 11/Jan/2021 20:16:12 [LuaEngine.cpp:571] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:1994: bad argument #2 to 'format' (number expected, got nil)]
Jan 11 20:16:20 malina2 systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd

ntopng --version
v.4.3.210111    [Enterprise/Professional/Embedded build]
GIT rev:        dev:eb140e33a44bde8124f7b91b24583b3d59234035:20210111
Pro rev:        r3468
Built on:       Raspbian GNU/Linux 10 (buster)
```

**Comment by simonemainardi** [comment]
That was another error already fixed. New builds with the fix are being built. Please, re-update after a couple of hours.

**Comment by AmCrNi** [comment]
@simonemainardi After update it now reporting following in the UI:
```
Started after anomalous termination (bug report) ntopng v.4.3.210111 (12741) [OS: Raspbian GNU/Linux 10 (buster)][pid: 22228][options: --interface 'eth10' --interface 'syslog://127.0.0.1:9999' --dump-flows '[hidden]' --http-port '3000' --local-networks '10.168.0.0/24' --max-num-hosts '512000' --max-num-flows '512000' ]
 ```

And ntopng is restarting every couple of minutes with following log entries:
```
Jan 12 20:16:08 malina2 ntopng[23487]: 12/Jan/2021 20:16:08 [Ntop.cpp:2321] Setting local networks to 10.168.0.0/24
Jan 12 20:16:08 malina2 ntopng[23487]: 12/Jan/2021 20:16:08 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:Jan 12 20:16:08 malina2 ntopng[23487]: 12/Jan/2021 20:16:08 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:Jan 12 20:16:08 malina2 ntopng[23487]: 12/Jan/2021 20:16:08 [NtopPro.cpp:311] [LICENSE] Reading license from /etc/ntopJan 12 20:16:08 malina2 ntopng[23487]: 12/Jan/2021 20:16:08 [NtopPro.cpp:440] [LICENSE] /etc/ntopng.license: found valJan 12 20:16:48 malina2 systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit ntopng.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 11.
Jan 12 20:16:48 malina2 systemd[1]: ntopng.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
```

ntopng version:
```
root@malina2:~# ntopng --version
v.4.3.210111    [Enterprise/Professional/Embedded build]
GIT rev:        dev:ec6d7b5c6dac2987ebfa9024a69e07d19e1b4259:20210111
Pro rev:        r3472
Built on:       Raspbian GNU/Linux 10 (buster)
```

**Comment by simonemainardi** [comment]
run it as

```
gdb --args ntopng --interface 'eth10' --interface 'syslog://127.0.0.1:9999' --dump-flows 'your data' --http-port '3000' --local-networks '10.168.0.0/24' --max-num-hosts '512000' --max-num-flows '512000' 
```

wait until it crashes, and report the stack trace

**Comment by AmCrNi** [comment]
thanks for an update @simonemainardi, here is the backtrace:

```
root@malina2:~# gdb --args ntopng --interface 'eth10' --interface 'syslog://127.0.0.1:9999' --dump-flows 'your data' --http-port '3000' --local-networks '10.168.0.0/24' --max-num-hosts '512000' --max-num-flows '512000'                                                                                           GNU gdb (Raspbian 8.2.1-2) 8.2.1                                                                                                                                                                                                                                                                                     Copyright (C) 2018 Free Software Foundation, Inc.                                                                                                                                                                                                                                                                    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                                                                                                                                                                                                                        This is free software: you are free to change and redistribute it.                                                                                                                                                                                                                                                   There is NO WARRANTY, to the extent permitted by law.                                                                                                                                                                                                                                                                Type "show copying" and "show warranty" for details.                                                                                                                                                                                                                                                                 This GDB was configured as "arm-linux-gnueabihf".                                                                                                                                                                                                                                                                    Type "show configuration" for configuration details.                                                                                                                                                                                                                                                                 For bug reporting instructions, please see:                                                                                                                                                                                                                                                                          <http://www.gnu.org/software/gdb/bugs/>.                                                                                                                                                                                                                                                                             Find the GDB manual and other documentation resources online at:                                                                                                                                                                                                                                                         <http://www.gnu.org/software/gdb/documentation/>.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     For help, type "help".                                                                                                                                                                                                                                                                                               Type "apropos word" to search for commands related to "word"...                                                                                                                                                                                                                                                      Reading symbols from ntopng...(no debugging symbols found)...done.                                                                                                                                                                                                                                                   (gdb) handle SIG33 nostop noprint pass                                                                                                                                                                                                                                                                               Signal        Stop      Print   Pass to program Description                                                                                                                                                                                                                                                          SIG33         No        No      Yes             Real-time event 33                                                                                                                                                                                                                                                   (gdb) handle SIGPIPE nostop noprint pass                                                                                                                                                                                                                                                                             Signal        Stop      Print   Pass to program Description                                                                                                                                                                                                                                                          SIGPIPE       No        No      Yes             Broken pipe                                                                                                                                                                                                                                                          (gdb) run                                                                                                                                                                                                                                                                                                            Starting program: /usr/local/bin/ntopng --interface eth10 --interface syslog://127.0.0.1:9999 --dump-flows your\ data --http-port 3000 --local-networks 10.168.0.0/24 --max-num-hosts 512000 --max-num-flows 512000                                                                                                  [Thread debugging using libthread_db enabled]                                                                                                                                                                                                                                                                        Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".                                                                                                                                                                                                                                        [New Thread 0xf40b8ca0 (LWP 28152)]                                                                                                                                                                                                                                                                                  [New Thread 0xf38b7ca0 (LWP 28153)]                                                                                                                                                                                                                                                                                  
13/Jan/2021 14:20:27 [Ntop.cpp:2321] Setting local networks to 10.168.0.0/24
13/Jan/2021 14:20:27 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
13/Jan/2021 14:20:27 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
13/Jan/2021 14:20:27 [NtopPro.cpp:311] [LICENSE] Reading license from /etc/ntopng.license
13/Jan/2021 14:20:27 [NtopPro.cpp:440] [LICENSE] /etc/ntopng.license: found valid Professional Embedded license
[Detaching after fork from child process 28165]
[New Thread 0xf2969ca0 (LWP 28170)]
[Thread 0xf2969ca0 (LWP 28170) exited]
[New Thread 0xf1cfcca0 (LWP 28186)]
[New Thread 0xf14fbca0 (LWP 28187)]
[New Thread 0xf0afeca0 (LWP 28188)]
[New Thread 0xf02fdca0 (LWP 28189)]
[New Thread 0xef8fcca0 (LWP 28190)]
[New Thread 0xeeefeca0 (LWP 28191)]
[New Thread 0xee4feca0 (LWP 28192)]
[New Thread 0xedcfdca0 (LWP 28193)]
[New Thread 0xed4fcca0 (LWP 28194)]
[Detaching after fork from child process 28195]
[Detaching after fork from child process 28198]
[Detaching after fork from child process 28200]
[New Thread 0xeccfbca0 (LWP 28210)]
[New Thread 0xec4faca0 (LWP 28211)]
[New Thread 0xebcf9ca0 (LWP 28212)]
[New Thread 0xeb4f8ca0 (LWP 28213)]
[New Thread 0xeacf7ca0 (LWP 28214)]
[New Thread 0xea4f6ca0 (LWP 28215)]
[New Thread 0xe9cf5ca0 (LWP 28216)]
[New Thread 0xe94f4ca0 (LWP 28217)]
[New Thread 0xe8cf3ca0 (LWP 28218)]
[New Thread 0xe84f2ca0 (LWP 28219)]
[New Thread 0xe7cf1ca0 (LWP 28220)]
[New Thread 0xe74f0ca0 (LWP 28221)]
[New Thread 0xe6cefca0 (LWP 28222)]
[New Thread 0xe64eeca0 (LWP 28223)]
[New Thread 0xe5cedca0 (LWP 28224)]
[New Thread 0xe54ecca0 (LWP 28225)]
[New Thread 0xe4cebca0 (LWP 28226)]
[New Thread 0xe44eaca0 (LWP 28227)]
[New Thread 0xe3ce9ca0 (LWP 28228)]
[New Thread 0xe34e8ca0 (LWP 28229)]
[New Thread 0xe2ce7ca0 (LWP 28230)]
[New Thread 0xe24e6ca0 (LWP 28231)]
[New Thread 0xe1ce5ca0 (LWP 28232)]
[New Thread 0xe14e4ca0 (LWP 28233)]
[New Thread 0xe0ce3ca0 (LWP 28234)]
[New Thread 0xe04e2ca0 (LWP 28235)]
[New Thread 0xde9feca0 (LWP 28236)]

Thread 38 "inline ifid 3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xe0ce3ca0 (LWP 28234)]
0x00031520 in ?? ()
(gdb) bt
#0  0x00031520 in ?? ()
#1  0x0008bffc in ?? ()
#2  0x0008bffc in ?? ()
#3  0x0008bd9c in ?? ()
#4  0x000e9e10 in ?? ()
#5  0x000e8ae8 in ?? ()
#6  0x000e8a54 in ?? ()
#7  0x000be65c in ?? ()
#8  0x000671fc in ?? ()
#9  0x000b8410 in ?? ()
#10 0x000bd258 in ?? ()
#11 0x000bb098 in ?? ()
#12 0x000bae58 in ?? ()
#13 0x0008b414 in ?? ()
#14 0xf7654494 in start_thread (arg=0xe0ce3ca0) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x1e
(gdb) 

```

**Comment by simonemainardi** [comment]
I have prepared a build with debug symbols. Download it from https://www.dropbox.com/s/oefvhk4qkmaeoxh/ntopng?dl=0

Re-run inside gdb, and send again the output of backtrace:

```
gdb --args <path to the downloaded file> --interface 'eth10' --interface 'syslog://127.0.0.1:9999' --dump-flows 'your data' --http-port '3000' --local-networks '10.168.0.0/24' --max-num-hosts '512000' --max-num-flows '512000'
```

**Comment by AmCrNi** [comment]
```
root@malina2:~# gdb --args ./ntopng-debug-info --interface 'eth10' --interface 'syslog://127.0.0.1:9999' --dump-flows 'your data' --http-port '3000' --local-networks '10.168.0.0/24' --max-num-hosts '512000' --max-num-flows '512000'                                                                                                                                                                                                                                        GNU gdb (Raspbian 8.2.1-2) 8.2.1                                                                                                                                                                                                                                                                                     Copyright (C) 2018 Free Software Foundation, Inc.                                                                                                                                                                                                                                                                    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                                                                                                                                                                                                                        This is free software: you are free to change and redistribute it.                                                                                                                                                                                                                                                   There is NO WARRANTY, to the extent permitted by law.                                                                                                                                                                                                                                                                Type "show copying" and "show warranty" for details.                                                                                                                                                                                                                                                                 This GDB was configured as "arm-linux-gnueabihf".                                                                                                                                                                                                                                                                    Type "show configuration" for configuration details.                                                                                                                                                                                                                                                                 For bug reporting instructions, please see:                                                                                                                                                                                                                                                                          <http://www.gnu.org/software/gdb/bugs/>.                                                                                                                                                                                                                                                                             Find the GDB manual and other documentation resources online at:                                                                                                                                                                                                                                                         <http://www.gnu.org/software/gdb/documentation/>.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     For help, type "help".                                                                                                                                                                                                                                                                                               Type "apropos word" to search for commands related to "word"...                                                                                                                                                                                                                                                      Reading symbols from ./ntopng-debug-info...done.                                                                                                                                                                                                                                                                     (gdb) handle SIG33 nostop noprint pass                                                                                                                                                                                                                                                                               Signal        Stop      Print   Pass to program Description                                                                                                                                                                                                                                                          SIG33         No        No      Yes             Real-time event 33                                                                                                                                                                                                                                                   (gdb) handle SIGPIPE nostop noprint pass                                                                                                                                                                                                                                                                             Signal        Stop      Print   Pass to program Description                                                                                                                                                                                                                                                          SIGPIPE       No        No      Yes             Broken pipe                                                                                                                                                                                                                                                          (gdb) run                                                                                                                                                                                                                                                                                                            Starting program: /root/ntopng-debug-info --interface eth10 --interface syslog://127.0.0.1:9999 --dump-flows your\ data --http-port 3000 --local-networks 10.168.0.0/24 --max-num-hosts 512000 --max-num-flows 512000                                                                                                [Thread debugging using libthread_db enabled]                                                                                                                                                                                                                                                                        Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".                                                                                                                                                                                                                                        [New Thread 0xf40b8ca0 (LWP 11378)]                                                                                                                                                                                                                                                                                  [New Thread 0xf38b7ca0 (LWP 11379)]                                                                                                                                                                                                                                                                                  14/Jan/2021 13:07:55 [Ntop.cpp:2323] Setting local networks to 10.168.0.0/24                                                                                                                                                                                                                                         14/Jan/2021 13:07:55 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0                                                                                                                                                                                                                                14/Jan/2021 13:07:55 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0                                                                                                                                                                                                                                14/Jan/2021 13:07:55 [NtopPro.cpp:311] [LICENSE] Reading license from /etc/ntopng.license                                                                                                                                                                                                                            14/Jan/2021 13:07:55 [NtopPro.cpp:440] [LICENSE] /etc/ntopng.license: found valid Professional Embedded license                                                                                                                                                                                                      [Detaching after fork from child process 11391]                                                                                                                                                                                                                                                                      [New Thread 0xf2969ca0 (LWP 11396)]                                                                                                                                                                                                                                                                                  [Thread 0xf2969ca0 (LWP 11396) exited]                                                                                                                                                                                                                                                                               [New Thread 0xf1cfcca0 (LWP 11413)]                                                                                                                                                                                                                                                                                  [New Thread 0xf14fbca0 (LWP 11414)]                                                                                                                                                                                                                                                                                  [New Thread 0xf0cfaca0 (LWP 11415)]                                                                                                                                                                                                                                                                                  [New Thread 0xf00feca0 (LWP 11416)]                                                                                                                                                                                                                                                                                  [New Thread 0xef8fdca0 (LWP 11417)]                                                                                                                                                                                                                                                                                  [New Thread 0xef0fcca0 (LWP 11418)]                                                                                                                                                                                                                                                                                  [New Thread 0xee6feca0 (LWP 11419)]                                                                                                                                                                                                                                                                                  [New Thread 0xedefdca0 (LWP 11420)]                                                                                                                                                                                                                                                                                  [New Thread 0xed6fcca0 (LWP 11421)]                                                                                                                                                                                                                                                                                  [Detaching after fork from child process 11423]                                                                                                                                                                                                                                                                      [Detaching after fork from child process 11431]                                                                                                                                                                                                                                                                      [Detaching after fork from child process 11433]                                                                                                                                                                                                                                                                      [New Thread 0xecd03ca0 (LWP 11547)]                                                                                                                                                                                                                                                                                  [Thread 0xecd03ca0 (LWP 11547) exited]
[New Thread 0xecd03ca0 (LWP 11550)]
[Thread 0xecd03ca0 (LWP 11550) exited]
[New Thread 0xecd03ca0 (LWP 11551)]
[Thread 0xecd03ca0 (LWP 11551) exited]
[New Thread 0xecd03ca0 (LWP 11553)]
[Thread 0xecd03ca0 (LWP 11553) exited]
[New Thread 0xecd03ca0 (LWP 11554)]
[Thread 0xecd03ca0 (LWP 11554) exited]
[New Thread 0xecd03ca0 (LWP 11555)]
[Thread 0xecd03ca0 (LWP 11555) exited]
[New Thread 0xecd03ca0 (LWP 11557)]
[Thread 0xecd03ca0 (LWP 11557) exited]
[New Thread 0xecd03ca0 (LWP 11558)]
[New Thread 0xec502ca0 (LWP 11559)]
[New Thread 0xebd01ca0 (LWP 11560)]
[New Thread 0xeb500ca0 (LWP 11561)]
[New Thread 0xeacffca0 (LWP 11562)]
[New Thread 0xea4feca0 (LWP 11563)]
[New Thread 0xe9cfdca0 (LWP 11564)]
[New Thread 0xe94fcca0 (LWP 11565)]
[New Thread 0xe8cfbca0 (LWP 11566)]
[New Thread 0xe84faca0 (LWP 11567)]
[New Thread 0xe7cf9ca0 (LWP 11568)]
[New Thread 0xe74f8ca0 (LWP 11569)]
[New Thread 0xe6cf7ca0 (LWP 11570)]
[New Thread 0xe64f6ca0 (LWP 11571)]
[New Thread 0xe5cf5ca0 (LWP 11572)]
[New Thread 0xe54f4ca0 (LWP 11573)]
[New Thread 0xe4cf3ca0 (LWP 11574)]
[New Thread 0xe44f2ca0 (LWP 11575)]
[New Thread 0xe3cf1ca0 (LWP 11576)]
[New Thread 0xe34f0ca0 (LWP 11577)]
[New Thread 0xe2cefca0 (LWP 11578)]
[New Thread 0xe24eeca0 (LWP 11579)]
[New Thread 0xe1cedca0 (LWP 11580)]
[New Thread 0xe14ecca0 (LWP 11581)]
[New Thread 0xe0cebca0 (LWP 11582)]
[New Thread 0xe04eaca0 (LWP 11583)]
[New Thread 0xde4feca0 (LWP 11586)]

Thread 45 "inline ifid 3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xe0cebca0 (LWP 11582)]
0x00163574 in Utils::formatMac (mac=0x40 <error: Cannot access memory at address 0x40>, buf=0xe0cea8b8 "", buf_len=128) at src/Utils.cpp:2468
2468    src/Utils.cpp: No such file or directory.
(gdb) bt
#0  0x00163574 in Utils::formatMac (mac=0x40 <error: Cannot access memory at address 0x40>, buf=0xe0cea8b8 "", buf_len=128) at src/Utils.cpp:2468
#1  0x0009d0a8 in Mac::print (this=0x0, str=0xe0cea8b8 "", str_len=128) at /home/deri/ntopng/include/Mac.h:119
#2  0x0017b4a8 in LocalHostStats::removeRedisSitesKey (this=0xddabcad0, host=0xddabc758) at src/LocalHostStats.cpp:364
#3  0x0017b1d4 in LocalHostStats::LocalHostStats (this=0xddabcad0, _host=0xddabc758) at src/LocalHostStats.cpp:37
#4  0x0014a8f0 in LocalHost::allocateStats (this=0xddabc758) at /home/deri/ntopng/include/LocalHost.h:85
#5  0x00148a44 in LocalHost::initialize (this=0xddabc758) at src/LocalHost.cpp:94
#6  0x001489d8 in LocalHost::LocalHost (this=0xddabc758, _iface=0x714e48, _mac=0x0, _vlanId=0, _ip=0xdd650cac) at src/LocalHost.cpp:34
#7  0x0011f674 in NetworkInterface::findFlowHosts (this=0x714e48, vlanId=0, src_mac=0x0, _src_ip=0xdd650cac, src=0xddabc400, dst_mac=0x0,
    _dst_ip=0xdd650cc4, dst=0xddabc404) at src/NetworkInterface.cpp:2858
#8  0x00083694 in Flow::Flow (this=0xddabc3e0, _iface=0x714e48, _vlanId=0, _protocol=17 '\021', _cli_mac=0x0, _cli_ip=0xdd650cac, _cli_port=27655,
    _srv_mac=0x0, _srv_ip=0xdd650cc4, _srv_port=9697, _icmp_info=0x0, _first_seen=0, _last_seen=0) at src/Flow.cpp:93
#9  0x001172c8 in NetworkInterface::getFlow (this=0x714e48, srcMac=0x0, dstMac=0x0, vlan_id=0, deviceIP=0, inIndex=0, outIndex=1, icmp_info=0x0,
    src_ip=0xdd650cac, dst_ip=0xdd650cc4, src_port=27655, dst_port=9697, l4_proto=17 '\021', src2dst_direction=0xe0ceb063, first_seen=0, last_seen=0,
    len_on_wire=0, new_flow=0xe0ceb062, create_if_missing=true) at src/NetworkInterface.cpp:894
#10 0x0011dd20 in NetworkInterface::pollQueuedeCompanionEvents (this=0x714e48) at src/NetworkInterface.cpp:2352
#11 0x0011b99c in NetworkInterface::dissectPacket (this=0x714e48, bridge_iface_idx=1, ingressPacket=true, sender_mac=0x0, h=0x7e2d6c,
    packet=0x5ebf30 "ܦ2\302\031\373\270\212`\346Eo\b", ndpiProtocol=0xe0ceb3b6, srcHost=0xe0ceb3b0, dstHost=0xe0ceb3ac, flow=0xe0ceb3a8)
    at src/NetworkInterface.cpp:1715
#12 0x000f0748 in packetPollLoop (ptr=0x714e48) at src/PcapInterface.cpp:319
#13 0xf7654494 in start_thread (arg=0xe0cebca0) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x714e80f8
(gdb) 

```

**Comment by simonemainardi** [comment]
@MatteoBiscosi please close this issue is fixed so I can trigger new RPIs builds.

**Comment by simonemainardi** [comment]
This needs to be fixed using the proper serialization key (e.g., mac or ip) as done for timeseries. Use method `getSerializationKey` to get the serialization key.
