### ISSUE TITLE
Active monitoring speedtest fails

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#5025]
I tried to use a speedtest active monitor but it fails.

speedtest-cli works from the server command line.

**Comment by simonemainardi** [comment]
Attach:

- screenshot of the issue
- ntopng --version

**Comment by amastelek** [comment]
![st](https://user-images.githubusercontent.com/61453908/107761644-64b14c00-6d34-11eb-8de8-fd49a74eb9fc.jpg)

v.4.2.210211

**Comment by cardigliano** [comment]
@amastelek what linux distribution/version are you running?

**Comment by amastelek** [comment]
debian buster

**Comment by cardigliano** [comment]
@amastelek I pushed new stable packages to make sure the speedtest support was enabled for your distribution. Please note that with the latest update, when the speedtest is not available, you should no longer see the option in the dropdown (please remove the speedtest you already configured before trying to create it again). Please update and let me know. Thank you.

**Comment by cardigliano** [comment]
This works for me with the package after the last changes, please reopen in case.

**Comment by AlphaDE** [comment]
I am still seeing this issue with v.4.3.210315 (Raspbian GNU/Linux 10 (buster)) |

**Comment by AlphaDE** [comment]
Was this also fixed in 4.3? Because I am still seeing this issue in v.4.3.210315 (Raspbian GNU/Linux 10 (buster)).

**Comment by amastelek** [comment]
> 
> 
> Was this also fixed in 4.3? Because I am still seeing this issue in v.4.3.210315 (Raspbian GNU/Linux 10 (buster)).

I'm still having the issuing on debian buster using 4.2.

**Comment by AlphaDE** [comment]
Any updates on this issue, persists with ntopng /Embedded v.4.3.210411 (Raspbian GNU/Linux 10 (buster))

**Comment by amastelek** [comment]
> 
> 
> Any updates on this issue, persists with ntopng /Embedded v.4.3.210411 (Raspbian GNU/Linux 10 (buster))

I was having the same problem of no result using the 3rd party speedtest-cli https://github.com/sivel/speedtest-cli  This was after a apt-get update && apt-get upgrade of buster.
I changed to the ookla one which works and scripted it to send the url of the result to slack and that now works for me.  I stopped using the speedtest on ntopng.

**Comment by AlphaDE** [comment]
I used speedtest 2.0.2 (installed via apt) so far, now replaced it with 2.1.3 installed via pip3 on two and with the ookla 1.0.0.2 on a third Raspbeery. On the commandline, they work all.

**Comment by amastelek** [comment]
> 
> 
> I used speedtest 2.0.2 (installed via apt) so far, now replaced it with 2.1.3 installed via pip3 on two and with the ookla 1.0.0.2 on a third Raspbeery. On the commandline, they work all.

On the non-ookla one I get a base10 error reported by python.   Didn't realize there is a version available via pip3.

**Comment by ahasbini** [comment]
I'm using docker build and also facing the same issue, the version I'm running is ntopng Community v.4.2.210426.

Even if I delete the speedtest entry in active monitoring, restart ntopng then add speedtest again or unlock the alert and delete past alerts, it still gets stuck with the error.

EDIT: I modified as the previous steps are no longer working with me.

**Comment by cardigliano** [comment]
I just pushed a patch to improve the speedtest reliability, unfortunately some of the servers provided by the speedtest.net service are sometimes replying with http error 500 leading to a test failure, the patch improves server selection. A new update will be available later today, please check it and let us know. Thank you.

**Comment by cardigliano** [comment]
The last patch fixed the issue for me, closing as no other feedback has been posted.

**Comment by AlphaDE** [comment]
I disagree, here, even after an uninstall and reset of all settings, it did work once... and then again fails.

**Comment by cardigliano** [comment]
This has been fixed: the check interval has been increased to avoid getting blacklisted by the servers, the user agent has been 'improved'

**Comment by AlphaDE** [comment]
@cardigliano 
I am sorry I have to disagree on the fix. I have ntopng running in 4 locations on a Raspberry Pi 4, installed "ntopng /Embedded v.5.1.211010 (Raspbian GNU/Linux 10 (buster))" when available and I see a permanent failure for 3 (not a single success since installation and resetup of speedtest.net) and mostly failures on 1.

**Comment by cardigliano** [comment]
@AlphaDE, are you able to run a test from cli and provide the output? Please follow the below instructions:

git clone https://github.com/ntop/ntopng.git
cd ntopng/third-party
gcc -DTEST_SPEEDTEST -DHAVE_EXPAT -I/usr/include/json-c speedtest.c -o speedtest -ljson-c -lexpat -lcurl -lpthread -lm
./speedtest

**Comment by AlphaDE** [comment]
Here we go.

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from NetCologne GmbH (89.1.xxx.xxx)...
Selecting best server based on ping...
Best server: ookla1.kues-data.de:8080(159.78KM)
Server latency is 30ms
Testing download speedDownload speed: 0.00Mbps
Testing upload speedUpload speed: 0.00Mbps
{ "client.isp": "NetCologne GmbH", "client.ip": "89.1.211.187", "server.url": "ookla1.kues-data.de:8080", "server.distance": 159.7818, "server.latency": 30, "download.speed": 0, "upload.speed": 0 }

**Comment by cardigliano** [comment]
@AlphaDE it seems the speedtest is actually running the test, computing a download speed of 0. We need to figure out if this is a bug or expected (due to some external factor)

**Comment by Cyphon00** [comment]
Hi @cardigliano 
I'm having similar issues with speedtest on ntopng 4.2 on NetGate PfSense.
![image](https://user-images.githubusercontent.com/3205742/137587580-56d4023d-27d5-4c51-acfa-86fb61b65c80.png)

Details of my system
![image](https://user-images.githubusercontent.com/3205742/137587613-f452a985-8549-4e41-aa82-8b7d78103d3d.png)

I wasn't able to find/run speed test from the CLI, so I (had to) install it using `pkg add "https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-freebsd.pkg" `

I hope this info is helpful. Please let me know if you need anything more.
Thanks.

**Comment by Cyphon00** [comment]
Hi @cardigliano - Can this issue be reopened please.

**Comment by cardigliano** [comment]
@Cyphon00 what ntopng are you running now? Please note 4.2 is no longer supported, I suggest to test if you are able to reproduce the same on 5.1

**Comment by Cyphon00** [comment]
@cardigliano Hi, I'm on ntopng Community v.4.2.210729.
I'm running it on a pfSense box, so it's part of the pfSense package (and I'd prefer not to install v5 unless absolutely necessary, as it's not natively supported).

I did attempt the above with v5, and did have a similar issue however.

**Comment by cardigliano** [comment]
@Cyphon00 please note we reworked some code of this component in 5.1, thus I am not able to support 4.2, and I recommend testing the latest 5.1

**Comment by AlphaDE** [comment]
The issue still persists on all my 4 instances on ntopng /Embedded v.5.1.211031 (Raspbian GNU/Linux 10 (buster)) 
I also see persisting high load on all 4 which can be temporarily resolved by restarting ntopng.

**Comment by Cyphon00** [comment]
@AlphaDE Thanks for the suggestion. After restarting mine (v4.2), speedtest has worked twice in a row. :)
It was still configured to run in Active Monitoring. I'm curious how long it lasts. 

@cardigliano I don't recall if I tested v5.0 or v5.1 (as it was ~2 months ago), but I'll keep monitoring this thread as I'm curious how this gets resolved for AlphaDE. I'm hopeful that I can benefit from any findings you make for AlphaDE.
For the version I tried, I recall one of the improvements related to removing the '5 mins' speedtest option, to remove the risk of servers banning clients. Thanks. I would find a 15 or 20 minute option very useful, as I am running speedtest to log data to (dis)prove ISP quality. I realise this feature would move me over to v5 ;-)

**Comment by Cyphon00** [comment]
Update: Since rebooting, speedtest has been running successfully (hourly) for 48 hours.
I'd still love to test every 20 mins (on v4) rather than using the 5 minute option.
If anyone is willing to point me to where I could make that unsupported (at my own risk) mod, I'd appreciate it.

**Comment by Cyphon00** [comment]
Update 2 (7 days since last reboot): Active monitoring finally failed.
A few errors appear in the log file and Polllers/Active Monitoring doesn't show in the GUI side menu.
A service restart (via pfSense GUI) didn't fix it, however a _STOP- WAIT30secs-START_ (via the pfSense GUI) worked :)
Hope this is useful to someone.

**Comment by Cyphon00** [comment]
Update: Seems it's finally failed. No amount of stop-restarting the service or deleting the speedtest active monitoring task (and creating a new one)  would fix it. Will keep trying things.

**Comment by thevrownguy** [comment]
I can confirm this issue. Is there a way to have other options for speedtesting?
