### ISSUE TITLE
BT5: Interface traffic report alignment

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5356]
This is broken. @lucaderi please review and tell if you want to directly drop this feature.

![image](https://user-images.githubusercontent.com/3397663/118616723-3d9a6880-b7c2-11eb-9f99-3fe4adb20bfc.png)

**Comment by lucaderi** [comment]
No this feature won't be dropped.

**Comment by simonemainardi** [comment]
Fixed.

**Comment by lucaderi** [comment]
The timepicker is still broken: either you disable edit of the time field or you allow editing

**Comment by simonemainardi** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/3397663/120994171-88d1e680-c784-11eb-8abb-0fb22d622d05.png)
