### ISSUE TITLE
BT5: Mobile version unusable

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5407]
Impossible to click on the top hamburger menu - nothing happens

![image](https://user-images.githubusercontent.com/3397663/119453418-b441e380-bd37-11eb-89a6-8f2905b6bb09.png)

**Comment by gabryon99** [comment]
Fixed as shown below:
https://user-images.githubusercontent.com/14114916/120068028-e4162180-c07e-11eb-9a02-b8dabff3bbaa.mov

**Comment by simonemainardi** [comment]
Still broken. Interface switch doesn't work. Clicking on dropdown entries is ineffective.

![image](https://user-images.githubusercontent.com/3397663/120158589-94f1fd00-c1f4-11eb-8895-17e63e4f7397.png)
