### ISSUE TITLE
ntop blog alerts is broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5422]
<img width="522" alt="Screenshot 2021-05-28 at 11 58 16" src="https://user-images.githubusercontent.com/4493366/119966880-0c811b80-bfac-11eb-825b-9596cbd7414a.png">

**Comment by lucaderi** [comment]
Fixed

**Comment by simonemainardi** [comment]
Still broken. Red "NEW" badges don't go away

![image](https://user-images.githubusercontent.com/3397663/120159318-5d378500-c1f5-11eb-9b8e-2d41c34153a2.png)

Only the counter next to the bell decreases and eventually disappears.
