### ISSUE TITLE
MAC address and Service Map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5625]
When MAC address is used as a key

![Screen Shot 2021-07-05 at 17 14 43](https://user-images.githubusercontent.com/4493366/124492262-816a2100-ddb4-11eb-8177-1e4eba913e13.png)

internally the system identifies hosts using a MAC. The MAC-IP association is stored when the MAC is first detected with the result that when the map is visualized, the association is outdated and thus wrong.

![Screen Shot 2021-07-05 at 17 11 02](https://user-images.githubusercontent.com/4493366/124492187-68617000-ddb4-11eb-95dd-6b6a38188d65.png)

This needs to be fixed

**Comment by lucaderi** [comment]
Still broken. On my network, I identify hosts with a MAC so in this map
- I have too many hosts with an IP address. This means that you have resolved the host when the map is rendered but it's not quite so
![Screen Shot 2021-07-09 at 20 11 10](https://user-images.githubusercontent.com/4493366/125119771-d7f79800-e0f1-11eb-8d1c-41c3a4a53ab7.png)
as most hosts are like this
![Screen Shot 2021-07-09 at 20 12 13](https://user-images.githubusercontent.com/4493366/125119884-fbbade00-e0f1-11eb-849b-108cd0ab6868.png)

So there is still something wrong happening.

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo

**Comment by lucaderi** [comment]
I still see the above problem, with hosts that do not exist instead of MAC addresses
![Screen Shot 2021-07-22 at 19 10 52](https://user-images.githubusercontent.com/4493366/126680347-2e6b0cbf-1a89-4863-8ec3-9de44b5aa359.png)
![Screen Shot 2021-07-22 at 19 11 05](https://user-images.githubusercontent.com/4493366/126680363-b3a540f0-b3cc-4b24-a06e-dc10516b76ae.png)

**Comment by simonemainardi** [comment]
Said that the current implementation is far from being optimal, the rework I've done should fix the behavior reported.

**Comment by lucaderi** [comment]
Better (I see MAC addresses now) but still bugged as in the main graph there are some edges that disappear during drill-down.


![Screen Shot 2021-07-27 at 12 47 23](https://user-images.githubusercontent.com/4493366/127141732-b9b96c4d-b706-4ab4-91f0-30aad1557f31.png)
![Screen Shot 2021-07-27 at 12 47 17](https://user-images.githubusercontent.com/4493366/127141739-3aeb3ac3-9e35-48bd-a2f2-45d83cb985b0.png)
![Screen Shot 2021-07-27 at 12 47 09](https://user-images.githubusercontent.com/4493366/127141742-4d770797-3b23-433d-9592-650adad92c76.png)

**Comment by simonemainardi** [comment]
Issue should be resolved now but this needs to be handled https://github.com/ntop/ntopng/issues/5717

**Comment by lucaderi** [comment]
Still bugged as of today: there are MAC addresses that are unknown and many nodes with only one edge. Something is still wrong

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/128245467-0cfba527-2b28-4f2f-aec6-a49d899e2b26.png)

![image](https://user-images.githubusercontent.com/4493366/128245576-71e07631-e56a-425f-ae3f-6e17da3e0e80.png)

Still bugged.

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/128305590-c753c973-e264-4d0d-89cf-0ec7b47ba24b.png)

![image](https://user-images.githubusercontent.com/3397663/128305620-69301d7c-17ba-4e52-ae32-93418cce2704.png)

**Comment by lucaderi** [comment]
It seems to work with the latest fixes
