### ISSUE TITLE
Support for aarch64 packages

### ISSUE THREAD

**Issue by espectrorj** [ntop/ntopng#5718]
Dear All,

Since last update ntopng starts but the process gets restarted after a few seconds in an endless loop.

Any help appreciated.

Regards,

--> The environment - Raspberry Pi 4:

Version:        4.3.210725 [Enterprise/Professional/Embedded build]
GIT rev:        dev:51072aea7492cb7cf831120cc14e95867b62660d:20210725
Pro rev:        r4057
Built on:       Raspbian GNU/Linux 10 (buster)
Platform:       armv7l
Edition:        Professional Embedded
License Type:   Permanent
Maintenance:    Until Tue Mar 29 12:36:21 2022 [244 days left]

--> Stack trace:

GNU gdb (Raspbian 8.2.1-2) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ntopng...(no debugging symbols found)...done.
(gdb) handle SIG33 nostop noprint pass
Signal        Stop      Print   Pass to program Description
SIG33         No        No      Yes             Real-time event 33
(gdb) handle SIGPIPE nostop noprint pass
Signal        Stop      Print   Pass to program Description
SIGPIPE       No        No      Yes             Broken pipe
(gdb) run
Starting program: /usr/bin/ntopng /etc/ntopng/ntopng.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
27/Jul/2021 19:55:47 [Ntop.cpp:2493] Setting local networks to 10.10.10.0/30,192.168.2.0/27,192.168.3.0/27,192.168.4.0/27,192.168.5.0/27,192.168.99.0/27,192.168.192.0/29,192.168.193.0/29,192.168.100.1/32,10.117.17.0/23
27/Jul/2021 19:55:47 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
27/Jul/2021 19:55:47 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
27/Jul/2021 19:55:47 [NtopPro.cpp:320] [LICENSE] No license file found /etc/ntopng.license: reading license from redis
[New Thread 0xf3e3fca0 (LWP 16300)]
[Thread 0xf3e3fca0 (LWP 16300) exited]
27/Jul/2021 19:55:49 [PcapInterface.cpp:93] Reading packets from eth0 [id: 1]
27/Jul/2021 19:55:49 [Ntop.cpp:2601] Registered interface eth0 [id: 1]
27/Jul/2021 19:55:49 [main.cpp:331] PID stored in file /var/run/ntopng.pid
27/Jul/2021 19:55:49 [Geolocation.cpp:116] Running without geolocation support.
27/Jul/2021 19:55:49 [Geolocation.cpp:117] To enable geolocation follow the instructions at
27/Jul/2021 19:55:49 [Geolocation.cpp:118] https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md
[New Thread 0xf3e3fca0 (LWP 16361)]
[New Thread 0xf31fdca0 (LWP 16362)]
[New Thread 0xf27feca0 (LWP 16363)]
[New Thread 0xf1ffdca0 (LWP 16364)]
[New Thread 0xf15feca0 (LWP 16365)]
[New Thread 0xf09feca0 (LWP 16366)]
27/Jul/2021 19:55:49 [HTTPserver.cpp:1691] Web server dirs [/usr/share/ntopng/httpdocs][/home/pi/scripts]
27/Jul/2021 19:55:49 [HTTPserver.cpp:1694] HTTP server listening on 3000
27/Jul/2021 19:55:49 [Utils.cpp:783] User changed to ntopng
[New Thread 0xf01fdca0 (LWP 16367)]
27/Jul/2021 19:55:49 [NetworkInterface.cpp:2743] Started flow user script hooks loop on interface eth0 [id: 1]...
[New Thread 0xef9fcca0 (LWP 16368)]
27/Jul/2021 19:55:49 [NetworkInterface.cpp:2774] Started host user script hooks loop on interface eth0 [id: 1]...
27/Jul/2021 19:55:49 [main.cpp:401] Working directory: /var/lib/ntopng
27/Jul/2021 19:55:49 [main.cpp:403] Scripts/HTML pages directory: /usr/share/ntopng
27/Jul/2021 19:55:49 [Ntop.cpp:479] Welcome to ntopng armv7l v.4.3.210725 - (C) 1998-21 ntop.org
27/Jul/2021 19:55:49 [Ntop.cpp:489] Built on Raspbian GNU/Linux 10 (buster)
27/Jul/2021 19:55:49 [NtopPro.cpp:764] [LICENSE] Edition:       Professional Embedded
27/Jul/2021 19:55:49 [NtopPro.cpp:765] [LICENSE] License Type:  Permanent License
27/Jul/2021 19:55:49 [NtopPro.cpp:790] [LICENSE] Maintenance:   Until Tue Mar 29 12:36:21 2022 [244 days left]
27/Jul/2021 19:55:49 [Ntop.cpp:945] Adding fe80::dea6:32ff:febd:c11a/128 as IPv6 interface address for eth0
27/Jul/2021 19:55:49 [Ntop.cpp:955] Adding fe80::dea6:32ff:febd:c11a/64 as IPv6 local network for eth0
[New Thread 0xeeffeca0 (LWP 16369)]
27/Jul/2021 19:55:49 [PeriodicActivities.cpp:107] Started periodic activities loop...
[Detaching after fork from child process 16370]
27/Jul/2021 19:55:50 [startup.lua:37] Processing startup.lua: please hold on...
[Detaching after fork from child process 16372]
[Detaching after fork from child process 16374]
27/Jul/2021 19:55:51 [startup.lua:169] [lists_utils.lua:784] Refreshing category lists...
27/Jul/2021 19:55:51 [startup.lua:169] [lists_utils.lua:717] Category Lists (1703 hosts, 3019 IPs, 99 JA3) loaded in 0 sec
[New Thread 0xee7fdca0 (LWP 16417)]
[Thread 0xee7fdca0 (LWP 16417) exited]
27/Jul/2021 19:55:52 [startup.lua:288] Completed startup.lua
[New Thread 0xee7fdca0 (LWP 16430)]
[New Thread 0xedffcca0 (LWP 16431)]
[New Thread 0xed7fbca0 (LWP 16432)]
[New Thread 0xecffaca0 (LWP 16433)]
[New Thread 0xec7f9ca0 (LWP 16434)]
[New Thread 0xebff8ca0 (LWP 16435)]
[New Thread 0xeb7f7ca0 (LWP 16436)]
[New Thread 0xeaff6ca0 (LWP 16437)]
[New Thread 0xea7f5ca0 (LWP 16438)]
[New Thread 0xe9ff4ca0 (LWP 16439)]
27/Jul/2021 19:55:52 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
[New Thread 0xe97f3ca0 (LWP 16440)]
[New Thread 0xe8ff2ca0 (LWP 16441)]
[New Thread 0xe87f1ca0 (LWP 16442)]
[New Thread 0xe7ff0ca0 (LWP 16443)]
[New Thread 0xe77efca0 (LWP 16444)]
[New Thread 0xe6feeca0 (LWP 16445)]
[New Thread 0xe67edca0 (LWP 16446)]
[New Thread 0xe5fecca0 (LWP 16447)]
[New Thread 0xe57ebca0 (LWP 16448)]
[New Thread 0xe4feaca0 (LWP 16449)]
[New Thread 0xe47e9ca0 (LWP 16450)]
[New Thread 0xe3fe8ca0 (LWP 16451)]
27/Jul/2021 19:55:52 [NetworkInterface.cpp:2925] Started packet polling on interface eth0 [id: 1]...
[New Thread 0xe33feca0 (LWP 16452)]
27/Jul/2021 19:55:52 [Ntop.cpp:2601] Registered interface eth0 [VLAN Id: 99] [id: 4]
[New Thread 0xe24feca0 (LWP 16453)]
27/Jul/2021 19:55:53 [NetworkInterface.cpp:2743] Started flow user script hooks loop on interface eth0 [VLAN Id: 99] [id: 4]...
[New Thread 0xe1cfdca0 (LWP 16454)]
27/Jul/2021 19:55:53 [NetworkInterface.cpp:2925] Started packet polling on interface eth0 [VLAN Id: 99] [id: 4]...
27/Jul/2021 19:55:53 [NetworkInterface.cpp:2774] Started host user script hooks loop on interface eth0 [VLAN Id: 99] [id: 4]...
27/Jul/2021 19:55:53 [Ntop.cpp:2601] Registered interface eth0 [VLAN Id: 10] [id: 9]
[New Thread 0xe0ffeca0 (LWP 16455)]
27/Jul/2021 19:55:53 [NetworkInterface.cpp:2743] Started flow user script hooks loop on interface eth0 [VLAN Id: 10] [id: 9]...
[New Thread 0xe07fdca0 (LWP 16456)]
27/Jul/2021 19:55:53 [NetworkInterface.cpp:2925] Started packet polling on interface eth0 [VLAN Id: 10] [id: 9]...

Thread 34 "inline ifid 1" received signal SIGBUS, Bus error.
[Switching to Thread 0xe3fe8ca0 (LWP 16451)]
0x0014eaac in ?? ()
(gdb)

**Comment by simonemainardi** [comment]
Reproduced.

**Comment by simonemainardi** [comment]
Fixed. Thanks for reporting. It was a sporadic issue due to timing. New build in progress. Hold on a couple of hours and update.

**Comment by espectrorj** [comment]
Sure, no problem.

Thank you for the fast fix, @simonemainardi!

Best regards.

**Comment by phantomski77** [comment]
Tested latest `ntopng_4.3.210728-15127_armhf.deb`.

Still the same error:
```
28/Jul/2021 16:15:18 [startup.lua:288] Completed startup.lua
28/Jul/2021 16:15:18 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
28/Jul/2021 16:15:18 [NetworkInterface.cpp:2926] Started packet polling on interface eth0 [id: 0]...
/run.sh: line 3:    18 Bus error               (core dumped) ntopng "$@"
```

And then it goes into continuous restart loop.

Raspberry Pi 4 Model B Rev 1.4
Linux 5.8.0-1029-raspi aarch64
Docker Engine 20.10.7

**Comment by espectrorj** [comment]
Same thing here, even after the update the error remains.

```
Thread 34 "inline ifid 1" received signal SIGBUS, Bus error.
[Switching to Thread 0xe3fe7ca0 (LWP 1779)]
0x0014dab4 in ?? ()
(gdb) bt
#0  0x0014dab4 in ?? ()
#1  0x00000056 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by simonemainardi** [comment]
Are you guys running on docker? I am not currently able to reproduce.

**Comment by simonemainardi** [comment]
also try and execute the following command when ntopng is not started

```
$  redis-cli del ntopng.prefs.checks.configset_v1
```

then try a restart

**Comment by phantomski77** [comment]
Yes, Docker (the .arm64 version on rPi4 8GB).

I have tried the startup process step by step:

1. Nothing running:
```
# redis-cli del ntopng.prefs.checks.configset_v1
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
2. After starting redis-server:
```
# /etc/init.d/redis-server start
Starting redis-server: redis-server.
```
3. Using your command:
```
# redis-cli del ntopng.prefs.checks.configset_v1
(integer) 0
```
4. Starting ntopng:
```
# ntopng -i eth0
29/Jul/2021 11:47:49 [Ntop.cpp:2493] Setting local networks to 127.0.0.0/8,fe80::/10
29/Jul/2021 11:47:49 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
29/Jul/2021 11:47:49 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
29/Jul/2021 11:47:49 [NtopPro.cpp:320] [LICENSE] No license file found /etc/ntopng.license: reading license from redis
29/Jul/2021 11:47:49 [NtopPro.cpp:469] [LICENSE] Unable to validate license [Empty license file]
29/Jul/2021 11:47:49 [NtopPro.cpp:538] WARNING: [LICENSE] Invalid license [Empty license file]
29/Jul/2021 11:47:49 [NtopPro.cpp:555] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
29/Jul/2021 11:47:49 [NtopPro.cpp:557] WARNING: [LICENSE] before returning to community mode
29/Jul/2021 11:47:49 [NtopPro.cpp:559] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
29/Jul/2021 11:47:49 [NtopPro.cpp:561] WARNING: [LICENSE] or run ntopng in community mode starting
29/Jul/2021 11:47:49 [NtopPro.cpp:562] WARNING: [LICENSE] ntopng --community
sh: 1: netstat: not found
29/Jul/2021 11:47:51 [PcapInterface.cpp:93] Reading packets from eth0 [id: 0]
29/Jul/2021 11:47:51 [Ntop.cpp:2601] Registered interface eth0 [id: 0]
29/Jul/2021 11:47:51 [main.cpp:331] PID stored in file /var/run/ntopng.pid
29/Jul/2021 11:47:51 [Geolocation.cpp:116] Running without geolocation support.
29/Jul/2021 11:47:51 [Geolocation.cpp:117] To enable geolocation follow the instructions at
29/Jul/2021 11:47:51 [Geolocation.cpp:118] https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md
29/Jul/2021 11:47:52 [HTTPserver.cpp:1691] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
29/Jul/2021 11:47:52 [HTTPserver.cpp:1694] HTTP server listening on 3000
29/Jul/2021 11:47:52 [Utils.cpp:739] WARNING: Unable to retain privileges for privileged file writing
29/Jul/2021 11:47:52 [Utils.cpp:783] User changed to ntopng
29/Jul/2021 11:47:52 [NetworkInterface.cpp:2744] Started flow user script hooks loop on interface eth0 [id: 0]...
29/Jul/2021 11:47:52 [NetworkInterface.cpp:2775] Started host user script hooks loop on interface eth0 [id: 0]...
29/Jul/2021 11:47:52 [main.cpp:401] Working directory: /var/lib/ntopng
29/Jul/2021 11:47:52 [main.cpp:403] Scripts/HTML pages directory: /usr/share/ntopng
29/Jul/2021 11:47:52 [Ntop.cpp:479] Welcome to ntopng armv7l v.4.3.210728 - (C) 1998-21 ntop.org
29/Jul/2021 11:47:52 [Ntop.cpp:489] Built on Raspbian GNU/Linux 10 (buster)
29/Jul/2021 11:47:52 [NtopPro.cpp:763] [LICENSE] System Id:	L44D43374499602D2--U0000000000000000--OL
29/Jul/2021 11:47:52 [NtopPro.cpp:764] [LICENSE] Edition:	Enterprise Embedded
29/Jul/2021 11:47:52 [NtopPro.cpp:765] [LICENSE] License Type:	Time-Limited [Empty license file] License
29/Jul/2021 11:47:52 [NtopPro.cpp:785] [LICENSE] Validity:	Until Thu Jul 29 11:57:49 2021
29/Jul/2021 11:47:52 [Ntop.cpp:914] Adding x.x.x.x/32 as IPv4 interface address for eth0
29/Jul/2021 11:47:52 [Ntop.cpp:923] Adding x.x.x.x/24 as IPv4 local network for eth0
29/Jul/2021 11:47:52 [PeriodicActivities.cpp:107] Started periodic activities loop...
29/Jul/2021 11:47:54 [startup.lua:37] Processing startup.lua: please hold on...
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:784] Refreshing category lists...
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:420] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:420] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:420] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:420] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:420] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
29/Jul/2021 11:47:57 [startup.lua:169] [lists_utils.lua:420] Updating list 'SSLBL JA3' [https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv]... OK
29/Jul/2021 11:47:58 [startup.lua:169] [lists_utils.lua:420] Updating list 'Snort IP Block List' [https://snort.org/downloads/ip-block-list]... ERROR [The server returned an error [HTTP Code: 429]]
29/Jul/2021 11:47:58 [startup.lua:169] [lists_utils.lua:717] Category Lists (1725 hosts, 1766 IPs, 99 JA3) loaded in 0 sec
29/Jul/2021 11:47:58 [startup.lua:288] Completed startup.lua
29/Jul/2021 11:47:58 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
29/Jul/2021 11:47:58 [NetworkInterface.cpp:2926] Started packet polling on interface eth0 [id: 0]...
Bus error (core dumped)
```

Same error.
Same error after restart.

Could it be related to running armv7l code (32bit) on arm64v8 (64bit) system? Potential memory access to memory that doesn't exist, etc.

**Comment by simonemainardi** [comment]
> Could it be related to running armv7l code (32bit) on arm64v8 (64bit) system

This is probable. I have been running the latest version without crashes for hours after all tests have succeeded ( on a physical rpi).

@espectrorj are you on docker as well?

**Comment by phantomski77** [comment]
Strange thing is all was perfectly fine on `v.4.3.210711`. Since then, all the subsequent builds fail with the same error. Something changed since that release that's causing it.

**Comment by simonemainardi** [comment]
I am not sure about the cause but you agree with me that running armv7l code (32bit)  on a dockerized arm64v8 (64bit) is quite hacky....

Are you able to build a debug version and run inside gdb?

**Comment by phantomski77** [comment]
It's a bit hacky, I do agree, but should be perfectly within the realms of arm64v8 interpreter and instruction set. Plus rPi4 is 8x the memory of rPi3.

**A little update** - running ntopng on different interfaces produces different results. For example local loopback `-i lo` doesn't crash. Some of the Docker networks run for a while, then crash later. It seems to depend on type of packets received (or their amount).
If it runs for a while, some new messages are produced:
```
29/Jul/2021 14:21:51 [NetworkInterface.cpp:2926] Started packet polling on interface br-537d9cb7f55a [id: 3]...
29/Jul/2021 14:21:51 [NetworkInterface.cpp:1863] Packets exceeding the expected max size have been received [len: 2767][max len: 1518].
29/Jul/2021 14:21:51 [NetworkInterface.cpp:1866] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
29/Jul/2021 14:21:51 [NetworkInterface.cpp:1868] WARNING: using: sudo ethtool -K br-537d9cb7f55a gro off gso off tso off
```

**Comment by phantomski77** [comment]
> Are you able to build a debug version and run inside gdb?

Not on my own (never done that), but if you'd have time for little tutorial, I'm happy to test it.

**Comment by espectrorj** [comment]
> 
> 
> Are you guys running on docker? I am not currently able to reproduce.

Negative, no docker here.

I'm also running ntopng on arm64v8 (64bit) system.

**Comment by espectrorj** [comment]
> 
> 
> also try and execute the following command when ntopng is not started
> 
> ```
> $  redis-cli del ntopng.prefs.checks.configset_v1
> ```
> 
> then try a restart

Issued the above command and restarted ntopng but got the same error.

```
pi@server-3-2:~ $ sudo redis-cli del ntopng.prefs.checks.configset_v1
(integer) 1
pi@server-3-2:~ $ sudo /usr/bin/ntopng -i eth0 /etc/ntopng/ntopng.conf
29/Jul/2021 11:09:43 [Ntop.cpp:2601] Registered interface eth0 [VLAN Id: 4] [id: 6]
29/Jul/2021 11:09:43 [NetworkInterface.cpp:2744] Started flow user script hooks loop on interface eth0 [VLAN Id: 4] [id: 6]...
29/Jul/2021 11:09:43 [NetworkInterface.cpp:2775] Started host user script hooks loop on interface eth0 [VLAN Id: 4] [id: 6]...
29/Jul/2021 11:09:43 [NetworkInterface.cpp:2926] Started packet polling on interface eth0 [VLAN Id: 4] [id: 6]...
29/Jul/2021 11:09:43 [Ntop.cpp:2601] Registered interface eth0 [VLAN Id: 99] [id: 4]
29/Jul/2021 11:09:43 [NetworkInterface.cpp:2744] Started flow user script hooks loop on interface eth0 [VLAN Id: 99] [id: 4]...
29/Jul/2021 11:09:43 [NetworkInterface.cpp:2775] Started host user script hooks loop on interface eth0 [VLAN Id: 99] [id: 4]...
29/Jul/2021 11:09:43 [NetworkInterface.cpp:2926] Started packet polling on interface eth0 [VLAN Id: 99] [id: 4]...
Bus error
```

**Comment by simonemainardi** [comment]
> I'm also running ntopng on arm64v8 (64bit) system.

How did you install the package? Unfortunately we are not yet supporting arm64v8

**Comment by phantomski77** [comment]
> Unfortunately we are not yet supporting arm64v8

I know you don't @simonemainardi and we're of course very grateful you're spending some time trying to find a solution. So thank you very much for your kind support!

If I can make a kind suggestion, I'd very much recommend putting some resources into this architecture. Raspberry Pi is an obvious example (that's how a lot of us start learning various systems before deploying them further or using them in enterprise on real servers). But it's not just hobbyists. arm arch has a big potential already and it's not just mobile devices and microcontrollers anymore. Look at [Apple's M1](https://debugger.medium.com/why-is-apples-m1-chip-so-fast-3262b158cba2) or [Amazon's AWS Graviton](https://aws.amazon.com/ec2/graviton/). Cheap, efficient, powerful.

I'm not sure which compiler you use, but gcc has a arm64v8 (with further sub-versions for later variants) support for quite some time. Both Debian and Ubuntu now run natively on the platform too. There's a big future ahead ;)

**Comment by simonemainardi** [comment]
@phantomski77 what's the actual rpi arm64v8 distribution you are using? And the hardware? we are trying to understand if we can produce the build

**Comment by phantomski77** [comment]
> @phantomski77 what's the actual rpi arm64v8 distribution you are using? And the hardware? we are trying to understand if we can produce the build

**HW**: Raspberry Pi 4 Model B Rev 1.4 (8GB)
**CPU**: Broadcom [BCM2711](https://datasheets.raspberrypi.org/bcm2711/bcm2711-peripherals.pdf) (ARM Cortex-A72 - arm64v8A)
**Kernel**: Linux 5.8.0-1029-raspi 
**OS**: Ubuntu 20.10 aarch64
**Docker**: 20.10.7 CE linux/arm64
**ntopng**: `4.3.210711` - **worked ok**, `4.3.210718`, `4.3.210725` and `4.3.210728` **didn't work.**

I'm using ntopng Docker version (based on debian:buster), which is image built using `Dockerfile.ntopng-arm64` from your [ntop/docker-ntop repository](https://github.com/ntop/docker-ntop). I've actually created this Dockerfile myself, it's based on the original `Dockerfile.ntopng-raspberry`, which didn't work. The reason is arm64 packages are actually available in your packages repository, but it's only older 3.x version ntopng.  This new Dockerfile forces latest armhf7l package with armhf dependencies in order to use latest ntopng builds, which are available only for this arch at the moment ([see PR with detailed explanation here](https://github.com/ntop/docker-ntop/pull/5))

**Comment by espectrorj** [comment]
I switched to 32 bit kernel (armv7l+) and can confirm that the application is running fine for 30 minutes now.

But ntopng was working fine until latest updates as @phantomski77 already mentioned, even with 64 bit Kernel enabled.

`HW: Raspberry Pi 4 Model B Rev 1.2 (4GB)`

64 bit Kernel - Crashes and endless restart loop
```
pi@server-3-2:~ $ uname -a
Linux server-3-2 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
```

32 bit Kernel - No issues so far.
```
pi@server-3-2:~ $ uname -a
Linux server-3-2 5.10.52-v7l+ #1440 SMP Tue Jul 27 09:55:21 BST 2021 armv7l GNU/Linux
```

**Comment by martinscheu** [comment]
same issue after auto update. `Linux raspberrypi 5.10.52-v8+ #1440 SMP PREEMPT Tue Jul 27 09:56:40 BST 2021 aarch64 GNU/Linux` ntopng is installed native, but docker is running on the host.

**Comment by simonemainardi** [comment]
@everyone unless we officially support `aarch64` for binary packages, the issue is likely to occur.

You should not expect to have a package built for an architecture to be running on another architecture. The fact that is was working/not working is not really meaningful as it could be due to unpredictable factors, such as functions used, compilers and compiled instructions, and so on.

Solution to this issue is to have `aarch64` packages, not trying to run armv7l on aarch64.

**Comment by simonemainardi** [comment]
Which distro would you like to have packaged? Ubuntu20?

**Comment by phantomski77** [comment]
> Which distro would you like to have packaged? Ubuntu20?

I personally prefer Docker, so it doesn’t really matter - Ubuntu 20 or 21 or Debian 10 would all do very nicely. If I needed to run this standalone, I’d probably prefer Debian for security, but no problem with Ubuntu 20.

**Comment by phantomski77** [comment]
> You should not expect to have a package built for an architecture to be running on another architecture. The fact that is was working/not working is not really meaningful as it could be due to unpredictable factors, such as functions used, compilers and compiled instructions, and so on.

You’re absolutely right and this was always “nice to have” rather than a requirement. I was actually surprised it worked at all in `4.3.210711`, but when it stopped in later versions it was bit of a bummer. In my limited experience with arm arch it always seemed to be pretty reliable running the old instruction set, it’s usually memory addressing when it falls apart. 
 
> Solution to this issue is to have `aarch64` packages, not trying to run armv7l on aarch64.

Absolutely. Big thumbs up if you decide to support it. I really like these small sub 10W fanless devices running around network as data collectors and monitoring devices.

**Comment by espectrorj** [comment]
> 
> 
> > Which distro would you like to have packaged? Ubuntu20?
> 
> I personally prefer Docker, so it doesn’t really matter - Ubuntu 20 or 21 or Debian 10 would all do very nicely. If I needed to run this standalone, I’d probably prefer Debian for security, but no problem with Ubuntu 20.

+1 for Debian 10.

**Comment by espectrorj** [comment]
> 
> 
> > You should not expect to have a package built for an architecture to be running on another architecture. The fact that is was working/not working is not really meaningful as it could be due to unpredictable factors, such as functions used, compilers and compiled instructions, and so on.
> 
> You’re absolutely right and this was always “nice to have” rather than a requirement. I was actually surprised it worked at all in `4.3.210711`, but when it stopped in later versions it was bit of a bummer. In my limited experience with arm arch it always seemed to be pretty reliable running the old instruction set, it’s usually memory addressing when it falls apart.
> 
> > Solution to this issue is to have `aarch64` packages, not trying to run armv7l on aarch64.
> 
> Absolutely. Big thumbs up if you decide to support it. I really like these small sub 10W fanless devices running around network as data collectors and monitoring devices.

Exactly, @phantomski77.

Couldn't agree more.

**Comment by phantomski77** [comment]
**Update:**
I've tested version `5.1.210829` from https://packages.ntop.org/RaspberryPI/buster_pi/armhf/ntopng/ntopng_5.1.210829-15416_armhf.deb and so far so good - `armv7l` runs well on `aarch64` with the following:
**HW**: Raspberry Pi 4 Model B Rev 1.4 (8GB)
**CPU**: Broadcom [BCM2711](https://datasheets.raspberrypi.org/bcm2711/bcm2711-peripherals.pdf) (ARM Cortex-A72 - arm64v8A)
**Kernel**: Linux 5.11.0-1016-raspi
**OS**: Ubuntu 21.04 aarch64
**Docker**: 20.10.8 CE linux/arm64

I know it's still unsupported (and Raspberry and arm64 Dockerfiles were removed), but whatever changed has recovered previous functionality (unless it's just the new kernel, Debian updates, etc). Just thought you might want to know.

**Comment by phantomski77** [comment]
It looks like most `5.1.x` `armhf` builds run well on RaspberryPi 4, I've now tested `5.1.210902` and it's also without issues. If anyone's interested, I'm regularly building and testing 64bit `arm64` Docker images from these nightly builds, which are available here:
[https://hub.docker.com/repository/docker/phantomski/ntopng](https://hub.docker.com/repository/docker/phantomski/ntopng)

Of course all the usual limitations apply - unofficial, unsupported, potentially unstable.

**Comment by mzac** [comment]
I am trying to install ntopng on a Raspberry Pi 3B+ running Raspbian 64 bit and getting an error during the install.  From this thread I see only the armhf version is available and not the arm64 yet.

Note: on this same Pi I had installed Raspbian armhf 32 bit and I was able to install all the packages and get it up and running.  Now I'm trying arm64.

```
root@ntop:~ # uname -a
Linux ntop 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux
root@ntop:~ # apt-get install --no-install-recommends ntopng
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: ntopng-data (= 3.8+dfsg1-2.1) but 4.3.210629 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by phantomski77** [comment]
> I am trying to install ntopng on a Raspberry Pi 3B+ running Raspbian 64 bit and getting an error during the install. From this thread I see only the armhf version is available and not the arm64 yet.
> 
> Note: on this same Pi I had installed Raspbian armhf 32 bit and I was able to install all the packages and get it up and running. Now I'm trying arm64.

The problem with [official ntop deb packages](https://packages.ntop.org/) for Raspberry Pi is that they don’t contain `arm64` platform specific binaries, so your 64 bit kernel installation instead defaults to only `arm64` repositories available and known to dpkg - which are Debian/Raspbian (not ntop.org) maintained and very old (3.x). These are not compatible with ntop-data, which is oddly available in more recent version. This creates the dependency mismatch error you encountered.

The only way so far to resolve this is to force 32bit `armhf` binaries to be installed instead and run them using 32bit interpreter. It’s a hack, it’s unsupported, but well, it runs great so far. The system is designed to do that natively. Until the team decides to support this arch directly, I don’t know a better solution.

You can check my [Dockerfile](https://github.com/phantomski77/docker-ntop/blob/arm64/Dockerfile.ntopng-arm64) for a self explanatory process of how to achieve this by `--add-architecture` dpkg option and `armhf` tags for the desired packages.

Bit more info in the [description here](https://hub.docker.com/repository/docker/phantomski/ntopng)

If you don’t use Docker and install this directly, I’d suggest following steps:
```
apt-get update
apt-get install software-properties-common wget lsb-release gnupg libelf1
wget -q http://packages.ntop.org/RaspberryPI/apt-ntop_1.0.190416-469_all.deb
apt-get install ./apt-ntop_1.0.190416-469_all.deb
apt-get clean all
dpkg --add-architecture armhf
apt-get update
apt-get install ntopng:armhf libcap2:armhf libzstd1:armhf
/etc/init.d/redis-server start
ntopng -i eth0
```

**Comment by mzac** [comment]
Thanks @phantomski77 !  I had actually found that config not long after I posted and it worked!  Now I have a very 'hot' Pi3 that I need to get better cooling for ! ;D

**Comment by phantomski77** [comment]
> Thanks @phantomski77 ! I had actually found that config not long after I posted and it worked! Now I have a very 'hot' Pi3 that I need to get better cooling for ! ;D

No probs. I found the older builds before `211017` to use significantly less CPU. I'm not sure what changed, but `ntopng` is now very demanding process indeed, roughly 10x higher load, maxing out one core on my rPi4. I'm keeping an eye on it for upcoming versions and will flag it if necessary.

**Comment by lucaderi** [comment]
Implemented on the latest bullseye_pi (rPI)
