### ISSUE TITLE
Segfault on pfSense related to LuaEngine

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#5929]
Using pfSense 21.05.1-RELEASE (amd64) on a Netgate SG-4860, with  v.5.1.210927 from the ntop pkg repo, I am receiving the following error approximately 15-45 minutes after starting:

> ` WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][index]`
> `Segmentation fault`

I was originally working with alfredo.cardigliano via the Discord on this issue. I have a coredump from a previous version that was also exhibiting the same behavior, which I would love to attach, but GitHub is choking on after being compressed

**Comment by cardigliano** [comment]
@Taralas I remember you had a bunch of failures, some of them were due to the inability to find lua modules (we pushed a fix for this some time ago), could you confirm you are no longer experiencing those failures? 
Is this the only message you get now, or you have more logs? Thank you.

**Comment by Taralas** [comment]
That is the only message that I am receiving at this time.

**Comment by cardigliano** [comment]
Please drop an email to cardigliano at ntop.org, I will send a debug binary

**Comment by cardigliano** [comment]
ntopng binaries were crashing upon application startup until yesterday's release. Today's version seems to be running and it is executing (with debug symbols) at the user premises. We will wait for updates.

**Comment by Taralas** [comment]
Sorry on the lack of updates. Work has been a bit difficult. I was able to get some time this morning, and ran the last debug build, and had two crashes, both with no stack traces:

14/Oct/2021 11:45:01 [LuaEngine.cpp:560] WARNING: Script failure {/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][attempt to index a string value]
PANIC: unprotected error in call to Lua API (attempt to index a function value)
Abort trap
During startup program exited with code 134.
(gdb) bt
No stack.

14/Oct/2021 12:15:01 [LuaEngine.cpp:560] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][attempt to index a string value]
Segmentation fault
During startup program exited with code 139.
(gdb) bt
No stack.

Shawn Hurst
(262) 497-7787

**Comment by Taralas** [comment]
From last night:

14/Oct/2021 20:45:00 [LuaEngine.cpp:560] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][attempt to index a string value]
PANIC: unprotected error in call to Lua API (attempt to index a function value)
Abort trap
During startup program exited with code 134.
(gdb) bt
No stack.

**Comment by cardigliano** [comment]
@Taralas please be patient a bit more as we are testing new fixes that could also fix your issue. Sorry for the inconvenience.

**Comment by Taralas** [comment]
Not a problem. Real troubleshooting takes time 😉

**Comment by lucaderi** [comment]
@Taralas Can you please update and report: we believe we have fixed the issues

**Comment by simonemainardi** [comment]
Other users have reported that the issue has been fixed on pfSense. So I'm closing for now, asking @Taralas to check and reopen if necessary.

**Comment by Taralas** [comment]
Sadly, I am still getting nightly crashes, but I do not believe they are related to the lua issues.
