### ISSUE TITLE
Invalid interface selection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6004]
![Screen Shot 2021-10-25 at 16 00 49](https://user-images.githubusercontent.com/4493366/138709786-0872dd37-3341-4a25-8d23-60baef730cc4.png)
Flows coming from loopback and enp0s31f6 are mixed on the same page

**Comment by MatteoBiscosi** [comment]
Interface id was missing from where statement, now should be fixed (pro repo), please update and let me know

**Comment by lucaderi** [comment]
![Screen Shot 2021-10-25 at 20 24 20](https://user-images.githubusercontent.com/4493366/138749615-33c2a102-fee9-43c3-a063-e60bcfe23ba0.png)
Still broken

**Comment by lucaderi** [comment]
Seems to work now
