### ISSUE TITLE
Service map host pools filter not working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#6110]
In the service map, selecting an host pool from the drop down always yields "No services found" although there are active hosts and services.

![image](https://user-images.githubusercontent.com/3397663/144409955-383d6f08-dad0-4ffb-bec8-8445f9daaa3d.png)

**Comment by MatteoBiscosi** [comment]
Should be fixed now, please let me know.
![Screenshot from 2021-12-07 16-56-33](https://user-images.githubusercontent.com/49585191/145062627-ea503ee4-f890-4b3f-93ab-146d19d52234.png)

**Comment by simonemainardi** [comment]
Verified as fixed.

**Comment by simonemainardi** [comment]
still not working (should be case insensitive)

<img width="194" alt="image" src="https://user-images.githubusercontent.com/3397663/146573035-6f10760c-d027-4d22-bccd-50cb86888671.png">
