### ISSUE TITLE
Service map all protocols dropdown not sorted

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#6111]
The dropdown with all protocols is not sorted. This makes the search too time consuming.

**Comment by MatteoBiscosi** [comment]
Fixed l7 proto dropdown ordering, pro version.

**Comment by simonemainardi** [comment]
Still not working, should be case-insensitive

<img width="194" alt="image" src="https://user-images.githubusercontent.com/3397663/146573135-4554ad77-aa93-4864-9f99-7f2d0a1a3478.png">

**Comment by simonemainardi** [comment]
Fixed. Pro part.
