### ISSUE TITLE
Cannot use -p option on ntop config file

### ISSUE THREAD

**Issue by Jenubis** [ntop/ntopng#6355]
**Environment**:
* OS name: Raspberry Pi 3
* OS version: [e.g. 18.04]
* Architecture: ARM
* ntopng version/revision: [e.g. 5.1.211223] : [](https://github.com/ntop/ntopng/commit/ca846f4015213719f7d3cd0a4efed51f085ba7c1)ntopng Enterprise M v.5.3.220227 rev.17006 (Raspbian GNU/Linux 11 (bullseye)) |

**What happened**:

Indicated -p option for custom protocol into the config file to start from systemctl ![image](https://user-images.githubusercontent.com/1705740/156357535-17b4dad2-ef9d-4787-afae-b565a95699d9.png)
,  in the log : 
![image](https://user-images.githubusercontent.com/1705740/156357697-a194a134-d8ec-4fe8-9675-a1c3a662e6f9.png)

**What did you expect to happen?**

Enable custom Application Rules modification on GUI

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
Fixed in the current version

**Comment by Jenubis** [comment]
Hello

Just tested today and still have the same issue 
![48864F39-B951-4A97-AB62-32BBE7109ED3](https://user-images.githubusercontent.com/1705740/173462428-43f8fc58-14f2-43c9-83c7-776c1c191ec3.jpeg)
![96531FB4-9AA3-44CC-A06B-E057852988E3](https://user-images.githubusercontent.com/1705740/173462438-8bfa01c1-2721-463b-bb79-84e0507e07ec.png)
![88F02679-FC96-4F89-AD7C-F552445DDFD0](https://user-images.githubusercontent.com/1705740/173462440-c22e3ab6-4539-4bc7-a8b6-dd83d9afd30e.jpeg)

**Comment by cardigliano** [comment]
Please note that the '-p' option is using a bad character as '-' (which is similar but not exactly the same), please delete it and write it again.
