### ISSUE TITLE
Error in alerts edit options

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#6396]
**Environment**:
* OS name: [e.g. Ubuntu] 
* Red Hat Enterprise Linux 8.5
* Architecture: [e.g. amd64]
* ntopng version/revision: []
* [ntopng Enterprise M v.5.2.220309

**What happened**:

Cant edit alerts setting, see picture.

14/Mar/2022 11:34:20 [LuaEngine.cpp:1254] WARNING Script failure [/usr/share/ntopng/scripts/lua/get_check_config.lua][/usr/share/ntopng/scripts/lua/modules/alert_exclusions.lua:238: attempt to index a nil value (global 't')]

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

[LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_check_config.lua][/usr/share/ntopng/scripts/lua/modules/alert_exclusions.lua:238: attempt to index a nil value (global 't')]
mar 14 11:29:00 xxxxxxxxxxxx ntopng[788037]: 14/Mar/2022 11:29:00 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_check_config.lua][/usr/share/ntopng/scripts/lua/modules/alert_exclusions.lua:238: attempt to index a nil value (global 't>
m
![Edit Action 2022-03-14 113714](https://user-images.githubusercontent.com/43986547/158157024-db08d1b3-3d7e-43d7-9622-b39fc37d1d21.jpg)

**Comment by MatteoBiscosi** [comment]
Hi @ListenNjoy a new update should be available in a couple of hours, please update and let me know

**Comment by ListenNjoy** [comment]
Hi, its still the same, error below

15/Mar/2022 08:22:58 [LuaEngine.cpp:1254] WARNING Script failure [/usr/share/ntopng/scripts/lua/get_check_config.lua][/usr/share/ntopng/scripts/lua/modules/alert_exclusions.lua:240: attempt to index a nil value (local 't')]

**Comment by MatteoBiscosi** [comment]
Hi @ListenNjoy try to update and let me know if now it's working please. With the latest patch in my lab the issue was fixed

**Comment by ListenNjoy** [comment]
Sorry to say but i still get error and only {action} button.

Error below

22/Mar/2022 08:08:38 [LuaEngine.cpp:1254] WARNING Script failure [/usr/share/ntopng/scripts/lua/get_check_config.lua][/usr/share/ntopng/scripts/lua/modules/alert_exclusions.lua:240: attempt to index a nil value (local 't')]

**Comment by ListenNjoy** [comment]
I have tested to reset ntopng on a test server with the same error, with the command: redis-cli -n ntopng.conf flushdb, and after this the edit alert option is working. 

Is there a way to only reset the alerts config in ntopng so we dont lose all setting and timeseries.?

**Comment by MatteoBiscosi** [comment]
Hi @ListenNjoy, you have to go here and reset the checks
![Screenshot from 2022-03-28 07-43-57](https://user-images.githubusercontent.com/49585191/160333783-45359781-9265-467e-bf44-0f2e9e634803.png)

**Comment by ListenNjoy** [comment]
Thanks for this all is working after reset of checks setting and now everything works as i should.
