### ISSUE TITLE
DOT1Q_SRC_VLAN from nprobe not populating VLAN in ntopng

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#650]
Tweaking my nprobe template that is collecting sflow
I noticed that %SRC_VLAN and %DST_VLAN didn't populate via nprobe but %DOT1Q_SRC_VLAN did however I don't see ntopng making use of that template field

**Comment by simonemainardi** [comment]
can you please capture sflow traffic in order to make sure it is actually carrying SRC_VLAN and DST_VLAN ? Feel free to enclose the pcap if you want us to do the check.

**Comment by seismiccollision** [comment]
@simonemainardi the sflow I'm capturing contains the 802.1q tag
I was running tests with nprobe writing out to a file and saw the SRC_VLAN and DST_VLAN write out at "0" but DOT1Q_SRC_VLAN writes out the VLAN contained in the sflow capture's dot1q header

Does that make sense?

**Comment by simonemainardi** [comment]
@seismiccollision everything looks good as very likely the sflow doesn't have SRC_VLAN and DST_VLAN, but has just the DOT1Q_SRC_VLAN populated. This is why you get 0 for SRC_VLAN.

Also according to this discussion https://www.ietf.org/mail-archive/web/ipfix/current/msg06205.html I argue we could collapse DOT1Q_SRC_VLAN to SRC_VLAN for visualization purposes in ntopng. However, I would be interested in @lucaderi 's opinion on this.

**Comment by lucaderi** [comment]
@seismiccollision Please send me a pcap to reproduce your issue and also specify the exact CLI I need ti use to reproduce the issue

[ 58] %SRC_VLAN                   %vlanId                       Source VLAN (inner VLAN in QinQ)
[ 59] %DST_VLAN                   %postVlanId                   Destination VLAN (inner VLAN in QinQ)
[243] %DOT1Q_SRC_VLAN             %dot1qVlanId                  Source VLAN (outer VLAN in QinQ)
[254] %DOT1Q_DST_VLAN             %postdot1qVlanId              Destination VLAN (outer VLAN in QinQ)

These IEs are used when we have nested VLANs. Please share that pcap and I will see what happens

**Comment by seismiccollision** [comment]
@lucaderi I will follow this up with a sample pcap to your email
The command I was using to see this was:
`nprobe -b 2 --interpret-flow-packets -P temp --collector-port 6344 -T "%EXPORTER_IPV4_ADDRESS %INPUT_SNMP %OUTPUT_SNMP %IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV4_DST_MASK %IN_SRC_MAC %OUT_DST_MAC %SRC_VLAN %DST_VLAN %DOT1Q_SRC_VLAN"`

Thanks for all the continued help to you and @simonemainardi - someday I hope to know enough to be able to contribute back

**Comment by lucaderi** [comment]
I have fixed this issues and the patch will be included in the next build. In essence in case of a single encapsulation (no stacked VLANs) nprobe now populates also the inner VLAN tags (SRC_VLAN/DST_VLAN) . Thanks for reporting it.

**Comment by seismiccollision** [comment]
@lucaderi I'm not sure if I was supposed to see a build to incorporate the DOT1Q_SRC_VLAN but the latest update doesn't seem to fix this

I was expecting to see something in ntopng/src/ParserInterface.cpp like:
...
addMapping("DOT1Q_SRC_VLAN", 243);
...
        case DOT1Q_SRC_VLAN:
          flow.vlan_id = atoi(value);
          break;
...

maybe? I could be way off the mark here

**Comment by simonemainardi** [comment]
hi @seismiccollision we have decided to use the outer vlan tag found in DOT1Q_SRC_VLAN/DOT1Q_DST_VLAN to set the flow vlan field, provided no inner vlan tag is available either in SRC_VLAN or DST_VLAN.
