### ISSUE TITLE
Invalid IPv6 Address Filtering in Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6572]
In the flow analysis page clicking on an IPv6 address
![image](https://user-images.githubusercontent.com/4493366/166823746-059a761c-72ea-4b63-bf06-a387389d1ac8.png)the 
following dialog is open
![Screen Shot 2022-05-04 at 22 50 06](https://user-images.githubusercontent.com/4493366/166823840-88d3f1f5-b312-4b22-86f7-2f304eeb8875.png)
 
Instead of the Server IP (the same happens with the Client) the Server Name is selected.

**Comment by cardigliano** [comment]
Fixed in pro 09cdc630b664327800d2420e7d6db793739d218f (custom queries with no IP version field were affected)

**Comment by lucaderi** [comment]
I have tested with today's code on HS and it still faile
![Screen Shot 2022-06-09 at 10 09 42](https://user-images.githubusercontent.com/4493366/172797986-9c07f20f-2e96-42d0-b968-990131787dd6.png)
d

**Comment by cardigliano** [comment]
It seems this was actually working according to the last check. Please reopen in case.
