### ISSUE TITLE
When alerts are acknowledged, they are still accounted in the menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6574]
![Screen Shot 2022-05-06 at 15 17 57](https://user-images.githubusercontent.com/4493366/167143155-5d4055d4-5238-4f87-9367-51db23ceacc9.png)
In the move screen dump the list is empty but there is still 1 accounted as alert

**Comment by MatteoBiscosi** [comment]
Should be fixed in latest version

**Comment by lucaderi** [comment]
Still broken. Just go to http://194.xxxx:3000/lua/alert_stats.lua?page=user&epoch_begin=1653598888&epoch_end=1653600688&status=historical&ifid=2&severity=3%3Blte
take the alert and acknowledge. As you will see it won't disappear as it should.

**Comment by cardigliano** [comment]
The number in the menu does not match the alerts displayed when they have been triggered after the selected time range. A note about this has been added to the page footer to warn the user.
