### ISSUE TITLE
Historical flow using UTC and local time

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6688]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220610 (Ubuntu 20.04.4 LTS

**What happened**:
In historical flow explorer the search time is UTC based, but records are shown in local time zone:
<img width="1478" alt="Screenshot 2022-06-11 at 10 25 16" src="https://user-images.githubusercontent.com/38549755/173179998-d01770b8-2ce1-44a2-9ea6-c7ceec2e7ced.png">

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
@martinscheu Can you report (after ntopng update) what you see in the local time zone?

![image](https://user-images.githubusercontent.com/4493366/173357732-e86daad3-75dd-44a5-bbff-8594c228df18.png)

**Comment by martinscheu** [comment]
yes: 
Local Timezone | Etc/UTC

which corresponds to the system settings:
```
systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-06-15 13:09:39 UTC; 2s ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 3562880 (systemd-timesyn)
     Status: "Initial synchronization to time server

```

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu the issue should be fixed now, ntopng is going to display the server time.
(tried to put the machine in China and it's working correctly).
Please tell me if you find some not epoch not correctly formatted :)
![Screenshot from 2022-06-16 20-34-40](https://user-images.githubusercontent.com/49585191/174094355-743c94b9-5226-449f-9dd2-37f3541fac1d.png)

**Comment by martinscheu** [comment]
@MatteoBiscosi yes for Historical flows recorded after the update it works, for older flows it still shows a time difference:
current:
<img width="1442" alt="Screenshot 2022-06-18 at 15 31 06" src="https://user-images.githubusercontent.com/38549755/174439978-ce892f57-57e1-4259-8875-167019990a1d.png">


old:

<img width="1444" alt="Screenshot 2022-06-18 at 15 30 50" src="https://user-images.githubusercontent.com/38549755/174439974-1dfa6fed-52bb-4052-945a-bc22bed16e08.png">

**Comment by martinscheu** [comment]
works well, thanks @MatteoBiscosi, @lucaderi
