### ISSUE TITLE
This flow cannot be found. Very likely it is expired and ntopng has purged it from memory.

### ISSUE THREAD

**Issue by klevacore** [ntop/ntopng#6706]
When going to Flows -> Live and clicking on "+" for more detail a following message appears (most of the time):
"This flow cannot be found. Very likely it is expired and ntopng has purged it from memory."
or
"This flow has been purged from memory." while displaying some flow details, and goes to the message above upon clicking anything. 

Settings on the Preferences page:
Idle Local Hosts Cache - On
Local Hosts Cache Duration - 12h
Active Local Hosts Cache - On
Active Local Host Cache Interval - 12h

All idle Timeout Settings are set to 30min.

**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: v.5.3.220616

**Comment by MatteoBiscosi** [comment]
Hi @ipodogrny could you please tell me your ntopng configuration?

**Comment by cardigliano** [comment]
It seems this happens when collecting flows from nProbe (I was able to reproduce it with nProbe in agente mode). It seems flows expire too early.

**Comment by MatteoBiscosi** [comment]
Hi @ipodogrny the issue should be fixed, however note that the flow idle timeout preference works only for packet interfaces
![Screenshot from 2022-06-17 15-54-19](https://user-images.githubusercontent.com/49585191/174333937-fef8f428-57fe-44a2-8d47-dc62426f1260.png)

To change the flow idle timeout from ZMQ interfaces, you have to add `-d <num_sec>` option to nProbe (e.g. `-d 120`).
In ntopng those flows will be purged after the double of `-d` nProbe's option

**Comment by cardigliano** [comment]
I confirm live flows are no longer purged immediately now for me. @ipodogrny please reopen in case you are still experiencing the issue.

**Comment by takenek** [comment]
Hey i got same problem right now.
This flow cannot be found. Very likely it is expired and ntopng has purged it from memory. You can set purge idle timeout settings from the [ Preferences]

Cache settings:
Idle Local Hosts Cache - enable
Local Hosts Cache Duration - 12h
Active Local Hosts Cache - enable
Active Local Host Cache Interval - 12h
Flow Idle Timeout - 30 min
Local Host Idle Timeout - 30 min
Remote Host Idle Timeout - 30min

I got professional license.

OS: Debian 11
ntopng version: 5.4.221223-19100

Best Regards
Marek
