### ISSUE TITLE
Attempt to index a nil value in lua_utils.lua

### ISSUE THREAD

**Issue by Hedders** [ntop/ntopng#6713]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision:  5.3.220618-17902

**What happened**:

Since updating to the above version, attempting to access any part of the web interface results in the following:

HTTP/1.1 302 Found Server: ntopng 5.3.220618 (x86_64) Set-Cookie: session=e793a6618b37b1bb795ea819b28e863a; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.178.250%3A3000%2F&error_message=%2Fusr%2Fshare%2Fntopng%2Fscripts%2Flua%2Fmodules%2Flua_utils.lua%3A4398%3A%20attempt%20to%20index%20a%20nil%20value%20%28local%20%27info%27%29 /usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a nil value (local 'info') 

**What did you expect to happen?**

The relevant panel of the web interface to be displayed.

**How did you reproduce it?**

Log in to the web interface and/or attempt to visit any screen of the web interface.

**Debug Information**:

● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-06-18 06:16:21 UTC; 11min ago
    Process: 13114 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 13128 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 13130 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 13132 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 13134 (2/flow_checks)
      Tasks: 26 (limit: 9278)
     Memory: 168.2M
        CPU: 54.479s
     CGroup: /system.slice/ntopng.service
             └─13134 /usr/bin/ntopng /run/ntopng.conf

Jun 18 06:16:23 ubuntu-lenovo ntopng[13134]: 18/Jun/2022 06:16:23 [startup.lua:216] Completed startup.lua
Jun 18 06:16:23 ubuntu-lenovo ntopng[13134]: 18/Jun/2022 06:16:23 [PeriodicActivities.cpp:167] Found 10 activities
Jun 18 06:16:23 ubuntu-lenovo ntopng[13134]: Unknown rule 'tcp'
Jun 18 06:16:23 ubuntu-lenovo ntopng[13134]: 18/Jun/2022 06:16:23 [NetworkInterface.cpp:3236] Started packet polling on interface eno1 [id: 2]...
Jun 18 06:16:36 ubuntu-lenovo ntopng[13134]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/index.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a n>
Jun 18 06:16:36 ubuntu-lenovo ntopng[13134]: 18/Jun/2022 06:16:36 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/index.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398:>
Jun 18 06:18:29 ubuntu-lenovo ntopng[13134]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/about.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a n>
Jun 18 06:18:29 ubuntu-lenovo ntopng[13134]: 18/Jun/2022 06:18:29 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/about.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398:>
Jun 18 06:24:07 ubuntu-lenovo ntopng[13134]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/index.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a n>
Jun 18 06:24:07 ubuntu-lenovo ntopng[13134]: 18/Jun/2022 06:24:07 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/index.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398:>

![screenshot](https://user-images.githubusercontent.com/5206915/174425864-abec122d-7cee-402a-bfbf-34cb228dbed6.png)

**Comment by MatteoBiscosi** [comment]
Hi @Hedders could you please update to the latest version? It's probably fixed in the latest one. Otherwise let me know

**Comment by Hedders** [comment]
Hi @MatteoBiscosi thanks for the quick response.  I've updated to version 5.3.220620-17904 and unfortunately the issue persists.

**Comment by MatteoBiscosi** [comment]
could you please share your `ntopng --version` output? in which pages this error appears? cause i'm not able to reproduce it.

**Comment by Hedders** [comment]
Sure.  It appears on all pages of the web interface, except hosts_geomap.lua for some reason.  output of ntopng --version:

Version:        5.3.220620 [Enterprise/Professional build]
GIT rev:        dev:8a001e56cb205b4124ee5e353cc7b0e4b96eab4e:20220620
Pro rev:        r5102
Built on:       Ubuntu 22.04 LTS
System Id:      L6DB806129206AAF2--U6DB80612601612D8--OL
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [Empty license file]
Validity:       Until Mon Jun 20 09:37:43 2022

**Comment by urbantao** [comment]
Same issue after upgrade last week. from noptng logs:
[LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/monitor/active_monitoring_monitor.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a nil value (local 'info')]

from webinterface : 
HTTP/1.1 302 Found Server: ntopng 5.3.220620 (x86_64) Set-Cookie: session=6a96b82e98d0417bb0b8e693dbcd2c65; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=10.10.6.100%3A3000%2F&error_message=%2Fusr%2Fshare%2Fntopng%2Fscripts%2Flua%2Fmodules%2Flua_utils.lua%3A4398%3A%20attempt%20to%20index%20a%20nil%20value%20%28local%20%27info%27%29 /usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a nil value (local 'info') 

I'm using community edition. (--community in conf file)

seems like if I start ntop like that : /usr/bin/ntopng /etc/ntopng/ntopng.conf it's ok, but some category missing in flows (malware)

**Comment by urbantao** [comment]
in reply to my previous post : all seems ok but not. Can't go into manage configuration menu. same error.

**Comment by MatteoBiscosi** [comment]
Hi @Hedders please add the `--community` option to the configuration file, restart ntopng and everything should work again fine.
Please let me know

**Comment by Hedders** [comment]
> Hi @Hedders please add the `--community` option to the configuration file, restart ntopng and everything should work again fine. Please let me know

The --community option is already set in my configuration file.

**Comment by urbantao** [comment]
got it in my ntopng.conf file : 
-G=/var/run/ntopng.pid
--community
-i=eno1


 Can you confirm me the system script ? : 

[Unit]
Description=ntopng high-speed web-based traffic monitoring and analysis tool
After=network.target syslog.target redis.service pf_ring.service cluster.service mysql.service
Requires=
Wants=redis.service pf_ring.service cluster.service
PartOf=redis.service pf_ring.service cluster.service

[Service]
Type=simple

ExecStartPre=/bin/sh -c '/usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true'
ExecStartPre=/bin/sh -c '/bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw'
ExecStartPre=/bin/sh -c '/bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true'
ExecStartPre=/bin/sh -c '/bin/sed "/^[ ]*-e.*$\\|^[ ]*-G.*\\|^[ ]*--daemon.*\\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf'

ExecStart=/usr/bin/ntopng /run/ntopng.conf.raw

ExecStopPost=-/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
Alias=

**Comment by MatteoBiscosi** [comment]
I added a check on the null value. Please update in a couple of hours and let me know.
Sorry for the inconvenience but i'm unable to reproduce your behavior

**Comment by Hedders** [comment]
> I added a check on the null value. Please update in a couple of hours and let me know. Sorry for the inconvenience but i'm unable to reproduce your behavior

I will do that and report back.  Thank you.  And no need to apologise - you're being incredibly helpful.

**Comment by urbantao** [comment]
will give you a feed back tomorrow. And I agree with hedders no apologise needed

**Comment by Hedders** [comment]
@MatteoBiscosi I've updated and can confirm it seems to be fixed.  Thank you!

**Comment by urbantao** [comment]
I tried the update but I got some dependencies issue : 

Error: Package: cento-1.17.220620-753.x86_64 (@ntop)
           Requires: pfring = 8.1.0-7555
           Removing: pfring-8.1.0-7555.x86_64 (@ntop)
               pfring = 8.1.0-7555
           Updated By: pfring-8.1.0-7556.x86_64 (ntop)
               pfring = 8.1.0-7556
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

I'm on CentOS Linux release 7.9.2009

**Comment by urbantao** [comment]
I tried a new yum update this morning, and it was ok. Ntopng work again. So really thx !!!! Just 1 little thing, got my malware category empty ... I'm going to check why but if you got an idea ?

**Comment by urbantao** [comment]
and still got an error on the mange configuration page :+1: 
HTTP/1.1 302 Found Server: ntopng 5.3.220621 (x86_64) Set-Cookie: session=e7b420840212208e89400de2523978ae; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=10.10.6.100%3A3000%2Flua%2Fadmin%2Fmanage_configurations.lua&error_message=%5Bstring%20%22context%3D...%20or%20%7B%7D...%22%5D%3A132%3A%20attempt%20to%20index%20a%20nil%20value%20%28global%20%27info%27%29 [string "context=... or {}..."]:132: attempt to index a nil value (global 'info')

**Comment by Hedders** [comment]
Actually, I can confirm that error on the Manage Configurations page:

HTTP/1.1 302 Found Server: ntopng 5.3.220621 (x86_64) Set-Cookie: session=5f94cdeab8b010f207be649a8ed0f729; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.178.250%3A3000%2Flua%2Fadmin%2Fmanage_configurations.lua&error_message=%5Bstring%20%22context%3D...%20or%20%7B%7D...%22%5D%3A132%3A%20attempt%20to%20index%20a%20nil%20value%20%28global%20%27info%27%29 [string "context=... or {}..."]:132: attempt to index a nil value (global 'info') 

Perhaps the fix applied to lua_utils.lua also needs applying to http_status_code.lua?

**Comment by closertotheedge** [comment]
Same here (ntopng with raspi4).

**Comment by urbantao** [comment]
I did some updates to my malware category and it's ok. Just to resume, only the manage configuration page is nok. One more time, thx for the work !!!! now I can have an eye on my internet flows !!!! you did the job really fast !! :+1:

**Comment by MatteoBiscosi** [comment]
hello everyone, please update to the latest ntopng version and even the configuration page should be fixed.
Thanks everyone for your help and updates

**Comment by closertotheedge** [comment]
I upgraded (via apt-get) to latest available version (raspi4, raspbian) but error still exists:

HTTP/1.1 302 Found Server: ntopng 5.3.220619 (armv7l) Set-Cookie: session=6...; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.?.?%3A3000%2Flua%2Fflows_stats.lua&error_message=%2Fusr%2Fshare%2Fntopng%2Fscripts%2Flua%2Fmodules%2Flua_utils.lua%3A4398%3A%20attempt%20to%20index%20a%20nil%20value%20%28local%20%27info%27%29 /usr/share/ntopng/scripts/lua/modules/lua_utils.lua:4398: attempt to index a nil value (local 'info')
