### ISSUE TITLE
NPROBE not find installing NTOPNG on Raspberry PI 4.

### ISSUE THREAD

**Issue by txurrispo** [ntop/ntopng#6795]
Hi!!!

I have a problem triying to install NTOP on a Raspberry PI 4 Bullseye, updated to 27/07/2022

When I try to do the install from the instructions :
wget https://packages.ntop.org/RaspberryPI/apt-ntop_1.0.190416-469_all.deb
sudo dpkg -i apt-ntop_1.0.190416-469_all.deb
sudo apt-get update

sudo apt-get install ntopng nprobe n2n

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Thanks!!!
Regards.

**Comment by lucaderi** [comment]
Please do apt-get update first and try again

**Comment by txurrispo** [comment]
> Please do apt-get update first and try again

Thanks for the answer.

$ sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:3 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease
Hit:4 https://packages.ntop.org/apt/bullseye_pi all/ InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

$ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nprobe

No luck :(

I see the NPROBE package on https://packages.ntop.org/apt/bullseye_pi/armhf/ but not on https://packages.ntop.org/apt/bullseye_pi/all/  
Could this cause the error? I´m not very experienced with debian respositories.

**Comment by txurrispo** [comment]
Any news?

**Comment by txurrispo** [comment]
Hi!!!!

Today not find NPROBE and not find NTOPNG

$  sudo apt update
Get:1 https://packages.ntop.org/apt/bullseye_pi all/ InRelease [2,153 B]
Get:2 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease [2,155 B]
Get:3 https://packages.ntop.org/apt/bullseye_pi all/ Packages [449 B]
Get:4 https://packages.ntop.org/apt/bullseye_pi armhf/ Packages [1,614 B]
Get:5 http://archive.raspberrypi.org/debian bullseye InRelease [23.7 kB]
Get:6 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:7 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:8 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [295 kB]
Fetched 13.6 MB in 9s (1,535 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

$ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe


Thanks!!
Best Regards.

**Comment by txurrispo** [comment]
HI @cardigliano 

Whi is closed? today doesnt work too??
It not the same error than the https://github.com/ntop/ntopng/issues/6804.....

Regards.

**Comment by cardigliano** [comment]
@txurrispo this is not closed, it's some issue related to the bullseye_pi/armhf repo that we need to check as we made some change with the repo due to the GPG keys change

**Comment by txurrispo** [comment]
Ok, thanks for all your work!!!!!

**Comment by FumiyukiKato** [comment]
I got the same problem on newer version `https://packages.ntop.org/RaspberryPI/apt-ntop.deb` update at 2022/08/02.

**Comment by tramsach** [comment]
same problem here

`
xxx@rpi:~ $ sudo apt-get update 
Hit:1 http://download.zerotier.com/debian/bullseye bullseye InRelease
Hit:2 http://mirror.freedif.org/Raspbian/raspbian bullseye InRelease                                       
Get:3 https://download.docker.com/linux/raspbian bullseye InRelease [26.7 kB]                              
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease                                             
Hit:5 http://raspbian.raspberrypi.org/raspbian bullseye InRelease                                
Get:6 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease [2,155 B] 
Get:7 https://packages.ntop.org/apt/bullseye_pi all/ InRelease [2,153 B]
Get:8 https://packages.ntop.org/apt/bullseye_pi all/ Packages [447 B]
Fetched 31.4 kB in 2s (14.9 kB/s) 
Reading package lists... Done
xxx@rpi:~ $ sudo apt-get install ntopng nprobe n2n -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe
`

**Comment by txurrispo** [comment]
First, thanks Luca and all the team for the work.

Checked today, and the same problem. 

pi@raspberrypi:~ $ wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2022-08-30 12:28:42--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/x-debian-package]
Saving to: ‘apt-ntop.deb’

apt-ntop.deb             100%[==================================>]   3.15K  --.-KB/s    in 0s

2022-08-30 12:28:43 (17.9 MB/s) - ‘apt-ntop.deb’ saved [3226/3226]


pi@raspberrypi:~ $ sudo dpkg -i apt-ntop.deb
Selecting previously unselected package apt-ntop.
(Reading database ... 41822 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) ...
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: keybox '/usr/share/keyrings/ntop-archive-keyring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 3D84C955924F7599: public key "Luca Deri <deri@ntop.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1


pi@raspberrypi:~ $ sudo apt-get update
Get:1 http://archive.raspberrypi.org/debian bullseye InRelease [23.7 kB]
Get:2 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease [2,155 B]
Get:3 https://packages.ntop.org/apt/bullseye_pi all/ InRelease [2,153 B]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [295 kB]
Get:5 https://packages.ntop.org/apt/bullseye_pi all/ Packages [448 B]
Hit:6 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Fetched 323 kB in 5s (68.9 kB/s) 
Reading package lists... Done


pi@raspberrypi:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe

**Comment by cardigliano** [comment]
@txurrispo it seems you are running RPi 3, we currently support Buster on that hw. Bullseye is supported on RPi 4.

**Comment by txurrispo** [comment]
> @txurrispo it seems you are running RPi 3, we currently support Buster on that hw. Bullseye is supported on RPi 4.

No its a Bullseye RPi4, if you se the repositories are bullseye

**Comment by cardigliano** [comment]
You are running an armhf Debian then, we support arm64 on RPi4

**Comment by txurrispo** [comment]
Yes you are right. Its a RPi4, but with Rapsberry Pi OS lite 32bits Bullseye. Im checking some things...

Formated and Installed with Rapsberry Pi OS lite 64bits Bullseye. Updated to today.

Same procedure for install that are on the web page  https://packages.ntop.org/

pi@raspberrypi:~ $ wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2022-08-30 14:42:53--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/x-debian-package]
Saving to: ‘apt-ntop.deb’

apt-ntop.deb             100%[==================================>]   3.15K  --.-KB/s    in 0s

2022-08-30 14:42:54 (28.9 MB/s) - ‘apt-ntop.deb’ saved [3226/3226]

pi@raspberrypi:~ $ sudo dpkg -i apt-ntop.deb
Selecting previously unselected package apt-ntop.
(Reading database ... 35797 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) ...
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: keybox '/usr/share/keyrings/ntop-archive-keyring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 3D84C955924F7599: public key "Luca Deri <deri@ntop.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1


pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Get:5 https://packages.ntop.org/apt/bullseye_pi arm64/ InRelease [2,165 B]
Get:6 https://packages.ntop.org/apt/bullseye_pi all/ InRelease [2,153 B]
Get:7 https://packages.ntop.org/apt/bullseye_pi arm64/ Packages [1,835 B]
Get:8 https://packages.ntop.org/apt/bullseye_pi all/ Packages [448 B]
Fetched 6,601 B in 2s (4,181 B/s)
Reading package lists... Done


pi@raspberrypi:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nprobe : Depends: pfring (= 8.3.0-7762) but it is not installable
E: Unable to correct problems, you have held broken packages.
pi@raspberrypi:~ $

**Comment by cardigliano** [comment]
@txurrispo I pushed a repo update, please try now

**Comment by txurrispo** [comment]
> @txurrispo I pushed a repo update, please try now

I think isd working!, thanks!!!!!!!!!

**Comment by sascha224** [comment]
Closed, but not solved... Same problem here: "Package 'ntopng' has no installation candidate" on Raspbian 11.5 Bullseye 64bit @Raspi4

**Comment by MaxG4** [comment]
I'm seeing the same issue as noted above, despite is being 'resolved'.

admin@raspberrypi:~ $ date
Tue 20 Dec 2022 11:45:45 AM PST
admin@raspberrypi:~ $ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:3 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease
Hit:4 https://packages.ntop.org/apt/bullseye_pi all/ InRelease
Reading package lists... Done
admin@raspberrypi:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe

**Comment by dapize** [comment]
same problem here :/, not solution yet


```
danielpz@pibox:~ $ sudo apt install ./apt-ntop.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'apt-ntop' instead of './apt-ntop.deb'
The following NEW packages will be installed:
  apt-ntop
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3,226 B of archives.
After this operation, 10.2 kB of additional disk space will be used.
Get:1 /home/danielpz/apt-ntop.deb apt-ntop all 2.9-16 [3,226 B]
Selecting previously unselected package apt-ntop.
(Reading database ... 44374 files and directories currently installed.)
Preparing to unpack /home/danielpz/apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) ...
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: keybox '/usr/share/keyrings/ntop-archive-keyring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 3D84C955924F7599: public key "Luca Deri <deri@ntop.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
danielpz@pibox:~ $ sudo apt install ntopong nprobe n2n -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ntopong
E: Unable to locate package nprobe

danielpz@pibox:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe

danielpz@pibox:~ $ sudo apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://archive.raspberrypi.org/debian bullseye InRelease [23.6 kB]
Get:5 http://archive.raspberrypi.org/debian bullseye/main arm64 Packages [302 kB]
Get:6 https://packages.ntop.org/apt/bullseye_pi arm64/ InRelease [2,165 B]
Hit:7 https://deb.nodesource.com/node_18.x bullseye InRelease
Get:8 https://packages.ntop.org/apt/bullseye_pi all/ InRelease [2,153 B]
Get:9 https://packages.ntop.org/apt/bullseye_pi arm64/ Packages [1,821 B]
Get:10 https://packages.ntop.org/apt/bullseye_pi all/ Packages [448 B]
Get:11 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [311 kB]
Fetched 735 kB in 2s (325 kB/s)
Reading package lists... Done

danielpz@pibox:~ $ sudo apt install ntopong nprobe n2n -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ntopong

```

**Comment by II-II-II-II** [comment]
I can confirm that ntop is still not available on the newest version of bullseye

**Comment by yaz29** [comment]
same problem here!

sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe

**Comment by isibley765** [comment]
### My steps
I'm following these commands [from the site](https://packages.ntop.org/RaspberryPI/) (same as everyone above?):
```
sudo apt update; sudo apt upgrade
wget http://packages.ntop.org/RaspberryPI/apt-ntop.deb
sudo dpkg -i apt-ntop.deb
sudo apt-get install ntopng nprobe n2n
```
And I get the same output from the last install command:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe
```

## Finding?
After tinkering with the `.list` file, and confirming it looked right (I think? New dive for me), I eventually ran another `sudo apt update`...
And then `sudo apt-get install ntopng nprobe n2n` seemed to start to to work.

## Potential Fix (please recreate & confirm):
If we configured the downloads properly in the `.list` file, but then didn't update `apt-get` with it, that might be the missing piece here?
Maybe the steps just need an update before the final `apt install`:
```
# update & upgrade to start if you want
wget http://packages.ntop.org/RaspberryPI/apt-ntop.deb
sudo dpkg -i apt-ntop.deb
sudo apt update
sudo apt-get install ntopng nprobe n2n
```

**Comment by TheNazzi89** [comment]
After more than 8 months, still getting the same error on arm64 on RPi4

`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe`

I have tried all the solutions mentioned above. But no success.

**Comment by 24inch** [comment]
> ### My steps
> I'm following these commands [from the site](https://packages.ntop.org/RaspberryPI/) (same as everyone above?):
> 
> ```
> sudo apt update; sudo apt upgrade
> wget http://packages.ntop.org/RaspberryPI/apt-ntop.deb
> sudo dpkg -i apt-ntop.deb
> sudo apt-get install ntopng nprobe n2n
> ```
> 
> And I get the same output from the last install command:
> 
> ```
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Package ntopng is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'ntopng' has no installation candidate
> E: Unable to locate package nprobe
> ```
> 
> ## Finding?
> After tinkering with the `.list` file, and confirming it looked right (I think? New dive for me), I eventually ran another `sudo apt update`... And then `sudo apt-get install ntopng nprobe n2n` seemed to start to to work.
> 
> ## Potential Fix (please recreate & confirm):
> If we configured the downloads properly in the `.list` file, but then didn't update `apt-get` with it, that might be the missing piece here? Maybe the steps just need an update before the final `apt install`:
> 
> ```
> # update & upgrade to start if you want
> wget http://packages.ntop.org/RaspberryPI/apt-ntop.deb
> sudo dpkg -i apt-ntop.deb
> sudo apt update
> sudo apt-get install ntopng nprobe n2n
> ```

This one worked, thank you!!!

**Comment by jfonte** [comment]
Hi there everyone. Any chance we could get a fix for Raspbian bookworm?
`Hit:1 http://raspbian.raspberrypi.com/raspbian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
Ign:3 https://packages.ntop.org/apt/bookworm_pi armhf/ InRelease
Hit:4 https://packages.ntop.org/apt/bookworm_pi all/ InRelease
Err:5 https://packages.ntop.org/apt/bookworm_pi armhf/ Release
  404  Not Found [IP: 167.99.215.164 443]
Reading package lists... Done
E: The repository 'https://packages.ntop.org/apt/bookworm_pi armhf/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by bernhardberg** [comment]
Hi together,
I´m sorry to reopen that topic....but I have the same problem again.

Started with a fresh RPI 3 setup - RaspberryPi OS 32 bit (Legacy) - did all the steps mentioned:

```
sudo apt-get update
sudo apt-get upgrade
wget http://packages.ntop.org/RaspberryPI/apt-ntop.deb
sudo dpkg -i apt-ntop.deb
sudo apt update
sudo apt-get install ntopng nprobe n2n
```

and run into the same problem:

```
xxx@yyyy:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe
```

What did I miss?

**Comment by KayhanKaynar** [comment]
Having the same problem..

**Comment by EstebanVargas10** [comment]
Same issue

**Comment by OndrejVrto** [comment]
Same issue

**Comment by doigtscarres** [comment]
Same issue.... still no package available for Raspberry pi.

Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe

**Comment by user32983** [comment]
Same issue:

`openrangepi@openrangepi:~ $ sudo apt-get install ntopng                                                                 Reading package lists... Done                                                                                           Building dependency tree... Done                                                                                        Reading state information... Done                                                                                       Package ntopng is not available, but is referred to by another package.                                                 This may mean that the package is missing, has been obsoleted, or                                                       is only available from another source                                                                                   However the following packages replace it:                                                                                ntopng-data                                                                                                                                                                                                                                   E: Package 'ntopng' has no installation candidate   `

**Comment by user32983** [comment]
Update: I reinstalled my Raspberry Pi's OS, this time choosing the 64-bit version of Raspbian OS lite, and it worked!
