### ISSUE TITLE
custom category name wasn't shown under host > app > category tab > table

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6803]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: 5.5.220729

**What happened**:
The original name of the 'user custom category x' is shown under host > app > category tab > table.

**How did you reproduce it?**
Anytime. 'Restarting ntopng' doesn't help.

**Debug Information**:
![host-app-category-tab-table](https://user-images.githubusercontent.com/50309519/181689738-88e9aa9a-c86c-46f7-a817-52768408f261.jpg)

**Comment by MatteoBiscosi** [comment]
Hi @61swong, like usual thanks for your reports. A new build should be available in a couple of hours, please update after that and let me know, the issue should be fixed

**Comment by 61swong** [comment]
Hi @MatteoBiscosi, following the upgrade to the latest release, I found the issue still exists. Please see attached the screenshot.

![host-app-category_tab-table](https://user-images.githubusercontent.com/50309519/182290679-61867807-3cdd-45c3-971f-d55496dd2cb4.png)

**Comment by MatteoBiscosi** [comment]
Could you please try to update again? Has you can see, the label should be right now (Custom Test is custom category 2, but renamed)
![image](https://user-images.githubusercontent.com/49585191/182425490-e9c64d4a-46a8-47bf-ab32-0eedc07757f6.png)
![image](https://user-images.githubusercontent.com/49585191/182425829-13f329a2-c362-4986-ab9b-19bd28eb6735.png)

**Comment by 61swong** [comment]
Hi @MatteoBiscosi I tried to run the 'check for update' via the web gui and it didn't update for me. Finally I updated the package via command line and have it (ntopng Enterprise M v.5.5.220802 rev.18189) running. When I browsed a host > app > category tab, the table still shows the original name instead of the new name. I restarted the service a few times and it is still the same. Please let me know if you need more information for the troubleshooting.

**Comment by 61swong** [comment]
Hi @MatteoBiscosi I updated ntopng to v.5.5.220804 rev.18199 and the issue still exists.
![host-app-category_tab-table](https://user-images.githubusercontent.com/50309519/182767191-af10c746-b631-4dde-b47e-bf2b4fa33ad9.png)

**Comment by MatteoBiscosi** [comment]
Hi @61swong can you find the user custom category 1 and 3 name in the category list?
![Screenshot from 2022-08-23 14-40-49](https://user-images.githubusercontent.com/49585191/186160635-a35d3b21-19d3-41de-94f9-7aa015ed238b.png)
If yes, then please edit them and rename them.
Please let me know

**Comment by 61swong** [comment]
Hi @MatteoBiscosi 

I just updated the ntopng to v5.5.220824, renamed those categories to 'User custom category x' (note: I forget which one was 'User custom category 1', .... so I just renamed them in the order they were shown in the list to 'User custom category 1', 'User custom category 2',... and then back to my own names. Then I restarted ntopng. I chose one of the top local talkers for one of the interfaces, went to the app and selected the 'category' view. In the table, it still shows the 'User custom category x'.

Is there a way for me to reset the category list if it works in your dev in the new build?

Thanks.

**Comment by MatteoBiscosi** [comment]
Hi @61swong, could you please run this command in the terminal? 
![image](https://user-images.githubusercontent.com/49585191/187182429-4a9dc721-6fa8-40c6-b55a-69e69fe2fab5.png)
Here you should have all the custom category names you set up.
To remove them and reset them to the default naming you have to run `redis-cli HDEL ntopng.prefs.category_name "ID_OF_THE_CATEGORY"`
![image](https://user-images.githubusercontent.com/49585191/187183096-f9fb963e-f08a-4981-ad88-d6f468a0ee0f.png)

To remove them the only way is to reset the entire ntopng configuration, so I don't suggest doing it, I prefer trying to understand why in your case it doesn't work properly, instead in my case it works perfectly

**Comment by 61swong** [comment]
Hi @MatteoBiscosi , I have followed your commands to remove them.
`[root@host ~]# redis-cli HGETALL ntopng.prefs.category_name
 1) "20"
 2) "corp data"
 3) "21"
 4) "corp biz high pri"
 5) "22"
 6) "corp infra ops"
 7) "23"
 8) "corp infra mon"
 9) "24"
10) "corp biz low pri"
[root@host ~]# redis-cli HDEL ntopng.prefs.category_name "20"
(integer) 1
[root@host ~]# redis-cli HDEL ntopng.prefs.category_name "21"
(integer) 1
[root@host ~]# redis-cli HDEL ntopng.prefs.category_name "22"
(integer) 1
[root@host ~]# redis-cli HDEL ntopng.prefs.category_name "23"
(integer) 1
[root@host ~]# redis-cli HDEL ntopng.prefs.category_name "24"
(integer) 1
[root@host ~]# redis-cli HGETALL ntopng.prefs.category_name
(empty list or set)
[root@host ~]#
`
I restarted ntopng service and redid all the changes to the custom category names.
Browsed to a host > app, then changed to 'Categories' tab, the pie chart showed the custom name correctly but the original names in the table.

REDIS output following the changes.

`[root@host ~]# redis-cli HGETALL ntopng.prefs.category_name
 1) "20"
 2) "corp biz high pri"
 3) "21"
 4) "corp biz low pri"
 5) "22"
 6) "corp data"
 7) "23"
 8) "corp infra ops"
 9) "24"
10) "corp infra mon"
`

Remark: I'm running v.5.5.220830.

**Comment by MatteoBiscosi** [comment]
Hi @61swong ii reworked the whole page, now each category label should be the right one, in a couple of hours a new build should be available. Please update and let me know

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed

**Comment by 61swong** [comment]
Thanks @MatteoBiscosi. It's working for me. Cheers.
