### ISSUE TITLE
Error while calling historical flow API  <DB::Exception: Syntax error: failed at position 144 ('10'): 10  . Expected>

### ISSUE THREAD

**Issue by midoelhawy** [ntop/ntopng#6880]
**Environment**:
* OS name: **Ubuntu server** 
* OS version:**22.04**
* Docker version: **20.10.18**
* Architecture: **x86_64**
* clickhouse-server: **latest**
* clickhouse-client: **22.8.5.29**
* ntopng version/revision: **5.4.220913 [Enterprise/Professional build]**
* GIT rev:	**5.4-stable:ede2eeb11f6ec2dc445caee2f852c49ffded8c27:20220913**

**What happened**:
I can't get historical flows by the API  `/lua/pro/rest/v2/get/db/flows.lua`
server response with this error `...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:925: bad argument #1 to 'for iterator' (table expected, got nil)`

Container log : 

```
2022-09-14T10:18:27.432851222Z 14/Sep/2022 10:18:27 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://127.0.0.1:5556
2022-09-14T10:18:27.434983977Z 14/Sep/2022 10:18:27 [MySQLDB.cpp:1046] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 34 ('10'): 10  . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.8.5.29 (official build))][1][SELECT * FROM flows   ORDER BY 0 10  ]
2022-09-14T10:18:27.435679883Z 14/Sep/2022 10:18:27 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:925: bad argument #1 to 'for iterator' (table expected, got nil)]
2022-09-14T10:18:49.089926932Z 14/Sep/2022 10:18:49 [NetworkInterface.cpp:5173] [Device IP] 0.0.0.0 / [In Idx] 0 / [Out Idx] 0
2022-09-14T10:20:37.597930255Z 14/Sep/2022 10:20:37 [MySQLDB.cpp:698] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
2022-09-14T10:20:37.599019799Z 14/Sep/2022 10:20:37 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://127.0.0.1:5556
2022-09-14T10:20:37.600932019Z 14/Sep/2022 10:20:37 [MySQLDB.cpp:1046] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 34 ('10'): 10  . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.8.5.29 (official build))][1][SELECT * FROM flows   ORDER BY 0 10  ]
2022-09-14T10:20:37.601246980Z 14/Sep/2022 10:20:37 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:925: bad argument #1 to 'for iterator' (table expected, got nil)]
2022-09-14T10:38:08.700841526Z 14/Sep/2022 10:38:08 [MySQLDB.cpp:698] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
2022-09-14T10:38:08.702167656Z 14/Sep/2022 10:38:08 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://127.0.0.1:5556
2022-09-14T10:38:08.704298393Z 14/Sep/2022 10:38:08 [MySQLDB.cpp:1046] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 96 ('10'): 10  . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.8.5.29 (official build))][1][SELECT * FROM flows WHERE (FIRST_SEEN >= 1314870540) AND (LAST_SEEN <= 1663150766)  ORDER BY 0 10  ]
2022-09-14T10:38:08.704728805Z 14/Sep/2022 10:38:08 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:925: bad argument #1 to 'for iterator' (table expected, got nil)]
2022-09-14T10:38:56.570229423Z 14/Sep/2022 10:38:56 [MySQLDB.cpp:698] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
2022-09-14T10:38:56.571949642Z 14/Sep/2022 10:38:56 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://127.0.0.1:5556
2022-09-14T10:38:56.574246573Z 14/Sep/2022 10:38:56 [MySQLDB.cpp:1046] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 144 ('10'): 10  . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.8.5.29 (official build))][1][SELECT * FROM flows WHERE IPV4_SRC_ADDR = IPv4StringToNum192.168.56.1 AND (FIRST_SEEN >= 1590480290) AND (LAST_SEEN <= 1590480590)  ORDER BY 0 10  ]
2022-09-14T10:38:56.574688685Z 14/Sep/2022 10:38:56 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:925: bad argument #1 to 'for iterator' (table expected, got nil)]
2022-09-14T10:48:46.982325215Z 14/Sep/2022 10:48:46 [NetworkInterface.cpp:5173] [Device IP] 0.0.0.0 / [In Idx] 0 / [Out Idx] 0
2022-09-14T10:48:50.634608497Z 14/Sep/2022 10:48:50 [NetworkInterface.cpp:5173] [Device IP] 0.0.0.0 / [In Idx] 0 / [Out Idx] 0
2022-09-14T12:22:45.738790459Z 14/Sep/2022 12:22:45 [MySQLDB.cpp:698] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
2022-09-14T12:22:45.740958464Z 14/Sep/2022 12:22:45 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://127.0.0.1:5556
2022-09-14T12:22:45.743145751Z 14/Sep/2022 12:22:45 [MySQLDB.cpp:1046] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 144 ('10'): 10  . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. (SYNTAX_ERROR) (version 22.8.5.29 (official build))][1][SELECT * FROM flows WHERE IPV4_SRC_ADDR = IPv4StringToNum192.168.56.1 AND (FIRST_SEEN >= 1590480290) AND (LAST_SEEN <= 1590480590)  ORDER BY 0 10  ]
2022-09-14T12:22:45.743601905Z 14/Sep/2022 12:22:45 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:925: bad argument #1 to 'for iterator' (table expected, got nil)]


```

**How did you reproduce it?**

CURL request :
```
curl -u admin:PASSWORD -H "Content-Type: application/json" -d '{"ifid": 1, "select_clause": "*", "where_clause": "IPV4_SRC_ADDR = 192.168.1.2", "begin_time_clause": 1590480290, "end_time_clause": 1690480590, "maxhits_clause": 10}' http://192.168.1.1:3000/lua/pro/rest/v2/get/db/flows.lua -v
```

**Debug Information**:

**Comment by cardigliano** [comment]
Please paste here the configuration file

**Comment by midoelhawy** [comment]
`--redis", "127.0.0.1:6379","-i","tcp://127.0.0.1:5556", "-F", "clickhouse;127.0.0.1;ntopng;USERNAME;EMPTYPASSWORD"`

**Comment by cardigliano** [comment]
@midoelhawy I pushed a fix to support your curl, a new package will be available later today or tomorrow, please also adjust the query using parenthesis and quotes when specifying IP addresses as below:

`curl -u admin:PASSWORD -H "Content-Type: application/json" -d '{"ifid": 1, "select_clause": "*", "where_clause": "IPV4_SRC_ADDR = (\"192.168.1.2\")", "begin_time_clause": 1590480290, "end_time_clause": 1690480590, "maxhits_clause": 10}' http://192.168.1.1:3000/lua/pro/rest/v2/get/db/flows.lua -v`

**Comment by midoelhawy** [comment]
I think it's still not working:

I tried to execute the same request sent by you :

```
curl -u admin:PASSWORD -H "Content-Type: application/json" -d '{"ifid": 1, "select_clause": "*", "where_clause": "IPV4_SRC_ADDR = (\"192.168.1.2\")", "begin_time_clause": 1590480290, "end_time_clause": 1690480590, "maxhits_clause": 10}' http://192.168.1.1:3000/lua/pro/rest/v2/get/db/flows.lua
```
But I got this output error

```
HTTP/1.1 302 Found
Server: ntopng 5.5.220914 (x86_64)
Set-Cookie: session=; path=/; HttpOnly; SameSite=lax
Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.128.40%3A3000%2Flua%2Fpro%2Frest%2Fv2%2Fget%2Fdb%2Fflows.lua&error_message=attempt%20to%20index%20a%20nil%20value

attempt to index a nil value
```

I have the stable docker image updated less than 4 hours ago `ntop/ntopng:stable`

![Screenshot from 2022-09-14 23-31-52](https://user-images.githubusercontent.com/27738027/190266408-6b8ebeb7-57d0-4da4-bde1-011d377861b1.png)

**Comment by cardigliano** [comment]
Could you provide the ntopng output from the container?

**Comment by midoelhawy** [comment]
```
Version:	5.5.220914 [Enterprise/Professional build]
GIT rev:	dev:d1e0bfe4eb4307745370a05a278ce1a80e036e3e:20220914
Pro rev:	r5262
Built on:	Ubuntu 20.04.4 LTS
System Id:	**************
Platform:	x86_64
Edition:	Enterprise L (Bundle)
```

**Comment by cardigliano** [comment]
I mean the full ntopng log when reproducing the API failure

**Comment by midoelhawy** [comment]
```
2022-09-15T00:01:38.945488283Z 15/Sep/2022 00:01:38 [LuaEngine.cpp:413] WARNING: Script failure [][/usr/share/ntopng/pro/scripts/lua/modules/?.lua;/usr/share/ntopng/scripts/lua/?.lua;/usr/share/ntopng/scripts/lua/modules/?.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua]
2022-09-15T00:01:38.945909804Z 15/Sep/2022 00:01:38 [LuaEngine.cpp:597] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/daily-delayed/system/assets.lua][...ng/pro/scripts/callbacks/daily-delayed/system/assets.lua:10: module 'asset_utils' not found:]
2022-09-15T08:04:38.413958574Z 15/Sep/2022 08:04:38 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]



```

**Comment by cardigliano** [comment]
@midoelhawy can I see the full log please? Did you always use the dockerhub image? It seems you were running ubuntu 22 on the first post, the dockerhub image was ubuntu 20 until yesterday

**Comment by cardigliano** [comment]
Anyway, we will update the docker hub images later today, worth to check with the latest one.

**Comment by midoelhawy** [comment]
Ubuntu 22 is the host OS.
Did you always use the dockerhub image? yes 

This is our full log :

```
2022-09-14T21:17:21.906784931Z 14/Sep/2022 21:17:21 [plugin.c:178] No plugins found in ./plugins
2022-09-14T21:17:21.906816674Z 14/Sep/2022 21:17:21 [plugin.c:186] Loading 23 plugins [.so] from /usr/lib/nprobe/plugins
2022-09-14T21:17:21.913995125Z 14/Sep/2022 21:17:21 [Prefs.cpp:1290] ntopng will use redis 127.0.0.1@0
2022-09-14T21:17:21.914760725Z 14/Sep/2022 21:17:21 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
2022-09-14T21:17:21.915422797Z 14/Sep/2022 21:17:21 [nprobe.c:5303] Valid nProbe Pro [ntopng Enterprise L License] license found
2022-09-14T21:17:21.915448328Z 14/Sep/2022 21:17:21 [nprobe.c:5853] Disabling flow cache during collection
2022-09-14T21:17:21.915753262Z 14/Sep/2022 21:17:21 [nprobe.c:7517] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
2022-09-14T21:17:21.915764184Z 14/Sep/2022 21:17:21 [nprobe.c:7520] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
2022-09-14T21:17:21.915768640Z 14/Sep/2022 21:17:21 [nprobe.c:7545] Using ZMQ sourceId 553127520
2022-09-14T21:17:21.915772816Z 14/Sep/2022 21:17:21 [nprobe.c:7616] Flow cache is disabled in flow collection mode
2022-09-14T21:17:21.915776616Z 14/Sep/2022 21:17:21 [nprobe.c:7619] Welcome to nProbe v.10.1.220914 for x86_64-pc-linux-gnu with native PF_RING acceleration
2022-09-14T21:17:21.915783191Z 14/Sep/2022 21:17:21 [nprobe.c:7641] Pro [ntopng Enterprise L License] Edition running on Ubuntu 20.04.4 LTS
2022-09-14T21:17:21.915787164Z 14/Sep/2022 21:17:21 [nprobe.c:7642] Current limits [4 ZMQ exporters][4 collector devices]
2022-09-14T21:17:21.915790980Z 14/Sep/2022 21:17:21 [nprobe.c:7653] SystemId: L139CF36EB206AB13--U139CF36E6E670A1A--OL
2022-09-14T21:17:21.916244441Z 14/Sep/2022 21:17:21 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
2022-09-14T21:17:21.916608634Z 14/Sep/2022 21:17:21 [nprobe.c:7726] Sample rate [packet: 1][flow collection/export: 1/1]
2022-09-14T21:17:21.918011460Z 14/Sep/2022 21:17:21 [nprobe.c:9705] Using template %IN_SRC_MAC %OUT_DST_MAC %INPUT_SNMP %OUTPUT_SNMP %SRC_VLAN %IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %L7_PROTO %L7_CONFIDENCE %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %CLIENT_TCP_FLAGS %SERVER_TCP_FLAGS %L7_PROTO_RISK %L7_RISK_SCORE %EXPORTER_IPV4_ADDRESS %DIRECTION %SAMPLING_INTERVAL %TOTAL_FLOWS_EXP %NPROBE_IPV4_ADDRESS %POST_NAT_SRC_IPV4_ADDR %POST_NAT_DST_IPV4_ADDR %POST_NAPT_SRC_TRANSPORT_PORT %POST_NAPT_DST_TRANSPORT_PORT
2022-09-14T21:17:21.918023646Z 14/Sep/2022 21:17:21 [nprobe.c:9707] Using NetFlow Packet Payload Len: 1472
2022-09-14T21:17:21.918481707Z 14/Sep/2022 21:17:21 [template.c:3491] WARNING: Unable to locate template 'NPROBE_IPV6_ADDRESS': Pro version does not include plugins.
2022-09-14T21:17:21.918502607Z 14/Sep/2022 21:17:21 [template.c:3491] WARNING: Unable to locate template 'POST_NAT_SRC_IPV6_ADDR': Pro version does not include plugins.
2022-09-14T21:17:21.918514333Z 14/Sep/2022 21:17:21 [template.c:3491] WARNING: Unable to locate template 'POST_NAT_DST_IPV6_ADDR': Pro version does not include plugins.
2022-09-14T21:17:21.918602020Z 14/Sep/2022 21:17:21 [template.c:3491] WARNING: Unable to locate template 'NPROBE_IPV6_ADDRESS': Pro version does not include plugins.
2022-09-14T21:17:21.918625566Z 14/Sep/2022 21:17:21 [template.c:3491] WARNING: Unable to locate template 'POST_NAT_SRC_IPV6_ADDR': Pro version does not include plugins.
2022-09-14T21:17:21.918640246Z 14/Sep/2022 21:17:21 [template.c:3491] WARNING: Unable to locate template 'POST_NAT_DST_IPV6_ADDR': Pro version does not include plugins.
2022-09-14T21:17:21.918646037Z 14/Sep/2022 21:17:21 [plugin.c:1196] 0 plugin(s) enabled
2022-09-14T21:17:21.918883313Z 14/Sep/2022 21:17:21 [nprobe.c:10248] Each flow is 132 bytes long
2022-09-14T21:17:21.918918438Z 14/Sep/2022 21:17:21 [nprobe.c:10249] The # flows per packet has been set to 10
2022-09-14T21:17:21.918932995Z 14/Sep/2022 21:17:21 [nprobe.c:10252] IP TOS is ignored
2022-09-14T21:17:21.918948203Z 14/Sep/2022 21:17:21 [nprobe.c:11020] Flow export type (-T): bidirectional flows
2022-09-14T21:17:21.918959749Z 14/Sep/2022 21:17:21 [nprobe.c:11225] Flows ASs will not be computed (no GeoDB files loaded with --as-list)
2022-09-14T21:17:21.918970566Z 14/Sep/2022 21:17:21 [nprobe.c:11257] Flows will be exported in NetFlow 9 format
2022-09-14T21:17:21.918981016Z 14/Sep/2022 21:17:21 [nprobe.c:11300] Learning the public IP address.. Disable it with --disable-startup-checks
2022-09-14T21:17:21.926859685Z 14/Sep/2022 21:17:21 [NtopPro.cpp:319] [LICENSE] Reading license from /etc/ntopng.license
2022-09-14T21:17:21.927556688Z 14/Sep/2022 21:17:21 [NtopPro.cpp:507] [LICENSE] /etc/ntopng.license: found valid Enterprise L (Bundle) license
2022-09-14T21:17:21.928180315Z 14/Sep/2022 21:17:21 [NtopPro.cpp:570] WARNING: [LICENSE] Your license will expire on Tue Sep 20 12:55:23 2022
2022-09-14T21:17:22.060301819Z 14/Sep/2022 21:17:22 [util.c:6293] Initializing ZMQ as server
2022-09-14T21:17:22.060771125Z 14/Sep/2022 21:17:22 [util.c:6372] Successfully created ZMQ endpoint tcp://*:5556 with sourceId: 553127520
2022-09-14T21:17:22.060795922Z 14/Sep/2022 21:17:22 [nprobe.c:11474] Not capturing packet from interface (collector mode)
2022-09-14T21:17:22.061995822Z sh: 1: cannot create /proc/sys/net/core/rmem_max: Read-only file system
2022-09-14T21:17:22.062055311Z 14/Sep/2022 21:17:22 [util.c:5133] Enlarged socket buffer [echo 8388608 > /proc/sys/net/core/rmem_max]
2022-09-14T21:17:22.062466361Z 14/Sep/2022 21:17:22 [util.c:5188] nProbe changed user to 'nprobe'
2022-09-14T21:17:22.116785019Z 14/Sep/2022 21:17:22 [collect.c:246] Flow collector listening on port 2055 (IPv4/v6)
2022-09-14T21:17:22.117076854Z 14/Sep/2022 21:17:22 [export.c:567] Using TLV as serialization format
2022-09-14T21:17:22.117120007Z 14/Sep/2022 21:17:22 [nprobe.c:11766] nProbe started successfully
2022-09-14T21:17:22.507988194Z 14/Sep/2022 21:17:22 [Ntop.cpp:2584] Registered interface tcp://127.0.0.1:5556 [id: 1]
2022-09-14T21:17:22.508316195Z 14/Sep/2022 21:17:22 [main.cpp:344] PID stored in file /var/run/ntopng.pid
2022-09-14T21:17:22.508736071Z 14/Sep/2022 21:17:22 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
2022-09-14T21:17:22.509058944Z 14/Sep/2022 21:17:22 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
2022-09-14T21:17:22.509224305Z 14/Sep/2022 21:17:22 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
2022-09-14T21:17:22.600045170Z 14/Sep/2022 21:17:22 [HTTPserver.cpp:1408] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
2022-09-14T21:17:22.600579034Z 14/Sep/2022 21:17:22 [HTTPserver.cpp:1683] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
2022-09-14T21:17:22.600855863Z 14/Sep/2022 21:17:22 [HTTPserver.cpp:1686] HTTP server listening on 3000
2022-09-14T21:17:22.601079292Z 14/Sep/2022 21:17:22 [Utils.cpp:3701] WARNING: Capabilities cap_set_proc error: Operation not permitted
2022-09-14T21:17:22.601316743Z 14/Sep/2022 21:17:22 [Utils.cpp:754] WARNING: Unable to retain privileges for privileged file writing
2022-09-14T21:17:22.602108210Z 14/Sep/2022 21:17:22 [Utils.cpp:800] User changed to ntopng
2022-09-14T21:17:22.603618488Z 14/Sep/2022 21:17:22 [NetworkInterface.cpp:3148] Started flow dump loop on interface tcp://127.0.0.1:5556 [id: 1]...
2022-09-14T21:17:22.605020516Z 14/Sep/2022 21:17:22 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ] for interface tcp://127.0.0.1:5556
2022-09-14T21:17:22.605438546Z 14/Sep/2022 21:17:22 [ClickHouseFlowDB.cpp:65] [ClickHouse] Creating Flow DB
2022-09-14T21:17:22.789600541Z 14/Sep/2022 21:17:22 [ClickHouseFlowDB.cpp:38] ClickHouse will dump into /var/lib/ntopng/tmp/clickhouse
2022-09-14T21:17:22.790119871Z 14/Sep/2022 21:17:22 [NetworkInterface.cpp:3035] Started flow user script hooks loop on interface tcp://127.0.0.1:5556 [id: 1]...
2022-09-14T21:17:22.790130728Z 14/Sep/2022 21:17:22 [NetworkInterface.cpp:3091] Started host user script hooks loop on interface tcp://127.0.0.1:5556 [id: 1]...
2022-09-14T21:17:22.791544750Z 14/Sep/2022 21:17:22 [main.cpp:414] Working directory: /var/lib/ntopng
2022-09-14T21:17:22.791971561Z 14/Sep/2022 21:17:22 [main.cpp:416] Scripts/HTML pages directory: /usr/share/ntopng
2022-09-14T21:17:22.792396985Z 14/Sep/2022 21:17:22 [Ntop.cpp:467] Welcome to ntopng x86_64 v.5.5.220914 - (C) 1998-22 ntop.org
2022-09-14T21:17:22.792812705Z 14/Sep/2022 21:17:22 [Ntop.cpp:477] Built on Ubuntu 20.04.4 LTS
2022-09-14T21:17:22.793228734Z 14/Sep/2022 21:17:22 [NtopPro.cpp:800] [LICENSE] System Id:	***************
2022-09-14T21:17:22.793709031Z 14/Sep/2022 21:17:22 [NtopPro.cpp:801] [LICENSE] Edition:	Enterprise L (Bundle)
2022-09-14T21:17:22.794106323Z 14/Sep/2022 21:17:22 [NtopPro.cpp:802] [LICENSE] License Type:	Time-Limited [License Ok] License
2022-09-14T21:17:22.796487389Z 14/Sep/2022 21:17:22 [NtopPro.cpp:816] [LICENSE] License Hash:	CDC50EBC56671686413FE91645DF578A1663678523170A512F
2022-09-14T21:17:22.797258054Z 14/Sep/2022 21:17:22 [FlowRiskAlerts.cpp:199] [!] nDPI risk 26/Risky ASN has not been defined in ntopng
2022-09-14T21:17:22.797729606Z 14/Sep/2022 21:17:22 [FlowRiskAlerts.cpp:199] [!] nDPI risk 27/Risky Domain Name has not been defined in ntopng
2022-09-14T21:17:22.800584520Z 14/Sep/2022 21:17:22 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ] for interface __system__
2022-09-14T21:17:22.826894771Z 14/Sep/2022 21:17:22 [PeriodicActivities.cpp:109] Started periodic activities loop...
2022-09-14T21:17:23.393379188Z 14/Sep/2022 21:17:23 [startup.lua:35] Processing startup.lua: please hold on...
2022-09-14T21:17:23.406333469Z 14/Sep/2022 21:17:23 [startup.lua:120] [lists_utils.lua:822] Refreshing category lists...
2022-09-14T21:17:23.889239687Z 14/Sep/2022 21:17:23 [startup.lua:120] [lists_utils.lua:411] Updating list 'Stratosphere Lab' [https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/Todays-Blacklists/AIP_historical_blacklist_prioritized_by_newest_attackers.csv]... OK
2022-09-14T21:17:24.332412745Z 14/Sep/2022 21:17:24 [startup.lua:120] [lists_utils.lua:746] Category Lists (4023 hosts, 18958 IPs, 0 JA3) loaded in 1 sec
2022-09-14T21:17:24.333857668Z 14/Sep/2022 21:17:24 [startup.lua:124] Initializing device polices...
2022-09-14T21:17:24.352435247Z 14/Sep/2022 21:17:24 [startup.lua:140] Initializing alerts...
2022-09-14T21:17:24.356777757Z 14/Sep/2022 21:17:24 [startup.lua:149] Initializing timeseries...
2022-09-14T21:17:24.361736451Z 14/Sep/2022 21:17:24 [startup.lua:207] Importing ClickHouse dumps...
2022-09-14T21:17:24.470353941Z 14/Sep/2022 21:17:24 [startup.lua:212] Fetching latest ntop blog posts...
2022-09-14T21:17:24.493665638Z 14/Sep/2022 21:17:24 [collect.c:3317] Collecting flows from 192.168.128.1 [total: 1/4]
2022-09-14T21:17:24.875942253Z 14/Sep/2022 21:17:24 [startup.lua:216] Completed startup.lua
2022-09-14T21:17:24.882719206Z 14/Sep/2022 21:17:24 [PeriodicActivities.cpp:167] Found 10 activities
2022-09-14T21:17:24.890425017Z 14/Sep/2022 21:17:24 [NetworkInterface.cpp:3257] Started packet polling on interface tcp://127.0.0.1:5556 [id: 1]...
2022-09-14T21:17:25.890447459Z 14/Sep/2022 21:17:25 [ZMQCollectorInterface.cpp:269] Collecting flows on tcp://127.0.0.1:5556
2022-09-14T21:17:36.501574312Z 14/Sep/2022 21:17:36 [collect.c:1786] Added new flow template definition [id=5206][flow_version=9][netflow_device=192.168.128.1:5557][observation_domain_id=0][total=1]
2022-09-14T21:20:03.811448577Z 14/Sep/2022 21:20:03 [LuaEngineNtop.cpp:45] ERROR: ntop_get_ndpi_protocol_name : expected number[@pos 1], got nil
2022-09-14T21:22:37.822854293Z 14/Sep/2022 21:22:37 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:23:02.097076476Z 14/Sep/2022 21:23:02 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:23:29.352505287Z 14/Sep/2022 21:23:29 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:24:14.650522729Z 14/Sep/2022 21:24:14 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:24:20.906519875Z 14/Sep/2022 21:24:20 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:25:13.369656029Z 14/Sep/2022 21:25:13 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:27:21.941260240Z 14/Sep/2022 21:27:21 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-14T21:27:36.925066679Z 14/Sep/2022 21:27:36 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]
2022-09-15T00:01:33.359065641Z 15/Sep/2022 00:01:33 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
2022-09-15T00:01:34.035976664Z 15/Sep/2022 00:01:34 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
2022-09-15T00:01:34.249199266Z 15/Sep/2022 00:01:34 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Feodo' [https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt]... OK
2022-09-15T00:01:34.436114646Z 15/Sep/2022 00:01:34 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
2022-09-15T00:01:34.598289977Z 15/Sep/2022 00:01:34 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
2022-09-15T00:01:34.812964887Z 15/Sep/2022 00:01:34 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
2022-09-15T00:01:35.345081508Z 15/Sep/2022 00:01:35 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Stratosphere Lab' [https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/Todays-Blacklists/AIP_historical_blacklist_prioritized_by_newest_attackers.csv]... OK
2022-09-15T00:01:35.580580858Z 15/Sep/2022 00:01:35 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'ThreatFox' [https://threatfox.abuse.ch/downloads/hostfile/]... OK
2022-09-15T00:01:35.769191219Z 15/Sep/2022 00:01:35 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
2022-09-15T00:01:35.877382566Z 15/Sep/2022 00:01:35 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'dshield 7 days' [https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d.netset]... OK
2022-09-15T00:01:36.323222507Z 15/Sep/2022 00:01:36 [housekeeping.lua:37] [lists_utils.lua:746] Category Lists (4071 hosts, 19162 IPs, 0 JA3) loaded in 1 sec
2022-09-15T00:01:38.945488283Z 15/Sep/2022 00:01:38 [LuaEngine.cpp:413] WARNING: Script failure [][/usr/share/ntopng/pro/scripts/lua/modules/?.lua;/usr/share/ntopng/scripts/lua/?.lua;/usr/share/ntopng/scripts/lua/modules/?.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua]
2022-09-15T00:01:38.945909804Z 15/Sep/2022 00:01:38 [LuaEngine.cpp:597] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/daily-delayed/system/assets.lua][...ng/pro/scripts/callbacks/daily-delayed/system/assets.lua:10: module 'asset_utils' not found:]
2022-09-15T08:04:38.413958574Z 15/Sep/2022 08:04:38 [LuaEngine.cpp:1293] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/flows.lua][attempt to index a nil value]


```

**Comment by cardigliano** [comment]
This has been addressed today, a new build will be available soon

**Comment by cardigliano** [comment]
@midoelhawy please try rebuilding your container using the dockerhub image now nad let me know

**Comment by midoelhawy** [comment]
Now it's works;
Thank you

**Comment by midoelhawy** [comment]
Grate, thank you.
What about the timestamp problem?
All historical flows has timestamp (from live) has old datetime (for
example 29-07-2022)

Il mer 14 set 2022, 18:43 Alfredo Cardigliano ***@***.***> ha
scritto:
