### ISSUE TITLE
Impossible to login on Chrome

### ISSUE THREAD

**Issue by ThomasdOtreppe** [ntop/ntopng#706]
Using Chrome Version 54.0.2836.0 canary (64-bit) on Windows 7 64 bit, it doesn't let me login.

ntopng version: ntopng Community v.2.4.160818 from ntopng repos (--community has been appended to /etc/ntopng/ntopng.conf

I haven't changed the credentials, base Ubuntu 16.04 install and ntop-ng only.

It lets me type the login no problem but when I type the password, it enable login button after the first character then disable it when typing the second character of the password and leaves it disabled which is preventing logging in. Works fine on Firefox 48.0.1 on the same OS.

**Comment by simonemainardi** [comment]
Hi, I can successfully login using Version 54.0.2839.2 canary (64-bit). Please, try with the new build that will be released tomorrow as it includes the following fix that very likely is related: https://github.com/ntop/ntopng/issues/700

**Comment by simonemainardi** [comment]
fix and solution given. closing for inactivity.

**Comment by ThomasdOtreppe** [comment]
Tested and just did a fresh install a few minutes ago and got v2.4.160818-1561. Still doesn't work.

**Comment by ThomasdOtreppe** [comment]
Is there any way I can help debug the issue?

**Comment by simonemainardi** [comment]
version `v2.4.160818-1561` doesn't include the fix. Please use a more recent version.

**Comment by ThomasdOtreppe** [comment]
That's the latest version available in packages.

**Comment by simonemainardi** [comment]
look for DEV packages, not sable

**Comment by ThomasdOtreppe** [comment]
Works fine with dev.

**Comment by HontoNoRoger** [comment]
Just tried the newest version on Ubuntu 16.04 stable repo, where it's not working.
When will a stable version with Chrome support be released to address this issue?
Thanks.

**Comment by robertdxyz** [comment]
I was able to reproduce it too

**Comment by xflowXen** [comment]
I am also able to reproduce this issue using v.2.4.170215 on CentOS 7.3.1611

**Comment by simonemainardi** [comment]
@xyGZen issue is fixed in the dev packages and will be included in the next forthcoming release

**Comment by mjhdcode** [comment]
Still happening for me on 3.6.181106 with CentOS 7.5....
Login works first time, then won't login - only on Chrome - Firefox works as expected
Thought I had lost my damn mind

**Comment by emanuele-f** [comment]
Please update to the latest version and retry. Please also ensure that you have no blocking browser plugins installed

**Comment by mjhdcode** [comment]
I don't have any plugins, and this bug seems pretty persistent (I'm well past the dev branch version suggested in other places), I think if you want this feature to work, a more in depth response to it's existence will be needed, luckily I'm monitoring isolated local network traffic, so I don't mind having no login - I just wanted you to know this issue is still lurking and has been since at least 2014. I have seen this question asked in 2014, and re-asked in 2016, 2017 and early 2018 with various versions cited. I think this bug needs to be upgraded to snark status and hunted thusly...

**Comment by mjhdcode** [comment]
Awesome toolkit though - kudos

**Comment by maravento** [comment]
neither in google chrome v72.0.3626.121 (Official build) (64 bits) (works in firefox 65.0.2 x64 and opera 58.0.3135.90) (ubuntu 18.04.2 x64)
