### ISSUE TITLE
Invalid timeseries links

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7065]
![image](https://user-images.githubusercontent.com/4493366/208936754-8d66f2ba-8237-4d11-b7ae-494e43f6b59b.png)

In the image above the URLs highlighted are not pointing to the correct timeseries

Please also note that there is a small issue on the last table column.

This issue is present on both dev and stable editions.

**Comment by uccidibuti** [comment]
I fixed frontend timeseries page to select the right metric and timeseries from url.
This is an example of timeseries url for tcp protocol:
http://localhost:3000/lua/host_details.lua?host=192.168.1.1&ts_schema=top:host:ndpi&page=historical&zoom=1d&ts_query=ifid:1,host:192.168.1.1,l4proto:tcp

**Comment by mtridici** [comment]
> I fixed frontend timeseries page to select the right metric and timeseries from url. This is an example of timeseries url for tcp protocol: http://localhost:3000/lua/host_details.lua?host=192.168.1.1&ts_schema=top:host:ndpi&page=historical&zoom=1d&ts_query=ifid:1,host:192.168.1.1,l4proto:tcp

@uccidibuti thank you for your work. Could you please help me to fix the issue also in my NTOPNG environment?

**Comment by lucaderi** [comment]
The bug is still pending. Clicking on 
![proto](https://user-images.githubusercontent.com/4493366/213407406-42a174c9-d54a-44cc-b2e7-5107fe10cadf.png)
any of these protocols always sends back to the same page
![luca](https://user-images.githubusercontent.com/4493366/213407607-112720a3-dcbb-4090-8e23-7955585c3cd1.png)

**Comment by MatteoBiscosi** [comment]
Now it works correctly
![image](https://user-images.githubusercontent.com/49585191/215459580-ca1f75c7-31cf-48c1-b7ef-c10ae602764d.png)
![image](https://user-images.githubusercontent.com/49585191/215459687-ec63309b-9224-42f3-8493-ff2161d415fa.png)

**Comment by lucaderi** [comment]
Not working If I click on the ICMP protocol icon I get

http://localhost:3000/lua/host_details.lua?host=192.168.1.178&zoom=1d&page=historical&ts_schema=top:host:l4protos&ts_query=ifid:0,host:192.168.1.178,l4proto:icmp

that does **not** show the ICMP timeseries

![a](https://user-images.githubusercontent.com/4493366/215750025-20db6687-9d21-4165-856f-944df4761cce.png)

**Comment by MatteoBiscosi** [comment]
Removed href in case no timeseries is still available
![image](https://user-images.githubusercontent.com/49585191/216568480-a86e95b7-1be5-4558-b838-22e8f89cdcdc.png)
![image](https://user-images.githubusercontent.com/49585191/216568605-32f912a2-1660-430f-af6a-dea627e53675.png)

**Comment by MatteoBiscosi** [comment]
Fixed in the latest version
