### ISSUE TITLE
SNMP Charts Need Improvements

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7076]
In SNMP there are a few issues that need to be tackled 
![image](https://user-images.githubusercontent.com/4493366/210179333-24a3dca4-9421-421c-b85e-381535b631df.png)

- Memory, CPU....timeseries are present only on host-based systems and need to be hidden for devices that do not support them
- Timeseries other than bytes RX/TX (example interface errors) are not selectable from the timeseries menu as they used to be: they need to be restored.

**Comment by MatteoBiscosi** [comment]
Fixed in the latest version. Pro version.
![image](https://user-images.githubusercontent.com/49585191/210532949-4b1fe30e-0a34-4efe-893b-f52ac6b8baae.png)

**Comment by lucaderi** [comment]
- CPU and memory are still present in hosts even
- The timeseries dropdown list does not include the interface list anymore. Please restore it

**Comment by MatteoBiscosi** [comment]
Issue fixed, please reopen if needed
