### ISSUE TITLE
Fail2Ban recipient frontend broken

### ISSUE THREAD

**Issue by aadlung** [ntop/ntopng#7284]
**Environment**:
OS name: Debian
OS version: 11.6
Architecture: x86_64
ntopng version/revision: ntopng Enterprise M v.5.6.230301

Some background: I am thinking about using the ntopng alerts to automatically block the clients (although they will still be in the alert list as the packet capture happens earlier). Currently I use fail2ban for logs and a shell script with ipset for IP ranges (based on https://github.com/kravietz/blacklist-scripts and using a `ipset add manual-blacklist x.x.x.x` for semi-automated blocks. But using a shell script for this just to block IPs would never "unban" them as I only receive the alerts with the IPs.

I tried to add/test the fail2ban integration to create a recipient, but this does not work. The frontend does not show the necessary fields (although filling out the wrong ones creates an invalid recipient).

![2023-03-01 at 22 56](https://user-images.githubusercontent.com/8441971/222274047-332add2f-f7d0-48e0-8799-224974209f2e.jpg)

In JS console I see an error:
```
third-party.js?1677707525:2 Uncaught Error: Syntax error, unrecognized expression: /usr/share/ntopng/scripts/lua/modules/check_templates/fail2ban_endpoint.template
    at st.error (third-party.js?1677707525:2:2006673)
    at st.tokenize (third-party.js?1677707525:2:2014690)
    at st.select (third-party.js?1677707525:2:2015525)
    at Function.st [as find] (third-party.js?1677707525:2:2000018)
    at A.fn.init.find (third-party.js?1677707525:2:2018111)
    at new A.fn.init (third-party.js?1677707525:2:2018600)
    at A (third-party.js?1677707525:2:1993878)
    at cloneTemplate (endpoint_notifications_list.lua:1276:16)
    at HTMLSelectElement.<anonymous> (endpoint_notifications_list.lua:1270:29)
    at HTMLSelectElement.dispatch (third-party.js?1677707525:2:2036164)
```

The file `/usr/share/ntopng/scripts/lua/modules/check_templates/fail2ban_endpoint.template` does not exist, only the file
`/usr/share/ntopng/httpdocs/templates/pages/notifications/fail2ban/fail2ban_endpoint.template`

**Comment by NicoMaio** [comment]
Fixed in pro repo by 5f66dfd55558543dbce1fb2fca73c6218b6f1e1b

**Comment by NicoMaio** [comment]
Hi @aadlung,
In the stable version, it should be fixed. Please update and let me know.

**Comment by aadlung** [comment]
Hello @NicoMaio - works now for me, at least I can add the endpoint, did not test the Fail2Ban completely yet.

I just realized the Links to recipients on the endpoint page, or the link to endpoints on the recipients page do not honor the setting for `-Z=/ntopng`. They always go to the root dir `/lua/admin/endpoint_notifications_list.lua?subdir=recipient&recipient_id=0`

![2023-03-03 at 22 02](https://user-images.githubusercontent.com/8441971/222828817-946efa38-7053-4351-9f85-0913a4857854.jpg)

**Comment by NicoMaio** [comment]
Hi @aadlung,
in the stable version, this last issue should be fixed too. Please update and let me know.

**Comment by aadlung** [comment]
Hello @NicoMaio  - the link from the endpoints to the "Used by Recipients" works now, thanks. But the link on the Recipients page back to "Bound to Endpoint" still does not work for me. This is a very minor issue.

**Comment by NicoMaio** [comment]
Hi @aadlung,
In the last stable version, the link on the Recipients page back to "Bound to Endpoint" should be fixed. Please update and let me know.

**Comment by aadlung** [comment]
Thanks, now everything works fine
