### ISSUE TITLE
Unexpected Device Connected/Disconnected is not working

### ISSUE THREAD

**Issue by plamondon-ln** [ntop/ntopng#7451]
ntopng v.5.7.230506 (20289) [OS: FreeBSD 12.2 Professional licence 
pfsense 2.6.0-RELEASE (amd64) FreeBSD 12.3-STABLE

**What happened**:
activated Unexpected Device Connected/Disconnected  Behavioural Checks (edit check options greyed out)

**How did you reproduce it?
got alerts and when trying to edit "Device/MAC Address Tracking List| Devices",  tried to edit "ACTION" , "Device Status" Denied to Allowed, does not work. The Device remains "Denied and teh alerts remain Engaged. 

Paste debug information below:
- Copy the service log from "systemctl status ntopng" or "journalctl -u ntopng".
systemctl status ntopng:  systemctl: Command not found.
journalctl: Command not found.

- Grab a screenshot from the GUI demonstrating the issue.
really?

- Provide a PCAP when this is required to reproduce the issue.
really?

**Comment by NicoMaio** [comment]
Hi @plamondon-ln 
In the last version released, it should be fixed. Please update and let me know.

**Comment by plamondon-ln** [comment]
Sorry no.
Version:        5.7.230508 [Enterprise/Professional build]
GIT rev:        dev:bdece1ba7006920c51d19d1191188e9406ba874f:20230508
Pro rev:        r5712
Built on:       FreeBSD 12.2
System Id:      xxxxxxxxxxxxxxx
Platform:       amd64
Edition:        Professional
License Type:   Permanent

**Comment by NicoMaio** [comment]
I think that you are not using the last version that we released because the commit that should fix this issue is 162ab5ce59bcdf16267bc0ef4245eb2879cb8841

**Comment by plamondon-ln** [comment]
I am using https://packages.ntop.org/FreeBSD/FreeBSD:12:amd64/latest/ as per documentation.
I cannot find 7451 in the version installed. No "coommit" number I can see.
Suggestion?

**Comment by NicoMaio** [comment]
Hi @plamondon-ln,
Please update with the last version released and let me know. It should fix this issue.

**Comment by MatteoBiscosi** [comment]
Hi @plamondon-ln we pushed a fix this morning, can you please update and let us know if the issue is fixed?

**Comment by plamondon-ln** [comment]
Something is different, but still not working. Now no IP/MAC is showing on the list. 
I joined a picture to show you.
 /usr/local/bin/ntopng -V:
[2.6.0-RELEASE][admin@pfSense.gmhp]/root: /usr/local/bin/ntopng -V
Version:        5.7.230509 [Enterprise/Professional build]
GIT rev:        dev:175462b4d3066406a3afa0e40d
![IMG_0803](https://github.com/ntop/ntopng/assets/60553360/784dd57b-c0ed-44c9-b764-c3a7a0ad950f)
2dcb4940cefa12:20230509
Pro rev:        r5715
Built on:       FreeBSD 12.2
System Id:      L431724979207AA80--U431724970E070E07--OB
Platform:       amd64
Edition:        Professional
License Type:   Permanent
Maintenance:    Until Sat Mar 30 13:54:22 2024 [326 days left]

**Comment by plamondon-ln** [comment]
FYI, I reinstalled everything from scratch. Did not change any preferences like it was suggested before. Ex..: left Interface Local Broadcast Domain Hosts Identifier to IP address instead of MAC addresss, like it was suggested before (not anymore).
Now the MAC list contains the proper name. But I no longer get an alert from Unexpected Device Connected/Disconnected. And I still cannot Edit Check Options (grayed out)

**Comment by MatteoBiscosi** [comment]
Hi @plamondon-ln I was able to reproduce your issue, I'll push an update soon and in a couple of hours update and the issue should be fixed. Please let me know.
The option is greyed out because that alert has no option to edit, it has just the enable and disable, then you edit everything from the "Device/MAC Address Tracking List" page

**Comment by plamondon-ln** [comment]
Thanks! Will do.

**Comment by plamondon-ln** [comment]
No change, sorry:
![IMG_0809](https://github.com/ntop/ntopng/assets/60553360/63bf0a02-2347-4fdd-96c9-aee9488a3ed3)

![IMG_0810](https://github.com/ntop/ntopng/assets/60553360/718b712d-a2f5-4958-8ac7-753aabfbafc1)

**Comment by plamondon-ln** [comment]
Good news!
software update ntopng v.5.7.230511 (20339) [OS: FreeBSD 12.2] seems to have fixed the problem, thank you!:
![IMG_0811](https://github.com/ntop/ntopng/assets/60553360/32de1d47-2cfa-4bde-8550-1f5ae20b3092)
