### ISSUE TITLE
Invalid Empty Tables Format

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7615]
1) Empty tables should not have an empty dropdown menu
2) it is odd that out of 4 expected flows none is reported

<img width="1430" alt="Screenshot 2023-06-29 at 17 15 13" src="https://github.com/ntop/ntopng/assets/4493366/06932f90-dd14-41c3-85ac-e0be5f29209a">

**Comment by NicoMaio** [comment]
Fixed by baeb8925adf0f0e6b3ac80ef88aca64435987522

**Comment by lucaderi** [comment]
<img width="1395" alt="Screenshot 2023-07-10 at 21 40 19" src="https://github.com/ntop/ntopng/assets/4493366/3a8fa03b-5d42-4f54-af91-4c97a57ceb4b">
Go to Hsol

**Comment by NicoMaio** [comment]
Fixed in the pro repo by 14b2bc24a8217ad0f6893a1047f2c0c60dc00e2d

**Comment by lucaderi** [comment]
Still broken
![Screenshot 2023-07-12 at 14 40 22](https://github.com/ntop/ntopng/assets/4493366/7666a880-4be8-470f-b7ea-6d866b1d8c95)

**Comment by lucaderi** [comment]
Seems to work after a restart. Let's close it for now
