### ISSUE TITLE
Ntop stop showing my custom profiles traffic after latest upgrade 

### ISSUE THREAD

**Issue by oronkessel1** [ntop/ntopng#7704]
**Environment**:
OS name: Centos 
* OS version: 7
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

ntop stop showing my custom profiles traffic after latest upgrade 

**How did you reproduce it?**

upgrade

**Debug Information**:

<img width="1336" alt="Screenshot 2023-07-31 at 12 26 31 PM" src="https://github.com/ntop/ntopng/assets/74092942/f7bc6e00-fb37-4cae-8c99-c035a32ce1ef">

**Comment by MatteoBiscosi** [comment]
The issue should be fixed in the latest version
![image](https://github.com/ntop/ntopng/assets/49585191/6d9110c6-a45f-4744-bb3b-a4ebcdbd8548)

**Comment by oronkessel1** [comment]
still not showing the graphs and also in the time dropdown I see only 30 min doesn't show the rest 
all was working before the upgrade

**Comment by oronkessel1** [comment]
<img width="1365" alt="Screenshot 2023-08-17 at 5 43 37 PM" src="https://github.com/ntop/ntopng/assets/74092942/d5f281c5-b91a-43c3-8622-4e86377c4ec3">

**Comment by oronkessel1** [comment]
I see graphs in the DASHBOARD but not under the interface ->  trafficprofiles
