### ISSUE TITLE
Slow periodic activity during startup

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7800]
![image](https://github.com/ntop/ntopng/assets/4493366/9754d6ea-ac9e-42fd-82cf-d6c4fc56784e)

The problem occurs during ntopng's startup procedure. When I restart  ntopng, I can see that both second and 5second scripts' statuses are showing as "Queued" but the "Not Executed" and "Running Slow" flags begin to increment as errors. As soon as the scripts start running properly there are no further errors or warnings. However, because the errors are now listed, the system constantly (every minute) updates the alert system that there are problems. Is this a bug? Please note that this is a brand new install of ntopng after I removed and deleted my original copy, so basically out of the box on a pfsense system. Other than disabling these warnings (which I would rather not) I don't know how to fix this. In my opinion, the "Not Executed" flag should not be set until the script is out of Queued status, I'm just guessing though.

This can be reproduced with ntopng Community v.5.6.230701 (FreeBSD 14.0)

**Comment by lucaderi** [comment]
Other evidence of the problem

![image](https://github.com/ntop/ntopng/assets/4493366/5b4e2d51-d888-4f6a-a2b7-af2500756e34)

**Comment by fredouil66** [comment]
hello, I too have this type of problem and it is impossible, despite hours of research and numerous adjustments, to resolve this error. Do you have a way to find out how because apparently I'm over 9 seconds..

![image](https://github.com/ntop/ntopng/assets/71542898/927fac40-2101-4b1d-a847-1746552f60cf)

**Comment by MatteoBiscosi** [comment]
Hi @fredouil66 could you please share your ntopng --version ?

**Comment by fredouil66** [comment]
root@ntop-vrb:~# ntopng --version
Version:        5.7.230921 [Enterprise/Professional build]
GIT rev:        dev:61b2606968565aac18d28f0b6cf55c5d670a3be0:20230921
Pro rev:        r6089
Built on:       Debian GNU/Linux 11 (bullseye)
Platform:       x86_64
Edition:        Enterprise XL (Bundle)
License Type:   Permanent
Maintenance:    Until Thu Aug 29 15:30:41 2024 [343 days left]

**Comment by milonic** [comment]
Is there any update to this?

I've noticed that ntopng is crashing now with "out of swap space" errors.

I believe it might be related to this issue

**Comment by MatteoBiscosi** [comment]
Hi @milonic your crash means that no more memory is available on your system and the os automatically kills some application using a lot of memory, so it should be releated to this.
Could you please share your ntopng --version output?
Please share the RAM usage of your machine with ntopng up, to ensure you have no memory leak.
(you can jump to the system interface -> Health -> System -> charts icon -> Process Memory)
![image](https://github.com/ntop/ntopng/assets/49585191/65a4d08b-e018-4993-8aee-05e949140a4a)

**Comment by milonic** [comment]
Here's the version:

[2.7.0-RELEASE][admin@pfSense.localdomain]/root: ntopng --version
Version:        5.6.230701 [Community build]
GIT rev:        :5.6.230701


When I visit: system interface -> Health -> System -> charts icon -> Process Memory - There's no data to show. Something's not logging?

However, I think there is a memory leak and it appears to be ntopng. When I first restarted ntopng it had consumed 428mb ram, after an hour or so it has consumed 626mb. I will see what the memory use is in another hour or two.

**Comment by MatteoBiscosi** [comment]
Hi @milonic there is a problem with your version, we currently support only the dev version (5.7 version) of ntopng on that system, if you have the 5.6 is the one by default that you can find on pfsense and we cannot help you with that. Please unistall it and reinstall ntopng by following these instructions https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html#pfsenseintegration
After installing this let me know if the memory leak persists

**Comment by milonic** [comment]
Hi,

Managed to get it installed but there's a problem with ntopng crashing with "Illegal instruction" error

redis is running

Is there a debug I can enable to figure this out or do you know what the problem is?

**Comment by MatteoBiscosi** [comment]
Yes, please run ntopng in foreground, to run in foreground, open a shell and directly run ntopng
![image](https://github.com/ntop/ntopng/assets/49585191/f3ac5d1e-56b8-4397-9a1e-7bacbf2b6151)

**Comment by milonic** [comment]
Hi,

I am running in foreground, with **ntopng --community /usr/local/etc/ntopng/ntopng.conf**

I end up with:

25/Oct/2023 15:01:02 [PeriodicActivities.cpp:108] Started periodic activities loop...
25/Oct/2023 15:01:03 [startup.lua:38] Processing startup.lua: please hold on...
25/Oct/2023 15:01:03 [startup.lua:121] [lists_utils.lua:831] Refreshing category lists...
25/Oct/2023 15:01:03 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'IP address' category '100' in list 'Stratosphere Lab'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host '56565' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'noluyoruzawk' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host '4040' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'datacikerim' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'nicehash' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'mpapwpodllalw' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'makelovenotmalware.local' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'lwwfechxdr8aiq0bbhtrxry7i1c8itnz' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:466] Failure loading host 'ddkkba0zqra9dtqunixbqaa8olgtkc5j' category '100' in list 'ThreatFox'
25/Oct/2023 15:01:04 [startup.lua:121] [lists_utils.lua:753] Category Lists (24487 hosts, 10917 IPs, 0 JA3) loaded in 1 sec
25/Oct/2023 15:01:04 [startup.lua:125] Initializing device polices...
25/Oct/2023 15:01:04 [startup.lua:141] Initializing alerts...
25/Oct/2023 15:01:04 [startup.lua:150] Initializing timeseries...
25/Oct/2023 15:01:04 [startup.lua:240] Completed startup.lua
25/Oct/2023 15:01:04 [PeriodicActivities.cpp:167] Found 10 activities
25/Oct/2023 15:01:04 [NetworkInterface.cpp:3708] Started packet polling on interface em0 [id: 1]...
25/Oct/2023 15:01:04 [NetworkInterface.cpp:3708] Started packet polling on interface LAN [id: 2]...
25/Oct/2023 15:01:04 [NetworkInterface.cpp:3708] Started packet polling on interface WAN [id: 3]...
25/Oct/2023 15:01:04 [NetworkInterface.cpp:3708] Started packet polling on interface lo0 [id: 4]...
Illegal instruction

**Comment by MatteoBiscosi** [comment]
Hi, could you please share the result of ntopng --version?

**Comment by milonic** [comment]
[2.7.0-RELEASE][admin@pfSense.localdomain]/var/log/redis: ntopng --version
Version:        5.7.231025 [Enterprise/Professional build]
GIT rev:        dev:42866af4a94c4c195cf9b42ee2cba7399e578f07:20231025
Pro rev:        r6138
Built on:       FreeBSD 14.0
System Id:      L67EB58689206A1D8--U67EB586805190C04--OB
Platform:       amd64
Edition:        Community
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Oct 25 15:29:14 2023

**Comment by MatteoBiscosi** [comment]
Can you give me your cpu model and name with all the info regarding to it?
run:
 sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu'

**Comment by milonic** [comment]
Sure, no problem:

hw.machine: amd64
hw.model: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
hw.ncpu: 4
hw.machine_arch: amd64


It's a HP DL320e Gen8 - I recently upgraded the ram to 12GB

**Comment by lucaderi** [comment]
@milonic Can you please download https://www.dropbox.com/s/qfv10lsziyhsvv7/ntopng-debug-freebsd14.tgz?dl=0 and create a coredump ? Please share it here on github so we can track the problem

**Comment by milonic** [comment]
Tried that, was hoping to see something in /var/crash but it's empty. Here's what appears in system.log:

Oct 25 19:00:45 pfSense kernel: em0: promiscuous mode enabled
Oct 25 19:00:45 pfSense kernel: pppoe0: promiscuous mode enabled
Oct 25 19:00:45 pfSense kernel: lo0: promiscuous mode enabled
Oct 25 19:00:48 pfSense kernel: pid 93765 (ntopng-debug-freebs), jid 0, uid 288: exited on signal 4
Oct 25 19:00:48 pfSense kernel: em0: promiscuous mode disabled
Oct 25 19:00:48 pfSense kernel: pppoe0: promiscuous mode disabled
Oct 25 19:00:48 pfSense kernel: lo0: promiscuous mode disabled


Please let me know how I can create a core dump, or where to look?

My apologies, I'm more Linux than BSD, so not sure how to do certain things.

**Comment by lucaderi** [comment]
I think you need to check if the core dump size is unlimited

[deri@freebsd14 ~]$ ulimit  -a
number of pseudoterminals                (-P) unlimited
socket buffer size           (bytes, -b) unlimited
core file size              (blocks, -c) unlimited

otherwise do this

- install gdb
- stop the ntopng service
- then do (as root) "gdb ntopng-debug"
- inside gdb do "r /etc/ntopng/ntopng.conf"
- as soon as you have the crash please do "thread apply all bt"

then paste the output in this ticket. Otherwise mail me (deri@ntop.org) and I will organize a remote support session

**Comment by milonic** [comment]
OK, from **ulimit -a** I get this:

cpu time               (seconds, -t)  unlimited
file size           (512-blocks, -f)  unlimited
data seg size           (kbytes, -d)  33554432
stack size              (kbytes, -s)  524288
core file size      (512-blocks, -c)  unlimited
max memory size         (kbytes, -m)  unlimited
locked memory           (kbytes, -l)  unlimited
max user processes              (-u)  15829
open files                      (-n)  351252
virtual mem size        (kbytes, -v)  unlimited
swap limit              (kbytes, -w)  unlimited
socket buffer size       (bytes, -b)  unlimited
pseudo-terminals                (-p)  unlimited
kqueues                         (-k)  unlimited
umtx shared locks               (-o)  unlimited


Which looks good.

I then tried gdb but I'm struggling there to get any data:

I'm not sure how to do a back trace, as **thread apply all bt** returns nothing, I set thread debugging on but looks like it's being deleted before i can view it.

Here's that I get:

26/Oct/2023 12:34:52 [PeriodicActivities.cpp:108] Started periodic activities loop...
26/Oct/2023 12:34:53 [startup.lua:38] Processing startup.lua: please hold on...
26/Oct/2023 12:34:53 [startup.lua:121] [lists_utils.lua:831] Refreshing category lists...
26/Oct/2023 12:34:53 [PeriodicActivities.cpp:167] Found 10 activities
26/Oct/2023 12:34:53 [NetworkInterface.cpp:3708] Started packet polling on interface em0 [id: 1]...
26/Oct/2023 12:34:53 [NetworkInterface.cpp:3708] Started packet polling on interface LAN [id: 2]...
26/Oct/2023 12:34:53 [NetworkInterface.cpp:3708] Started packet polling on interface WAN [id: 3]...
26/Oct/2023 12:34:53 [NetworkInterface.cpp:3708] Started packet polling on interface lo0 [id: 4]...
Illegal instruction
[threads] switch_to_no_thread: thread = NONE
[threads] operator(): deleting thread 98190.100123.0, silent = 0
[threads] ~thread_info: thread 98190.100123.0
During startup program exited with code 132.
(gdb) thread apply all bt
(gdb) info threads
No threads.

Shall I email you?

**Comment by lucaderi** [comment]
Can you please mail me so we can arrange an interactive call?

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/nDPI/commit/8769a2282b89883ccad97ddfe8dfaefefeb51865

**Comment by fredouil66** [comment]
Hello I followed the subject but I don't understand I still have the problem with 600% CPU usage (6X100%) because 6 core and I still don't understand how to solve all that
![image](https://github.com/ntop/ntopng/assets/71542898/97d985a0-ccc3-4318-b7f5-c62b2945f905)

**Comment by fredouil66** [comment]
I was in version:
![image](https://github.com/ntop/ntopng/assets/71542898/d6664bc1-ebf3-4518-9ccf-4ba9dee653a6)

I searched everywhere but in vain.. I just put days with:
![image](https://github.com/ntop/ntopng/assets/71542898/6926d448-6231-44ac-94a4-64392655de0d)

**Comment by fredouil66** [comment]
I deactivated all the Behavioral Checks to see if that was what consumed all the CPU resources but no, after a few hours the CPU went back to 100% for no reason
