### ISSUE TITLE
Flow Analysis broken in 5.6-stable

### ISSUE THREAD

**Issue by dwhitemv25** [ntop/ntopng#7819]
**Environment**:
* OS name: FreeBSD
* OS version: 12.4-RELEASE-p5
* Architecture: amd64
* ntopng version/revision: 5.6-stable@01841c9 (From FreeBSD port/package)

**What happened**:
Clicking Flows -> Analysis at top of page displays endless spinny, ntopng logs the following error:
```
11/Sep/2023 11:43:31 [LuaEngine.cpp:1338] WARNING: Script failure [/usr/local/share/ntopng/scripts/lua/rest/v2/get/flow/aggregated_live_flows.lua][/usr/local/share/ntopng/scripts/lua/modules/http_lint.lua:2421: [LINT] Validation error: Unknown key aggregation_criteria [value: application_protocol]: missing validation perhaps?
```

**How did you reproduce it?**

 * Open Flows -> Live
 * Click Analysis in menu bar

**Debug Information**:

* The string "aggregation_criteria" only appears in httpdocs/dist/ntopng.js. This file was last touched in commit 8b9a2a5, where it was merged from dev. 
* Copying http_lint.lua from dev gets the page to display, but all the application names are "undefined" and page navigation is broken.

**Comment by cardigliano** [comment]
Fixed aggregation_criteria  in 9210f5276ee3093bb6f14244a0b04e52de4812ba

**Comment by dwhitemv25** [comment]
This commit doesn't fix the Analysis page; it still shows no app names. See attached screenshot.
<img width="1942" alt="Screenshot 2023-09-12 at 12 34 47 PM" src="https://github.com/ntop/ntopng/assets/1824765/ac45630c-0a29-4ef8-a3a5-1ba8b6e8ca3d">

**Comment by NicoMaio** [comment]
Hi @dwhitemv25,
What is your ntopng version?

**Comment by dwhitemv25** [comment]
ntopng version/revision: 5.6-stable@01841c9 (From FreeBSD port/package)

**Comment by NicoMaio** [comment]
@dwhitemv25, 
could you please provide the response body of the REST endpoint '/lua/rest/v2/get/flow/aggregated_live_flows.lua'?

**Comment by dwhitemv25** [comment]
Sorry for the delay on the update, I wanted to make sure I didn't have any local changes that might be conflicting.

Attached is the output requested with `?ifid=1` added so it returns data.
[aggregated-flows.txt](https://github.com/ntop/ntopng/files/12707770/aggregated-flows.txt)

**Comment by NicoMaio** [comment]
@dwhitemv25,
When you open the element inspection in your browser and navigate to the 'Console' tab, do you see any errors?

**Comment by dwhitemv25** [comment]
Nope, no console messages in the browser developer tools.

**Comment by dwhitemv25** [comment]
That said, changing the dropbox at the top to 'Client' does generate this exception:
```
Uncaught TypeError: t.client_name is undefined
    f page-aggregated-live-flows.vue:152
    render page-aggregated-live-flows.vue:283
    get third-party.js:2
    fnGetData third-party.js:2
    $ third-party.js:2
    rt third-party.js:2
    j third-party.js:2
    gt third-party.js:2
    bt third-party.js:2
    c third-party.js:2
    l third-party.js:2
    fireWith third-party.js:2
    A third-party.js:2
    e third-party.js:2
    send third-party.js:2
    ajax third-party.js:2
    ft third-party.js:2
    bt third-party.js:2
    ct third-party.js:2
    ut third-party.js:2
    Rt third-party.js:2
    W third-party.js:2
    l third-party.js:2
    each third-party.js:2
    each third-party.js:2
    l third-party.js:2
    DataTable third-party.js:2
    setup datatable.vue:144
    setup datatable.vue:191
    Ia vue.esm-browser.prod.js:1
    Oa vue.esm-browser.prod.js:1
    __weh vue.esm-browser.prod.js:1
    tl vue.esm-browser.prod.js:1
    ll vue.esm-browser.prod.js:1
    promise callback*Za vue.esm-browser.prod.js:1
    Ya vue.esm-browser.prod.js:1
    effect vue.esm-browser.prod.js:1
    ft vue.esm-browser.prod.js:1
    pt vue.esm-browser.prod.js:1
    pa vue.esm-browser.prod.js:1
    set value vue.esm-browser.prod.js:1
    h page-aggregated-live-flows.vue:401
    i page-aggregated-live-flows.vue:82
    Ia vue.esm-browser.prod.js:1
    Oa vue.esm-browser.prod.js:1
    il vue.esm-browser.prod.js:1
    _ select-search.vue:111
    dispatch third-party.js:2
    handle third-party.js:2
    trigger third-party.js:2
    trigger third-party.js:2
    each third-party.js:2
    each third-party.js:2
    trigger third-party.js:2
    bind third-party.js:2
    invoke third-party.js:2
    trigger third-party.js:2
    trigger third-party.js:2
    _registerResultsEvents third-party.js:2
    invoke third-party.js:2
    trigger third-party.js:2
    bind third-party.js:2
    dispatch third-party.js:2
    handle third-party.js:2
page-aggregated-live-flows.vue:152:55
```

**Comment by dwhitemv25** [comment]
I found a solution to this problem -- I sync'd the `ntopng-dist-5.6-stable` branch from the `ntopng-dist` repository into my installation, cleared cache, and now the Analysis (and charts) work again. I will try to determine if there is an issue with the FreeBSD port/package not packaging the correct dist directory contents. 

Took a while to notice that the `httpdocs/dist` directory contents come from a completely separate repository. It's the first time I've encountered a cross-repository link in GitHub.

Sorry to send you on a wild-goose chase.

**Comment by dwhitemv25** [comment]
Looks like a problem with the FreeBSD port; the distfile versions are out of sync. I have opened a bug in [FreeBSD bugzilla](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274095) to address it.

This issue can be closed if no additional information is needed.

**Comment by MatteoBiscosi** [comment]
Hi @dwhitemv25 thanks for the report, we do not mantain freebsd on ntopng stable version (see https://packages.ntop.org/FreeBSD/) so I highly suggest on moving to the official (dev) repo, here you can find the instructions https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-freebsd
