### ISSUE TITLE
[bug] traffic dashboard has been disappear at startup, after today upgrade

### ISSUE THREAD

**Issue by walteroa2023** [ntop/ntopng#7840]
**Environment**:
* OS name: Alpine
* OS version: v3.18
* Architecture: amd64
* ntopng version/revision: Community  v.5.7.230920 (Ubuntu 22.04.3 LTS)

**What happened**:
After today upgrade, traffic dashboard has been disappear at startup 

**How did you reproduce it?**
restart after upgrade

**Debug Information**:

![image](https://github.com/ntop/ntopng/assets/142554546/ea3e8389-4b17-44f8-ba22-3486f2bc688d)

**Comment by cardigliano** [comment]
Fix pushed, new packages in less than 1h from now

**Comment by walteroa2023** [comment]
cool !! Thx @cardigliano

**Comment by walteroa2023** [comment]
updated to v.5.7.230921 rev.21638.
image hash sha256:b22867cff3808e809b146b01341f00ee501472dcf0dfdab4206787e4f1d25f3d 
**[TESTED] Issue still there.**

**Comment by DigiAngel** [comment]
Same...just git pulled a few seconds ago (06628ad6945fc7f8d21e4d120558c45b7e00ce38)...no dashboard.

**Comment by walteroa2023** [comment]
**[TESTED] Fixed.**
updated to v.5.7.230922 rev.21642
image hash: sha256:1eb081db3f9da2b28463201a9c388670344aed88599885d7caf21099f64fecbc

**Comment by DigiAngel** [comment]
git pull gives "Already up to date."

**Comment by walteroa2023** [comment]
> git pull gives "Already up to date."

i pulled from docker hub :)

**Comment by DigiAngel** [comment]
Ok?  I'm not using docker.  Trying a full git clone now.

**Comment by DigiAngel** [comment]
Confirming fixed using full git clone.  It looks pretty neat too!  Thank you.
