### ISSUE TITLE
Alert Explorer shows alerts but cannot display the list for FLOWS "[SQLiteAlertStore.cpp:161] ERROR: SQL Error: near "AS": syntax error"

### ISSUE THREAD

**Issue by field64** [ntop/ntopng#7878]
I think this is more of a local problem and not a defect, since i don't see any other references to the same problem.

**Environment**:
* OS name:  Raspbian GNU/Linux 
* OS version: 11 (bullseye) 
* Architecture: armv7l
* ntopng version/revision:  v.5.7.231001 

**What happened**:
[](url)
After upgrade to newest NTOPNG, alert->explorer displays alerts in the graph, and list.
Select "requires attention" or "all"'
select time range 6 hours (anything reasonable)
the list shows a number of FLOW type alerts at WARNING level
click on the number - could be 2, 10, or 300. expect a list of the alerts to appear, no entries appear.

- screen always shows "All good. There is no alert requiring user actions in the selected time frame."

### works for INTERFACE and HOST levels, but not FLOW levels error, emergency, 
webhook does properly output all levels of alerts.

**How did you reproduce it?**
Unknown, still in the error state after full OS upgrade and reboot.

**Debug Information**:
Prior to the OS upgrade , noted that each query on the alert->explorer screen seemed to coincide with these log messages in /var/log/ntopng.log

ntopng [SQLiteAlertStore.cpp:161] ERROR: SQL Error: near "AS": syntax error

![ntopng-24hrs](https://github.com/ntop/ntopng/assets/23174949/5de5a855-7b84-4d0c-ab59-a6534906be48)

Since the OS update, ntopng does not log anything to this file. (config file contains "-v=4")

● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2023-10-05 12:43:38 CEST; 1h 30min ago
  Process: 576 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a>
  Process: 604 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 606 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exi>
  Process: 610 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > />
 Main PID: 612 (ntopng-main)
    Tasks: 36 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           └─612 /usr/bin/ntopng /run/ntopng.conf

Screenshots attached showing all alerts, ,then selecting emergency. (27 entries)

![ntopng-24hrs](https://github.com/ntop/ntopng/assets/23174949/eecb58e8-bb94-4025-ac77-da3feac34cbd)
![ntopng-emergency-27entries](https://github.com/ntop/ntopng/assets/23174949/0187a8ed-6e22-4858-8b39-7f2e0408d0bd)

**Comment by MatteoBiscosi** [comment]
Hi @field64 , please update to the latest ntopng version in a couple of hours and let me know if the issue persists

**Comment by MatteoBiscosi** [comment]
Could you please share your ntopng.conf file?

**Comment by cardigliano** [comment]
This looks like a bug that has been fixed a few days ago, updating should fit it.

**Comment by field64** [comment]
Thanks, will update. FYI - still see this message in /var/log/ntopng.log
 Oct  6 02:21:13 pi-7 ntopng: 06/Oct/2023 02:21:13 [SQLiteAlertStore.cpp:161] ERROR: SQL Error: near "AS": syntax error#012 SELECT 4 entity_id, (tstamp_end - tstamp) duration, *, hex(alerts_map) alerts_map, (srv2cli_bytes + cli2srv_bytes AS total_bytes) FROM `flow_alerts` WHERE (tstamp >= 1696465170 AND tstamp <= 1696551570) AND ( ((alert_status = 0) OR (alert_status = 1)) ) ORDER BY tstamp desc LIMIT 10 OFFSET 0

**Comment by field64** [comment]
fixed after update.
ntopng Community v.5.7.231006 (Raspbian GNU/Linux 10 (buster))   - works well, thank you !

**Comment by field64** [comment]
fixed after update.
ntopng Community v.5.7.231006 (Raspbian GNU/Linux 10 (buster)) - works well, thank you !
