### ISSUE TITLE
Incomplete Reports when generate 1 week or more

### ISSUE THREAD

**Issue by souzaeric** [ntop/ntopng#813]
The reports don't show anything below “Application Breakdown”, i.e. the report doesn’t show “Top Countries”, Top Local Hosts”, “Top Remote Hosts” and “Top ASN”. It's the same for any time period bigger than 1 week.

ntopng Pro [Small Business Edition] v.2.5.161104

**Comment by simonemainardi** [comment]
- right-click on the browser and hit inspect elements to see if there are any js errors
- inspect ntopng logs and see if Lua goes oom when generating the report

**Comment by souzaeric** [comment]
this show up on my log: [Lua.cpp:5740] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/get_from_top_talkers_db.lua][not enough memory]

But I have enough memory, I have 11 Gb Ram free.

This is my inspect elements:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.send            jquery.js:9592

Uncaught SyntaxError: Unexpected token H in JSON at position 0(…)     jquery.js:8482

Uncaught TypeError: Cannot read property '1' of undefined(…)           d3.v3.js:6670

**Comment by emanuele-f** [comment]
@souzaeric how many local hosts do you have in your network?

**Comment by souzaeric** [comment]
On Ntopng I don't start with the option -m for local network, so, all hosts are considered remote hosts.

Even so, I don't know tell you exactly how many posts I have in the environment.

**Comment by emanuele-f** [comment]
The web server running ntopng web ui internally works with Lua VMs, which indeed has a memory limit (1GB I think) no matter how much RAM you have. The report page is significally memory intensive since it has to fetch a lot of data, expecially when the number of hosts is huge. Since the solution requires some accurate thoughts, I'll mark this as an enhancement for now. Thank you.

**Comment by thegeodave** [comment]
It occasionally works when I choose 1M, 6M or 1Y but it mostly hangs and get the "not enough memory" in syslog. My only suggestion is that when this is fixed I'd like to see or choose to see more than the top thirty Local Hosts

**Comment by emanuele-f** [comment]
Hi, we have made some improvements. Can you try the tomorrow version of ntopng and report if you still experience the original issue? Thank you.

**Comment by emanuele-f** [comment]
@souzaeric @thegeodave do you still experience the issue with the latest version?

**Comment by souzaeric** [comment]
Hi @emanuele-f, I updated my ntopng today, but the traffic report is missing some informations. Now this only show me, network Interfaces

See the picture in bellow:
![image](https://cloud.githubusercontent.com/assets/22778946/22883839/3a981e24-f1d9-11e6-9e36-3de3fb674b9b.png)

**Comment by emanuele-f** [comment]
Please select an interface from the check button at the top of the page, near the printer button

![screenshot at 2017-02-13 14-56-19](https://cloud.githubusercontent.com/assets/5488003/22886142/dfed1884-f1fc-11e6-92e6-afe478ee041e.png)

**Comment by souzaeric** [comment]
I'm sorry, I didn't pay attention on this option.

After selected, the problem continues, I got the message:
WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/get_from_top_talkers_db.lua][not enough memory]

**Comment by lucaderi** [comment]
@emanuele-f Any chance to close this issue pending for months?

**Comment by simonemainardi** [comment]
Further investigation highlighted the following.

The issue is due to the data aggregation of the sql top talker statistics. This also causes and invalid JSON to break the rendering of the page

```
"HTTP/1.1 500 Internal server error
Content-Type: text/html
Connection: close

<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script &quot;/home/deri/ntopng/scripts/lua/pro/get_from_top_talkers_db.lua&quot; returned an error:
<p><H3>not enough memory</H3></body></html>"
```

we must review the top talker statistics.

**Comment by simonemainardi** [comment]
Issue is fixed. A new release will be built overnight.

**Comment by thegeodave** [comment]
what version is this fix on? I have 2.5.170328 and the problems persists.

**Comment by thegeodave** [comment]
Well I take that back. It does appear to work after a restart BUT the report for 1 M or 6M shows top local hosts with totals that would reflect and be accurate for 1 day's worth of  throughput. I would expect my top local hosts on the 1 Month report to be around 800GB and the reports shows 9GB. And, Historical reports for individual local hosts are working and accurate.

**Comment by simonemainardi** [comment]
Some degree of approximation is natural as report top talkers are obtained from 'minute top-talkers' that, in turn, are crunched in 'hour top-talkers' and in 'day top-talkers' for long periods such as 1 month.

However, a 2 orders of magnitude difference is not reasonable, unless your hosts completely disappears for periods of time and thus are kicked out from many top talker samples.

Can you please comment on the differences you experience in 1 week reports?

Also, can you please report the interface active hosts chart?

However, I have made another optimization. Please, wait an hour (a new build is in progress) then update ntopng and repeat the tests before reporting back.

**Comment by thegeodave** [comment]
updated to v2.5.170403. Hourly report to Day report to Week report all show valid data. However,  pulling up the Monthly report shows the top local hosts results the same as weekly results. see attached

![hour](https://cloud.githubusercontent.com/assets/25374047/24633771/17a7782a-187f-11e7-8454-f9a085d74853.png)
![day](https://cloud.githubusercontent.com/assets/25374047/24633784/1f4f5c28-187f-11e7-87b5-036d41843908.png)

![week](https://cloud.githubusercontent.com/assets/25374047/24633788/24e39168-187f-11e7-9c2c-d6a06f323793.png)

![month](https://cloud.githubusercontent.com/assets/25374047/24633790/2876f0f4-187f-11e7-912f-4c38ff68d80c.png)

**Comment by emanuele-f** [comment]
Please open a separate bug to truck this issue. Thank you.
