### ISSUE TITLE
SNMP Interface Similarity Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8291]
It seems that this feature is no longer working

**Comment by NicoMaio** [comment]
Fixed in the PRO repo by 5aba754489f84d76ce6615e3e8b25efa6c868645

**Comment by lucaderi** [comment]
<img width="1370" alt="Screenshot 2024-04-30 at 10 53 30" src="https://github.com/ntop/ntopng/assets/4493366/fdee5ef2-0629-46fb-a6aa-df1888157e1c">

Still broken on Hsol SNMP

**Comment by NicoMaio** [comment]
Opening that page I got these logs 
![image](https://github.com/ntop/ntopng/assets/55502486/f5ca468a-a035-48b3-a9fa-170c6dfee4cf)

**Comment by lucaderi** [comment]
Fixed
