### ISSUE TITLE
ntopng database schema upgrade on every restart

### ISSUE THREAD

**Issue by tbo2k9** [ntop/ntopng#912]
There are already 2 tickets related to this issue. But it still not fixed.

We are on the stable repository.
ntopng --version
v.2.4.170109 [Professional Edition]
GIT rev:   2.4-stable:141c778cd94103c876cc75ad2dad74d27ae97c68:20170109
Pro rev:   r642

2 weeks ago we buyed and installed ntopng.
Since then we got 25 GB of mysql data.
But on every restart the datase schema is updated, which takes a very long time.
ALTER TABLE `flowsv4` ENGINE='MyISAM'

Since ntop created the database by itself a week ago and it is still myisam, I believe this is a bug.

mysql> show table status\G
*************************** 1. row ***************************
           Name: flowsv4
         Engine: MyISAM
        Version: 10
     Row_format: Dynamic
           Rows: 60287989
 Avg_row_length: 350
    Data_length: 21132018468
Max_data_length: 0
   Index_length: 4583618560
      Data_free: 0
 Auto_increment: 60287990
    Create_time: 2017-01-09 09:53:15
    Update_time: 2017-01-09 10:30:32
     Check_time: 2017-01-09 10:14:25
      Collation: utf8_general_ci
       Checksum: NULL
 Create_options: partitioned
        Comment:
*************************** 2. row ***************************
           Name: flowsv6
         Engine: MyISAM
        Version: 10
     Row_format: Dynamic
           Rows: 48
 Avg_row_length: 239
    Data_length: 11496
Max_data_length: 0
   Index_length: 475136
      Data_free: 0
 Auto_increment: 49
    Create_time: 2017-01-09 10:14:26
    Update_time: 2017-01-09 10:14:26
     Check_time: NULL
      Collation: utf8_general_ci
       Checksum: NULL
 Create_options: partitioned
        Comment:
2 rows in set, 2 warnings (0.01 sec)

We were using mariadb.
But since the other tickets indicated that would be a bug related mariadb vs. mysql, I purged mariadb and installed the official oracle mysql-5.7 with no change.

In the other tickets there was also mentioned some ntopng 2.5 which hast that fixed, but it looks like we would have to install the not recommend beta/dev then.

**Comment by simonemainardi** [comment]
@tbo2k9 can you please post the output of `show processlist;` in mysql while the update is in progress?

We already fixed that issue for other users and ported the fix to the stable : https://github.com/ntop/ntopng/issues/741

what is the os of the system you're using?

**Comment by tbo2k9** [comment]
I am running debian 8.6
I had mariadb 10.0.(some minor) delievered with debian 8.
Currently I am running mysql 5.7 from repo.mysql.com which did not fix the problem.

The background query was "ALTER TABLE flowsv4 ENGINE='MyISAM'" showing in processlist by ntopng.
Exactly like in the other tickets.

But apparently the problem does not to exist any longer.
After some restarts of ntopng I saw 3 "ALTER TABLE" (the other queued) and killed them manually (the mysql commands). Then the web interface appeared. 
And now it does not repeat the command anymore. 
I looks like the update from today fixed the problem.
