### ISSUE TITLE
Cannot create new Active Monitoring session

### ISSUE THREAD

**Issue by vk5ztv** [ntop/ntopng#9191]
**Environment**:
* OS name: Raspbian
* OS version: Bookworm
* Architecture: arch64
* ntopng version/revision: 6.5.250504
**What happened**:

Attempting to create Active Monitoring entry. Selected:
Measurement - Speedtest
Host - speedtest.net (only option)
Run Monitoring - Every Hour
Threshold - <30Mbps (appropriate for my connection speed)
Hovering over "Interface" gives a cursor with a "no-entry" symbol - cannot select an interface.
Click "Add".

Result: dialog never closes, progress indicator spins indefinitely. 

NOTE: This ONLY happens when ntopng is running as a service (using systemctl start ntopng.service). When running ntopng from the CLI using ntopng -v6 (as root) I can select an interface and the speedtest record is successfully added.

**How did you reproduce it?**

see above.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @vk5ztv thanks for reporting, the issue should be addressed by tomorrow build, so please tomorrow update and let me know

**Comment by vk5ztv** [comment]
Hi Matteo - yes, it does appear to be fixed. I can now edit existing active monitoring entries and add new ones without needing to have ntop running as root via the CLI. 

Thanks for the quick response.

**Comment by vk5ztv** [comment]
One thing I note though - even though I can add new entries and edit existing entries, I still cannot select an interface unless it is running as root via the CLI. The interfaces list does not appear to be populated and hovering the mouse over it gives the "No entry" cursor. Not sure if this is expected behaviour or not, but it is different when running as a service under systemd as compared to when running from the CLI as root. If that's expected, this issue can be closed, but if not there may still be something that needs attention (perhaps a permissions issue?).
