### ISSUE TITLE
System error detected in ntopng, please report it.

### ISSUE THREAD

**Issue by takenek** [ntop/ntopng#9194]
Debian 12 64bit
[ntopng Enterprise M v.6.4.250501]

root@NAT:~# dpkg -l |grep ntop
ii  apt-ntop-stable                 2.10-29                                 all          ntop stable apt package repository
ii  ntop-license                    1.0-606                                 amd64        ntop utility applications.
ii  ntopng                          6.4.250501-25736                        amd64        Web-based traffic monitoring.
ii  ntopng-data                     6.4.250501                              all          Geolocation databases for ntopng and other ntop software packaged from https://db-ip.com
ii  pfring                          9.0.0-9880                              amd64        PF_RING (http://www.ntop.org/pf_ring/) [9.0.0-stable:b7883f2eefab5ea6c15d27fa8bbb98c1220ecb30]

[System] [System Error] [system]
System error detected in ntopng, please report it. Error message: /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:698: bad argument #13 to 'format' (number expected, got nil)

**Comment by MatteoBiscosi** [comment]
Hi @takenek I added a new trace in order to understand the issue you have. In a couple of hours a new update should be available, when possible please update, wait for a couple of hours and run:
journalctl -u ntopng > log.txt
And forward me the log.txt file

**Comment by takenek** [comment]
Hi,
Thanks for the quick response.

Just to let you know – the issue occurred only three times and hasn’t happened since. It happened during what appeared to be an attempted break-in to the server – strange POST/GET requests were being sent to a service running on the server.

I'll keep monitoring the situation and will update ntopng as soon as the new version becomes available. If the issue reoccurs, I’ll collect and forward the logs as requested.

Best regards,
TaKeN

**Comment by MatteoBiscosi** [comment]
Hi @takenek glad to hear that, i added a trace in order to understand which is the case that causes issues.
For now i'll close the ticket if you are not encountering the issue anymore, however in case the issue come back please reopen the ticket or open a new one with the logs of ntopng:
journactl -u ntopng > log.txt
and share the log.txt file

**Comment by takenek** [comment]
The problem still exists. I have sent the logs to your email address.

**Comment by MatteoBiscosi** [comment]
Hi @takenek what's your ntopng version? Yesterday i pushed a possible fix, if you can update to the latest ntopng stable versione and let me know

**Comment by takenek** [comment]
Hi,

I'm currently using the following version:

> 
> ii  ntopng                          6.4.250530-25892        amd64   Web-based traffic monitoring.
> ii  ntopng-data                     6.4.250530              all     Geolocation databases for ntopng
> ii  apt-ntop-stable                 2.10-29                 all     ntop stable apt package repository
> ii  ntop-license                    1.0-607                 amd64   ntop utility applications.
> ii  pfring                          9.0.0-9959              amd64   PF_RING
> 

Unfortunately, I'm still experiencing the same issue today with this version. Here are the recent logs:

> 06/06/2025 10:51:00  [System Error] /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:767: bad argument #13 to 'format' (number expected, got nil)
> 06/06/2025 10:53:01  [System Error] /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:767: bad argument #13 to 'format' (number expected, got nil)
> 06/06/2025 10:54:00  [System Error] /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:767: bad argument #13 to 'format' (number expected, got nil)


Best regards,
TaKeN

**Comment by takenek** [comment]
Hello @MatteoBiscosi ,

Now I use the following version:

> root@NAT:~# dpkg -l | grep ntop
> ii  apt-ntop-stable     2.10-29           all     ntop stable apt package repository
> ii  ntop-license        1.0-607           amd64   ntop utility applications.
> ii  ntopng              6.4.250605-25917  amd64   Web-based traffic monitoring.
> ii  ntopng-data         6.4.250605        all     Geolocation databases for ntopng and other ntop software packaged from https://db-ip.com
> ii  pfring              9.0.0-9970        amd64   PF_RING (http://www.ntop.org/pf_ring/)


And the problem still exists:
> 2025-06-12T12:23:20.975513+02:00 NAT ntopng[1996084]: 12/Jun/2025 12:23:20 [LuaEngine.cpp:702] WARNING: /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:774: bad argument #13 to 'format' (number expected, got nil) [/usr/share/ntopng/pro/scripts/callbacks/minute-delayed/interface/assets.lua]
> 2025-06-12T12:24:14.975134+02:00 NAT ntopng: 12/Jun/2025 12:24:14 [LuaEngine.cpp:702] WARNING: /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:774: bad argument #13 to 'format' (number expected, got nil) [/usr/share/ntopng/pro/scripts/callbacks/minute-delayed/interface/assets.lua]
> 2025-06-12T12:24:14.975332+02:00 NAT ntopng[1996084]: 12/Jun/2025 12:24:14 [LuaEngine.cpp:702] WARNING: /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:774: bad argument #13 to 'format' (number expected, got nil) [/usr/share/ntopng/pro/scripts/callbacks/minute-delayed/interface/assets.lua]
> 2025-06-12T12:25:45.038632+02:00 NAT ntopng: 12/Jun/2025 12:25:45 [LuaEngine.cpp:702] WARNING: /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:774: bad argument #13 to 'format' (number expected, got nil) [/usr/share/ntopng/pro/scripts/callbacks/minute-delayed/interface/assets.lua]
> 2025-06-12T12:25:45.038770+02:00 NAT ntopng[1996084]: 12/Jun/2025 12:25:45 [LuaEngine.cpp:702] WARNING: /usr/share/ntopng/pro/scripts/lua/modules/asset_utils.lua:774: bad argument #13 to 'format' (number expected, got nil) [/usr/share/ntopng/pro/scripts/callbacks/minute-delayed/interface/assets.lua]


Restarting the service with "systemctl restart ntopng.service" temporarily resolves the issue.

Best regards,
TaKeN

**Comment by MatteoBiscosi** [comment]
Hi @takenek , we are going to release the new ntopng stable version in this week, please after the new release let me know if the issue persists
