### ISSUE TITLE
cannot delete an 'Active Monitoring' host of type 'Throughput' --- neither able to edit nor delete it!

### ISSUE THREAD

**Issue by uwaqar** [ntop/ntopng#9447]
<img width="1774" height="886" alt="Image" src="https://github.com/user-attachments/assets/f578b87c-5dde-4f91-83cb-816b69be0091" />

**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS
* Architecture: x86_64
* ntopng version/revision: 6.4.250725

**What happened**:

I added google.com as a host of type throughput in active monitoring just testing. I am neither able to edit not delete that host from the list of active monitoring hosts

**How did you reproduce it?**
repeat what I did

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @uwaqar the issue should now be fixed, please update and let me know

**Comment by uwaqar** [comment]
upgraded ntopng and successfully tested. This issue is fixed. thnx

**Comment by growlf** [comment]
I am having the same problem with editing or deleting one that is of type 'ICMP' - is this related? Or a new ticket?  I did just update to the `:latest` and the issue still persists.
