### ISSUE TITLE
Active Monitoring entries cannot be edited

### ISSUE THREAD

**Issue by uwaqar** [ntop/ntopng#9475]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS
* Architecture: x86_64
* ntopng version/revision: 6.4.250807

**What happened**:

The EDIT drop down for the entries in Active Monitoring doesn't edit the settings for those hosts. It keeps on spinning but doesn't edit the settings for the hosts in active monitoring. 

**How did you reproduce it?**

<img width="1769" height="832" alt="Image" src="https://github.com/user-attachments/assets/be47fa6f-7e12-4e15-93b6-116239f77379" />

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @uwaqar i pushed a possible fix, please in a couple of hours update and let me know

**Comment by uwaqar** [comment]
upgraded and tried in both chrome and firefox browsers without any luck. The settings are not editable

**Comment by DGabri** [comment]
Hi @uwaqar this is working on our end with the latest dev version, on both chrome and firefox: ntopng Enterprise XL v.6.5.250808 (Ubuntu 22.04.4 LTS). Still not working on your side? What version are you running now?

Thank you
