### ISSUE TITLE
[nEdge] Invalid Host Location Sort

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#9706]
<img width="682" height="662" alt="Image" src="https://github.com/user-attachments/assets/9bc2d091-d6c8-4c35-a34c-23761b014c99" />

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed, also in the MAC Address page

**Comment by lucaderi** [comment]
Still broken in hosts (MACs are ok)

<img width="599" height="815" alt="Image" src="https://github.com/user-attachments/assets/6b3d4570-cf1e-4c67-ade6-3c1e085f988d" />

**Comment by MatteoBiscosi** [comment]
The issue should have been fixed for the hosts too.

**Comment by lucaderi** [comment]
Verified as fixed
